alibaba/ice

layouts/HeaderAsideFooterLayout/src/Layout.scss
layouts/HeaderAsideFooterResponsiveLayout/src/Layout.scss
layouts/HeaderFooterLayout/src/Layout.scss

这个地方 background-position 也不是 center, background-position默认值 top  left, 所以去掉更合理

fix: layouts

---

.github/CONTRIBUTING.md
.github/GIT_COMMIT_SPECIFIC.md
README.md

chore: add readme

---

layouts/FixedHeaderFooterResponsiveLayout/README.md
layouts/FixedHeaderFooterResponsiveLayout/package.json
layouts/HeaderAsideFooterLayout/README.md
layouts/HeaderAsideFooterLayout/package.json
layouts/HeaderAsideFooterResponsiveLayout/README.md
layouts/HeaderFooterLayout/README.md
layouts/HeaderFooterLayout/package.json
scaffords/ice-design-lite/README.md
scaffords/ice-design-pro/README.md

docs: improve typo

---

tools/ice-scripts/lib/config/paths.js

fix(hotpatch): do not throw exception while buildConfig not exists

---

scripts/generate-marterials-database.js
scripts/helpers/dep-analyze.js
scripts/validate-commit-msg.js

feat: add createdTime for data

---

blocks/LandingIntroBanner/src/LandingIntroBanner.jsx
blocks/LandingIntroBanner/src/LandingIntroBanner.scss
blocks/LandingIntroBanner/src/__components_Header__.jsx
blocks/LandingIntroBanner/src/__components_Logo__.jsx
blocks/LandingIntroBanner/src/__navs__.js
layouts/BlankLayout/README.md
layouts/BlankLayout/demo/index.html
layouts/BlankLayout/demo/index.js
layouts/BlankLayout/mock/blank-layout.json
layouts/BlankLayout/package.json
layouts/BlankLayout/src/Layout.jsx
layouts/BlankLayout/src/Layout.scss
layouts/BlankLayout/src/index.js

Add new blank layout

---

scaffords/ice-design-lite/package.json
scaffords/ice-design-pro/package.json

issues: https://github.com/alibaba/ice/issues/98

fix: update scafford description

---

tools/ice-scripts/lib/config/getBabelConfig.js

feat: add polyfill-on-demand

---

tools/ice-scripts/lib/config/getBabelConfig.js
tools/ice-scripts/package.json

fix: use es module instead of commonjs

---

scaffolds/ice-design-cms/src/navs.js
scaffolds/ice-design-lite/src/navs.js
scaffolds/ice-design-pro/src/navs.js

后边我们的物料要注意遵守 ES Modules, 前面写的不规范踩了坑了

fix: navs to es modules

---

blocks/UserTrafficStastistics/README.md
blocks/UserTrafficStastistics/demo/index.html
blocks/UserTrafficStastistics/demo/index.js
blocks/UserTrafficStastistics/mock/application-progress.json
blocks/UserTrafficStastistics/package.json
blocks/UserTrafficStastistics/src/UserTrafficStastistics.jsx
blocks/UserTrafficStastistics/src/index.js

feat: add block

---

tools/ice-scripts/lib/config/paths.js
tools/ice-scripts/lib/config/webpack.config.prod.js

fix https://github.com/alibaba/ice/issues/193

feat: change html assets generator path

---

docs/iceworks.md

"Visual Stadio Code" change to "Visual Studio Code"

DOC: fix typo error

---

tools/ice-scripts/lib/config/getPlugins.js

feat: add NODE_ENV for builder

---

blocks/OverviewChart/src/LineChart.jsx
blocks/TabTable/src/TabTable.jsx
blocks/VisitorsLocationChart/README.md
blocks/VisitorsLocationChart/package.json
blocks/VisitorsLocationChart/src/VisitorsLocationChart.jsx
scaffolds/ice-design-analytical/src/pages/Dashboard/components/FlowStatistics/LineChart.jsx
scaffolds/ice-design-analytical/src/pages/Dashboard/components/OverviewChart/LineChart.jsx
scaffolds/ice-design-analytical/src/pages/Dashboard/components/VisitorsLocationChart/MapChart.jsx
scaffolds/ice-design-analytical/src/pages/Dashboard/components/VisitorsLocationChart/VisitorsLocationChart.jsx
scaffolds/ice-design-cms/src/pages/CateList/components/TabTable/TabTable.jsx
scaffolds/ice-design-cms/src/pages/PostList/components/TabTable/TabTable.jsx
scaffolds/ice-design-cms/src/pages/TagList/components/TabTable/TabTable.jsx
scaffolds/ice-design-cms/src/pages/UserList/components/TabTable/TabTable.jsx
scaffolds/ice-design-pro/src/pages/BasicTable/components/TabTable/TabTable.jsx

https://github.com/alibaba/ice/issues/291

chore: block optim

---

tools/ice-scripts/lib/config/getUserConfig.js
tools/ice-scripts/lib/config/webpack.config.basic.js
tools/ice-scripts/lib/config/webpack.server.config.js
tools/ice-scripts/lib/dev.js
tools/ice-scripts/package.json

.webpackrc.js  示例 
```js
const proxyTarget = 'http://127.0.0.1:7001';
module.exports = {
devServer: {
proxy: {
'/api': {
target: proxyTarget,
pathRewrite: { '^/api': '' },
bypass: function(req, res, proxyOpt) {
// 标识 proxy 开启
res.set('x-ice-proxy', 'on');
res.set('x-ice-proxy-by', proxyTarget);
}
}
}
}
};
```

Support webpackrc

---

tools/ice-devtools/database/generate-marterials-database.js
tools/ice-devtools/database/generate.js

feat: 兼容新的 marterials 字段标准
fix: screenshot 字段

feat: 兼容新的 marterials 字段标准

---

vue-materials/blocks/TagMessageList/README.md
vue-materials/blocks/TagMessageList/package.json
vue-materials/blocks/TagMessageList/src/TagMessageList.vue
vue-materials/blocks/TagMessageList/src/index.js

Related Issue: https://github.com/alibaba/ice/issues/411

feat(vue-material): add block - TagMessageList;

---

vue-materials/blocks/BasicException/README.md
vue-materials/blocks/BasicException/package.json
vue-materials/blocks/BasicNotFound/package.json
vue-materials/blocks/NotPermission/README.md
vue-materials/blocks/NotPermission/package.json

fix: update vue materials screenshot

fix: update vue materials screenshot

---

react-materials/blocks/IntroTab/README.md
react-materials/blocks/IntroTab/package.json
react-materials/blocks/IntroTab/src/IntroTab.jsx
react-materials/blocks/IntroTab/src/index.js
react-materials/blocks/IntroTab/src/index.scss
react-materials/blocks/SlideBanner/README.md
react-materials/blocks/SlideBanner/package.json
react-materials/blocks/SlideBanner/src/SlideBanner.jsx
react-materials/blocks/SlideBanner/src/index.js
react-materials/blocks/SlideBanner/src/index.scss

feat: add SlideBanner

---

tools/ice-scripts/lib/config/webpack.server.config.js
tools/ice-scripts/package.json

fix: serve file cros

---

vue-materials/scaffolds/d2-admin-ice/.env
vue-materials/scaffolds/d2-admin-ice/package.json

d2admin information update

---

vue-materials/blocks/BarChart/package.json
vue-materials/blocks/BasicException/package.json
vue-materials/blocks/BasicForm/package.json
vue-materials/blocks/BasicNotFound/package.json
vue-materials/blocks/BasicTable/package.json
vue-materials/blocks/DataDisplay/package.json
vue-materials/blocks/DiyToggleChart/package.json
vue-materials/blocks/EmptyContent/package.json
vue-materials/blocks/FixedTable/package.json
vue-materials/blocks/FunnelChart/package.json
vue-materials/blocks/GaugeChart/package.json
vue-materials/blocks/HeatmapChart/package.json
vue-materials/blocks/HistogramChart/package.json
vue-materials/blocks/LineChart/package.json
vue-materials/blocks/MapToggleChart/package.json
vue-materials/blocks/NormalToggleChart/package.json
vue-materials/blocks/NotPermission/package.json
vue-materials/blocks/PieChart/package.json
vue-materials/blocks/RadarChart/package.json
vue-materials/blocks/RingChart/package.json
vue-materials/blocks/ScatterChart/package.json
vue-materials/blocks/SimpleFooter/package.json
vue-materials/blocks/TabTable/package.json
vue-materials/blocks/TagMessageList/package.json
vue-materials/blocks/UserLogin/package.json

in order to open correct link in ice work, fix vue materials repo url

fix:modify vue materials block repo url

---

react-materials/blocks/OperationTable/package.json
react-materials/blocks/OperationTable/src/DialogDecorator.js
react-materials/blocks/OperationTable/src/EditorInfoDialog.jsx

fix: OperationTable close delay

---

vue-materials/blocks/WaterfallChart/README.md
vue-materials/blocks/WaterfallChart/package.json
vue-materials/blocks/WaterfallChart/src/WaterfallChart.vue
vue-materials/blocks/WaterfallChart/src/index.js

Add waterfall typed chart from v-charts lib to vue materials

feat: add vue-materials/WaterfallChart block

---

vue-materials/blocks/SelectTable/README.md
vue-materials/blocks/SelectTable/package.json
vue-materials/blocks/SelectTable/src/SelectTable.vue
vue-materials/blocks/SelectTable/src/index.js

Add select table

---

react-materials/components/balloon-confirm/.gitignore
react-materials/components/balloon-confirm/README.md
react-materials/components/balloon-confirm/demo/customChildren.md
react-materials/components/balloon-confirm/demo/usage.md
react-materials/components/balloon-confirm/package.json
react-materials/components/balloon-confirm/src/BalloonConfirm.jsx
react-materials/components/balloon-confirm/src/index.js
react-materials/components/balloon-confirm/src/main.scss

Add react component BalloonConfirm

feat: add balloon confirm

---

vue-materials/blocks/D2Crud/README.md
vue-materials/blocks/D2Crud/package.json
vue-materials/blocks/D2Crud/src/D2Crud.vue
vue-materials/blocks/D2Crud/src/index.js
vue-materials/blocks/D2CrudSimple/README.md
vue-materials/blocks/D2CrudSimple/package.json
vue-materials/blocks/D2CrudSimple/src/D2Crud.vue
vue-materials/blocks/D2CrudSimple/src/index.js

add D2Crud Block and D2CrudSimple Block

D2Crud Block

---

rax-materials/scaffolds/miniapp-lite/package.json
rax-materials/scaffolds/operating-dashboard/package.json
rax-materials/scaffolds/posts-admin/package.json
rax-materials/scaffolds/posts-admin/src/components/item/index.html
rax-materials/scaffolds/posts-admin/src/pages/drafts/index.html
rax-materials/scaffolds/posts-admin/src/pages/posts/index.html
rax-materials/scaffolds/posts-admin/src/pages/settings/index.html
rax-materials/scaffolds/products-admin/package.json
rax-materials/scaffolds/products-admin/src/pages/manage/blocks/productList/index.html

refactor: remove v-bind syntax

---

react-materials/blocks/CreativeRegister/package.json
react-materials/blocks/CreativeRegister/src/RegisterForm.js

fix issue: https://github.com/alibaba/ice/issues/954

fix:  validate form

---

vue-materials/blocks/TabTable/src/TabTable.vue
vue-materials/blocks/TabTable/src/components/DeleteBalloon.vue
vue-materials/blocks/TabTable/src/components/EditDialog.vue

fixed [https://github.com/alibaba/ice/issues/925](https://github.com/alibaba/ice/issues/925)
> 请忽略我起错了的分支名称

fixed issue 925

---

tools/css-prefix-plugin/README.md
tools/css-prefix-plugin/index.js
tools/css-prefix-plugin/lib/css-prefix-loader.js
tools/css-prefix-plugin/lib/css-prefix-plugin.js
tools/css-prefix-plugin/package.json
tools/ice-scripts/lib/build.js
tools/ice-scripts/lib/config/getBabelConfig.js
tools/ice-scripts/lib/config/getEntryByPages.js
tools/ice-scripts/lib/config/getEntryHtmlPlugins.js
tools/ice-scripts/lib/config/getPlugins.js
tools/ice-scripts/lib/config/getProxyConfig.js
tools/ice-scripts/lib/config/getRules.js
tools/ice-scripts/lib/config/webpack.config.basic.js
tools/ice-scripts/lib/config/webpack.config.dev.js
tools/ice-scripts/lib/dev.js
tools/ice-scripts/lib/helpers/npmUpdate.js
tools/ice-scripts/package.json
tools/ice-skin-loader/lib/createSkinExtraContent.js
tools/ice-skin-loader/lib/index.js
tools/ice-skin-loader/package.json

* 通过 css-prefix-plugin 支持 @icedesign/base 0.x 和 @alifd/next 1.x 的使用
* @icedesign/base 1.x 的工程改动不在这个分支提了，改动有些大，等整体 ready 之后再提

feat: add css-prefix-plugin

---

vue-materials/scaffolds/d2-admin-ice/package.json
vue-materials/scaffolds/d2-admin-ice/src/layouts/HeaderAside/components/header-size/index.vue

代码更新 详见 [https://github.com/d2-projects/d2-admin/releases/tag/1.5.9](https://github.com/d2-projects/d2-admin/releases/tag/1.5.9)

D2Admin code update

---

scripts/generate-biz-components.js
tools/component-docs-generator/README.md
tools/component-docs-generator/index.js
tools/component-docs-generator/package.json

1. component-docs-generator 支持 outputFilename 参数

feat: output filename support

---

tools/ice-scripts/CHANGES.md
tools/ice-scripts/lib/config/getPlugins.js
tools/ice-scripts/package.json

* fix issue:  https://github.com/alibaba/ice/issues/1057
* relative issue: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250

fix: filter mini-css-extract-plugin warnings

---

tools/iceworks/renderer/src/pages/Home/ProjectDashboard/Assets.jsx

**[iceworks]** add build button on assets card

Build optimization

---

tools/ice-scripts/CHANGES.md
tools/ice-scripts/lib/dev.js

**[ice-scripts]**auto open browser after first compile under dev mode

chore: auto open browser after first compile

---

404.html
index.html

chore: 升级静态资源版本

---

tools/ice-scripts/lib/config/getPlugins.js

* css-prefix 插件可以通过 buildConfig 开启或关闭
* 关联讨论：https://github.com/alibaba/ice/pull/1121#issuecomment-444370682
* 关于 css-prefix 的使用文档暂不对外透出，以免影响用户的困扰

feat: css prefix support

---

react-materials/components/form-binder/README.md
react-materials/components/form-binder/package.json
react-materials/components/form-binder/src/FormBinderWrapper.jsx

1. FormbinderWrapper 使用 `<React.Fragment>` 支持返回多个节点
2. 修复文档错误

feat: multiple elements support

---

docs/advanced/webpackrc.md

chore: fix typo

---

.travis.yml
package.json
react-materials/blocks/GeekEvents/package.json
react-materials/blocks/Partners/package.json
scripts/check-materials-publish.js

1. 更新 ci 脚本，去掉自动发布物料流程，如果有物料未发布则给出提示
2. 更新区块名

Update ci scripts

---

database/block-group.json

* 在根目录下新建 database 目录，用于存放一些常用的数据配置

feat: add blockGroup db

---

vue-materials/blocks/D2Crud/README.md
vue-materials/blocks/D2Crud/package.json
vue-materials/blocks/D2CrudSimple/README.md
vue-materials/blocks/D2CrudSimple/package.json

`@d2-projects/d2-crud-ice-block` and `@d2-projects/d2-crud-ice-block-simple`

new package name

---

README.md

chore: update qrcode

---

templates/ice-react-app-template/meta.js
templates/ice-react-app-template/package.json
templates/ice-react-app-template/template/package.json
templates/ice-react-block-template/package.json
templates/ice-react-block-template/template/package.json
templates/ice-react-materials-template/package.json
templates/ice-react-materials-template/template/blocks/Greeting/_package.json
templates/ice-react-materials-template/template/blocks/Greeting/src/index.js
templates/ice-react-materials-template/template/package.json
templates/ice-react-materials-template/template/scaffolds/lite/package.json
templates/ice-react-materials-template/template/scaffolds/lite/src/components/Greeting/index.js
templates/ice-react-materials-template/template/scaffolds/lite/src/pages/Home/index.js

fix registry config
fix 默认无缩略图的问题
fix 文档地址
fix lint

templates 优化

---

docs/materials/sync-material.md
tools/ice-devtools/lib/block/start.js
tools/ice-devtools/lib/sync.js

fix: warning in log

---

react-materials/scaffolds/ice-design-schools/README.md
react-materials/scaffolds/ice-design-schools/package.json
react-materials/scaffolds/ice-design-schools/src/layouts/BasicLayout/components/Aside/Aside.scss
react-materials/scaffolds/ice-design-schools/src/pages/Dashboard/components/QuickNavigation/QuickNavigation.jsx

Refactor school admin

---

react-materials/scaffolds/ice-algorithm-model-admin/README.md
react-materials/scaffolds/ice-algorithm-model-admin/package.json
react-materials/scaffolds/ice-algorithm-model-admin/src/layouts/BasicLayout/components/Header/Header.scss
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelPerformance/components/Overview/Overview.jsx

chore: adjust color

---

docs/materials/add-block.md
docs/materials/add-templates.md
docs/materials/quick-start.md

fix: update docs (#1232)

---

tools/iceworks/renderer/src/components/Scaffold/Item.jsx
tools/iceworks/renderer/src/components/Scaffold/Panel.jsx

* 使用非 ice-scripts 的模板新建项目时添加提示

feat: add confirm dialog when create new project

---

react-materials/components/container/demo/all.md
react-materials/components/container/package.json
react-materials/components/container/src/IceContainer.jsx

upgrade container to @alifd/next

upgrade container to @alifd/next

---

react-materials/components/balloon-confirm/demo/customChildren.md
react-materials/components/balloon-confirm/demo/usage.md
react-materials/components/balloon-confirm/package.json
react-materials/components/balloon-confirm/src/BalloonConfirm.jsx

upgrade balloon-confirm to @alifd/next

upgrade balloon-confirm to @alifd/next

---

react-materials/components/dynamic-icon/demo/all.md
react-materials/components/dynamic-icon/demo/simple.md
react-materials/components/dynamic-icon/package.json

upgrade @icedesign/dynamic-icon to @alifd/next

upgrade @icedesign/dynamic-icon to @alifd/next 

---

react-materials/components/container/demo/all.md
react-materials/components/container/package.json
react-materials/components/container/src/IceContainer.jsx

feat: upgrade container to @alifd/next

feat: upgrade container to @alifd/next

---

tools/ice-scripts/lib/config/getRules.js

ice-scripts: add style module for scss/less/css

ice-scripts: add style module for scss/less/css

---

tools/ice-scripts/lib/config/getRules.js

ice-scripts: mod css-module config

ice-scripts: mod css-module config

---

react-materials/scaffolds/ice-contract-management-admin/package.json
react-materials/scaffolds/ice-contract-management-admin/src/components/ContractTable/ContractTable.jsx
react-materials/scaffolds/ice-contract-management-admin/src/components/ContractTable/SearchFilter.jsx
react-materials/scaffolds/ice-contract-management-admin/src/components/ContractTable/index.module.scss
react-materials/scaffolds/ice-contract-management-admin/src/components/CustomForm/CustomForm.jsx
react-materials/scaffolds/ice-contract-management-admin/src/index.js
react-materials/scaffolds/ice-contract-management-admin/src/layouts/BasicLayout/components/Aside/Aside.jsx
react-materials/scaffolds/ice-contract-management-admin/src/layouts/BasicLayout/components/Aside/index.module.scss
react-materials/scaffolds/ice-contract-management-admin/src/layouts/BasicLayout/components/Header/Header.jsx
react-materials/scaffolds/ice-contract-management-admin/src/layouts/BasicLayout/index.js
react-materials/scaffolds/ice-contract-management-admin/src/layouts/BasicLayout/index.scss
react-materials/scaffolds/ice-contract-management-admin/src/layouts/UserLayout/UserLayout.scss
react-materials/scaffolds/ice-contract-management-admin/src/pages/ContractCenter/ContractCenter.jsx
react-materials/scaffolds/ice-contract-management-admin/src/pages/ContractCenter/components/SearchHistory/SearchHistory.jsx
react-materials/scaffolds/ice-contract-management-admin/src/pages/MyContract/MyContract.jsx
react-materials/scaffolds/ice-contract-management-admin/src/pages/MyContract/components/CreateContractForm/index.jsx
react-materials/scaffolds/ice-contract-management-admin/src/pages/MyContract/components/CustomNotice/CustomNotice.jsx
react-materials/scaffolds/ice-contract-management-admin/src/pages/MyContract/index.module.scss
react-materials/scaffolds/ice-contract-management-admin/src/pages/UserLogin/UserLogin.jsx
react-materials/scaffolds/ice-contract-management-admin/src/pages/UserRegister/UserRegister.jsx

upgrade ice-contract-management-admin to fusion design

upgrade ice-contract-management-admin to fusion design

---

tools/ice-scripts/lib/config/getRules.js
tools/ice-scripts/package.json

mod css module localIdentName

---

templates/ice-react-app-template/package.json
templates/ice-react-app-template/template/_package.json
tools/ice-devtools/CHANGELOG.md
tools/ice-devtools/config/webpack.base.js
tools/ice-devtools/package.json
tools/ice-devtools/utils/dep-analyze.js

- [bugfix] 修复 generate 时报 babel-core 找不到的问题
- [bugfix] 添加 file-loader, 解决大图片的加载失败问题
- [bugfix] 修复 scaffold html 模板拉取失败问题

fix: generate 时报 babel-core 找不到的问题

---

react-materials/scaffolds/ice-algorithm-model-admin/package.json
react-materials/scaffolds/ice-algorithm-model-admin/src/components/CustomTable/CustomTable.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/index.js
react-materials/scaffolds/ice-algorithm-model-admin/src/layouts/BasicLayout/components/Header/Header.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/layouts/BasicLayout/components/Header/Header.scss
react-materials/scaffolds/ice-algorithm-model-admin/src/layouts/UserLayout/components/Header/index.js
react-materials/scaffolds/ice-algorithm-model-admin/src/layouts/UserLayout/index.js
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelManagement/components/ModelTable/ModelTable.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelManagement/components/ModelTable/TableHead.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelManagement/components/ModelTable/table.module.scss
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelMarket/components/ModelCard/ModelCard.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelMarket/components/ModelCard/index.module.scss
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelPerformance/ModelPerformance.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelPerformance/components/ModelList/ModelList.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelPerformance/components/Overview/Overview.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/ModelPerformance/components/Performance/Performance.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/Setting/components/BaseSetting/index.js
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/UserLogin/UserLogin.jsx
react-materials/scaffolds/ice-algorithm-model-admin/src/pages/UserRegister/UserRegister.jsx

upgrade ice algorithm model admin to fusion design

upgrade ice algorithm model admin to fusion design

---

react-materials/scaffolds/ice-material-dashboard/config-overrides.js
react-materials/scaffolds/ice-material-dashboard/package.json
react-materials/scaffolds/ice-material-dashboard/rewire-scss.js

feat: upgrade material-dashboard to fusion desgin

feat: upgrade material-dashboard to fusion desgin

---

react-materials/scaffolds/create-react-app/config-overrides.js
react-materials/scaffolds/create-react-app/package.json
react-materials/scaffolds/create-react-app/rewire-scss.js
react-materials/scaffolds/create-react-app/src/App.js
react-materials/scaffolds/create-react-app/src/App.scss

feat: upgrade create-react-app to fusion design

feat: upgrade create-react-app to fusion design

---

react-materials/scaffolds/ice-coreui-admin/config-overrides.js
react-materials/scaffolds/ice-coreui-admin/package.json
react-materials/scaffolds/ice-coreui-admin/rewire-scss.js

feat: upgrade coreui admin to fusion design

feat: upgrade coreui admin to fusion design

---

react-materials/scaffolds/ice-creative-dashboard/config-overrides.js
react-materials/scaffolds/ice-creative-dashboard/package.json
react-materials/scaffolds/ice-creative-dashboard/rewire-scss.js
react-materials/scaffolds/ice-creative-dashboard/src/pages/Dashboard/Dashboard.jsx

feat: upgrade template to fusion design

feat: upgrade template to fusion design

---

react-materials/scaffolds/ice-light-bootstrap-dashboard/config-overrides.js
react-materials/scaffolds/ice-light-bootstrap-dashboard/package.json
react-materials/scaffolds/ice-light-bootstrap-dashboard/rewire-scss.js
react-materials/scaffolds/ice-light-bootstrap-dashboard/src/index.js
react-materials/scaffolds/ice-light-bootstrap-dashboard/src/pages/Dashboard/Dashboard.jsx

upgrade light-bootstrap-dashboard to fusion design

upgrade light-bootstrap-dashboard to fusion design

---

react-materials/scaffolds/ice-task-management-admin/package.json
react-materials/scaffolds/ice-task-management-admin/src/components/ContainerTitle/ContainerTitle.jsx
react-materials/scaffolds/ice-task-management-admin/src/index.js
react-materials/scaffolds/ice-task-management-admin/src/layouts/BasicLayout/components/Aside/Aside.jsx
react-materials/scaffolds/ice-task-management-admin/src/layouts/BasicLayout/components/Aside/Aside.scss
react-materials/scaffolds/ice-task-management-admin/src/layouts/BasicLayout/components/Footer/Footer.jsx
react-materials/scaffolds/ice-task-management-admin/src/layouts/BasicLayout/components/Header/Header.jsx
react-materials/scaffolds/ice-task-management-admin/src/layouts/BasicLayout/components/Header/Header.scss
react-materials/scaffolds/ice-task-management-admin/src/layouts/UserLayout/components/Header/index.js
react-materials/scaffolds/ice-task-management-admin/src/layouts/UserLayout/index.js
react-materials/scaffolds/ice-task-management-admin/src/pages/Activities/components/ActiveTimeline/index.js
react-materials/scaffolds/ice-task-management-admin/src/pages/AddDocument/components/ContentEditor/ContentEditor.jsx
react-materials/scaffolds/ice-task-management-admin/src/pages/AddMember/components/AddForm/index.js
react-materials/scaffolds/ice-task-management-admin/src/pages/Dashboard/Dashboard.jsx
react-materials/scaffolds/ice-task-management-admin/src/pages/Dashboard/components/Overview/Overview.jsx
react-materials/scaffolds/ice-task-management-admin/src/pages/Document/components/DocsList/DocsList.jsx
react-materials/scaffolds/ice-task-management-admin/src/pages/Member/components/MemberList/MemberList.jsx
react-materials/scaffolds/ice-task-management-admin/src/pages/Services/components/ServiceCard/ServiceCard.jsx
react-materials/scaffolds/ice-task-management-admin/src/pages/Services/components/ServiceHead/ServiceHead.jsx
react-materials/scaffolds/ice-task-management-admin/src/pages/Setting/components/BasicSetting/BasicSetting.jsx
react-materials/scaffolds/ice-task-management-admin/src/pages/UserLogin/UserLogin.jsx
react-materials/scaffolds/ice-task-management-admin/src/pages/UserRegister/UserRegister.jsx

upgrade ice-task-management-admin to fusion design

upgrade ice-task-management-admin to fusion design

---

react-materials/scaffolds/ice-customer-analysis-admin/package.json
react-materials/scaffolds/ice-customer-analysis-admin/src/components/ContainerTitle/ContainerTitle.jsx
react-materials/scaffolds/ice-customer-analysis-admin/src/components/EventsOverview/EventsOverview.jsx
react-materials/scaffolds/ice-customer-analysis-admin/src/components/EventsOverview/index.module.scss
react-materials/scaffolds/ice-customer-analysis-admin/src/components/PassengerFlow/index.js
react-materials/scaffolds/ice-customer-analysis-admin/src/components/TimeDistribution/index.js
react-materials/scaffolds/ice-customer-analysis-admin/src/components/UserPortrait/index.js
react-materials/scaffolds/ice-customer-analysis-admin/src/components/UserStatChart/UserStatChart.jsx
react-materials/scaffolds/ice-customer-analysis-admin/src/index.js
react-materials/scaffolds/ice-customer-analysis-admin/src/layouts/BasicLayout/components/Aside/Aside.jsx
react-materials/scaffolds/ice-customer-analysis-admin/src/layouts/BasicLayout/components/Aside/Aside.scss
react-materials/scaffolds/ice-customer-analysis-admin/src/layouts/BasicLayout/components/Header/Header.jsx
react-materials/scaffolds/ice-customer-analysis-admin/src/layouts/BasicLayout/components/Header/Header.scss
react-materials/scaffolds/ice-customer-analysis-admin/src/layouts/UserLayout/UserLayout.scss
react-materials/scaffolds/ice-customer-analysis-admin/src/pages/Schedule/Schedule.jsx
react-materials/scaffolds/ice-customer-analysis-admin/src/pages/Schedule/Schedule.module.scss
react-materials/scaffolds/ice-customer-analysis-admin/src/pages/UserLogin/UserLogin.jsx
react-materials/scaffolds/ice-customer-analysis-admin/src/pages/UserRegister/UserRegister.jsx

upgrade ice-customer-analysis-admin to fusion-design

upgrade ice-customer-analysis-admin to fusion-design

---

react-materials/scaffolds/ice-build-platfrom/package.json
react-materials/scaffolds/ice-build-platfrom/src/components/CustomTable/CustomTable.jsx
react-materials/scaffolds/ice-build-platfrom/src/index.js
react-materials/scaffolds/ice-build-platfrom/src/layouts/BasicLayout/components/Header/Header.jsx
react-materials/scaffolds/ice-build-platfrom/src/layouts/BasicLayout/components/Header/Header.scss
react-materials/scaffolds/ice-build-platfrom/src/layouts/UserLayout/components/Header/index.js
react-materials/scaffolds/ice-build-platfrom/src/layouts/UserLayout/index.js
react-materials/scaffolds/ice-build-platfrom/src/pages/Builder/components/BuilderTable/BuilderTable.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/Builder/components/TableFilter/TableFilter.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/Dashboard/components/BasicPieChart/BasicPieChart.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/Dashboard/components/BuilderDistribution/BuilderDistribution.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/Dashboard/components/BuilderDynamic/BuilderDynamic.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/Dashboard/components/BuilderState/BuilderState.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/Dashboard/components/BuilderTimes/BuilderTimes.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/Dashboard/components/CoBranding/CoBranding.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/Dashboard/components/PieLegendChart/PieLegendChart.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/New/New.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/Setting/components/BaseSetting/index.js
react-materials/scaffolds/ice-build-platfrom/src/pages/Task/components/TableFilter/TableFilter.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/UserLogin/UserLogin.jsx
react-materials/scaffolds/ice-build-platfrom/src/pages/UserRegister/UserRegister.jsx

Feat: upgrade ice builder platform to fusion design

Feat: upgrade ice builder platform to fusion design

---

react-materials/scaffolds/ice-design-schools/package.json
react-materials/scaffolds/ice-design-schools/src/index.js
react-materials/scaffolds/ice-design-schools/src/layouts/BasicLayout/BasicLayout.jsx
react-materials/scaffolds/ice-design-schools/src/layouts/BasicLayout/BasicLayout.scss
react-materials/scaffolds/ice-design-schools/src/layouts/BasicLayout/components/Aside/Aside.jsx
react-materials/scaffolds/ice-design-schools/src/layouts/BasicLayout/components/Footer/Footer.scss
react-materials/scaffolds/ice-design-schools/src/layouts/BasicLayout/components/Header/Header.jsx
react-materials/scaffolds/ice-design-schools/src/layouts/BasicLayout/components/Header/Header.scss
react-materials/scaffolds/ice-design-schools/src/layouts/UserLayout/components/Header/index.js
react-materials/scaffolds/ice-design-schools/src/layouts/UserLayout/index.js
react-materials/scaffolds/ice-design-schools/src/pages/AddStudent/components/AddForm/index.js
react-materials/scaffolds/ice-design-schools/src/pages/Dashboard/components/OverviewChart/OverviewChart.jsx
react-materials/scaffolds/ice-design-schools/src/pages/Dashboard/components/QuickNavigation/QuickNavigation.jsx
react-materials/scaffolds/ice-design-schools/src/pages/Setting/components/BaseSetting/index.js
react-materials/scaffolds/ice-design-schools/src/pages/TestManagement/components/Content/Content.jsx
react-materials/scaffolds/ice-design-schools/src/pages/TestManagement/components/Filter/Filter.jsx
react-materials/scaffolds/ice-design-schools/src/pages/TestManagement/components/Filter/index.module.scss
react-materials/scaffolds/ice-design-schools/src/pages/UserLogin/UserLogin.jsx
react-materials/scaffolds/ice-design-schools/src/pages/UserManagement/components/UserSearch/UserSearch.jsx
react-materials/scaffolds/ice-design-schools/src/pages/UserManagement/components/UserTable/UserTable.jsx
react-materials/scaffolds/ice-design-schools/src/pages/UserRegister/UserRegister.jsx

upgrade ice-design-schools to fusion design

upgrade ice-design-schools to fusion design

---

react-materials/scaffolds/ice-universal-homepage/package.json
react-materials/scaffolds/ice-universal-homepage/src/layouts/BlankLayout/components/Footer/index.jsx
react-materials/scaffolds/ice-universal-homepage/src/layouts/BlankLayout/components/Header/index.jsx
react-materials/scaffolds/ice-universal-homepage/src/layouts/BlankLayout/components/Header/index.module.scss
react-materials/scaffolds/ice-universal-homepage/src/pages/HomePage/components/Data/index.jsx
react-materials/scaffolds/ice-universal-homepage/src/pages/HomePage/components/Feature/index.jsx

feat: upgrade @icedesign/universal-homepage-scaffold to fusion design

feat: upgrade @icedesign/universal-homepage-scaffold to fusion design

---

react-materials/scaffolds/ice-open-platform-landingpage/package.json
react-materials/scaffolds/ice-open-platform-landingpage/src/components/Header/index.jsx
react-materials/scaffolds/ice-open-platform-landingpage/src/components/Header/index.scss
react-materials/scaffolds/ice-open-platform-landingpage/src/index.js

feat: upgrade open-platform-scaffold to fusion design

feat: upgrade open-platform-scaffold to fusion design

---

react-materials/scaffolds/ice-creator-landingpage/package.json
react-materials/scaffolds/ice-creator-landingpage/src/index.js
react-materials/scaffolds/ice-creator-landingpage/src/pages/Home/components/PlatformJoinus/index.jsx
react-materials/scaffolds/ice-creator-landingpage/src/pages/Home/components/PlatformJoinus/index.module.scss
react-materials/scaffolds/ice-creator-landingpage/src/pages/Home/components/PlatformLanding/index.jsx
react-materials/scaffolds/ice-creator-landingpage/src/pages/Home/components/PlatformLanding/index.module.scss
react-materials/scaffolds/ice-creator-landingpage/src/pages/Home/index.jsx

feat: upgrade ice-creator-landing-page to fusion design

feat: upgrade ice-creator-landing-page to fusion design

---

react-materials/scaffolds/ice-website-homepage/package.json
react-materials/scaffolds/ice-website-homepage/src/index.js
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/BrandList/index.jsx
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/BrandList/index.module.scss
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/DesignLanguage/index.jsx
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/DesignLanguage/index.module.scss
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/IceworksInfo/index.jsx
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/IceworksInfo/index.module.scss
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/LandingIntroBanner/index.jsx
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/LandingIntroBanner/index.module.scss
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/Materials/index.jsx
react-materials/scaffolds/ice-website-homepage/src/pages/Home/components/Materials/index.module.scss

Feat/upgrade ice-website-homepage to fusion design

Feat/upgrade ice-website-homepage to fusion design

---

react-materials/scaffolds/ice-creator-landingpage/package.json
react-materials/scaffolds/ice-creator-landingpage/src/pages/Home/index.jsx
react-materials/scaffolds/ice-design-analysis/package.json
react-materials/scaffolds/ice-design-iceworks/package.json
react-materials/scaffolds/ice-open-platform-landingpage/package.json
react-materials/scaffolds/ice-scroll-screen-homepage/package.json
react-materials/scaffolds/ice-universal-homepage/package.json
react-materials/scaffolds/ice-website-homepage/package.json
react-materials/scaffolds/ice-yunqi-homepage/.editorconfig
react-materials/scaffolds/ice-yunqi-homepage/.eslintignore
react-materials/scaffolds/ice-yunqi-homepage/.eslintrc
react-materials/scaffolds/ice-yunqi-homepage/package.json
scripts/scaffolds.js

* 发布未发布的模板
* 替换 homepage 为 unpkg 地址
* 调整模板展示顺序

chore: publish scaffold

---

react-materials/scaffolds/ice-design-dashboard/package.json
react-materials/scaffolds/ice-design-dashboard/src/index.js
react-materials/scaffolds/ice-design-dashboard/src/layouts/BlankLayout/components/Header/Header.jsx
react-materials/scaffolds/ice-design-dashboard/src/layouts/BlankLayout/components/Header/Header.scss
react-materials/scaffolds/ice-design-dashboard/src/layouts/BlankLayout/components/Logo/Logo.jsx
react-materials/scaffolds/ice-design-dashboard/src/layouts/BlankLayout/components/Logo/index.module.scss
react-materials/scaffolds/ice-design-dashboard/src/pages/Dashboard/Dashboard.jsx
react-materials/scaffolds/ice-design-dashboard/src/pages/Dashboard/components/OverviewPieChart/index.js
react-materials/scaffolds/ice-design-dashboard/src/pages/Dashboard/components/OverviewSatesChart/index.js

feat: upgrade @icedesign/dashboard-scaffold to fusion design

feat: upgrade @icedesign/dashboard-scaffold to fusion design

---

react-materials/scaffolds/ice-finance-dashboard/package.json
react-materials/scaffolds/ice-finance-dashboard/src/index.js
react-materials/scaffolds/ice-finance-dashboard/src/layouts/BlankLayout/components/Header/Header.jsx
react-materials/scaffolds/ice-finance-dashboard/src/layouts/BlankLayout/components/Header/Header.scss
react-materials/scaffolds/ice-finance-dashboard/src/layouts/BlankLayout/components/Logo/Logo.jsx
react-materials/scaffolds/ice-finance-dashboard/src/layouts/BlankLayout/components/Logo/index.module.scss
react-materials/scaffolds/ice-finance-dashboard/src/pages/Dashboard/Dashboard.jsx
react-materials/scaffolds/ice-finance-dashboard/src/pages/Dashboard/components/BorrowingChart/index.js
react-materials/scaffolds/ice-finance-dashboard/src/pages/Dashboard/components/CustomTable/index.js
react-materials/scaffolds/ice-finance-dashboard/src/pages/Dashboard/components/CustomTable/index.scss
react-materials/scaffolds/ice-finance-dashboard/src/pages/Dashboard/components/OverviewSatesChart/index.js
react-materials/scaffolds/ice-finance-dashboard/src/pages/Dashboard/components/OverviewSatesChart/index.module.scss
react-materials/scaffolds/ice-finance-dashboard/src/pages/Dashboard/components/TotalAmount/index.js
react-materials/scaffolds/ice-finance-dashboard/src/pages/Dashboard/components/TotalAmount/index.module.scss

feat: upgrade finance-dashboard to fusion design

feat: upgrade finance-dashboard to fusion design

---

tools/ice-scripts/CHANGELOG.md
tools/ice-scripts/bin/ice-build.js
tools/ice-scripts/lib/config/getRules.js
tools/ice-scripts/lib/config/webpack.config.prod.js
tools/ice-scripts/package.json

- 支持 css-module
- 命令行支持 sourcemap 配置

ice-scripts@1.8.1

---

docs/materials/devtools.md

* 重命名 devtools 的 “快速开始” 为 “使用 Devtools”

chore: update docs

---

tools/iceworks/.buildrc
tools/iceworks/app/main/index.js
tools/iceworks/app/package.json
tools/iceworks/app/yarn.lock
tools/iceworks/changelog/2.15.5.json
tools/iceworks/changelog/changelog.json
tools/iceworks/renderer/src/App.jsx
tools/iceworks/renderer/src/datacenter/materialsConfig.js
tools/iceworks/renderer/src/pages/Blocks/index.jsx
tools/iceworks/renderer/src/pages/Scaffolds/index.jsx

1. 浏览器唤起
2. fusion、bizchat物料源移除

Iceworks/release 2.15.5

---

tools/ice-devtools/CHANGELOG.md
tools/ice-devtools/config/webpack.base.js
tools/ice-devtools/package.json

feat: css modules support

---

docs/about.md
tools/ice-devtools/CHANGELOG.md
tools/ice-devtools/config/webpack.base.js
tools/ice-devtools/package.json
tools/ice-scripts/CHANGELOG.md
tools/ice-scripts/lib/config/getRules.js
tools/ice-scripts/lib/config/webpack.config.prod.js
tools/ice-scripts/package.json
tools/iceworks/.buildrc
tools/iceworks/app/main/index.js
tools/iceworks/app/package.json
tools/iceworks/app/yarn.lock
tools/iceworks/changelog/2.15.5.json
tools/iceworks/changelog/changelog.json
tools/iceworks/renderer/src/App.jsx
tools/iceworks/renderer/src/datacenter/materialsConfig.js
tools/iceworks/renderer/src/pages/Blocks/index.jsx
tools/iceworks/renderer/src/pages/Scaffolds/index.jsx

* 站点二维码更新，通过站点加群的人都加不进了，需要手动拉，优先级比较急
* iceworks 2.15.0 版本
* ice-scripts 1.8.3 版本

sync master

---

react-materials/scaffolds/ice-design-pro/package.json
react-materials/scaffolds/ice-design-pro/src/pages/Dashboard/components/PieDoughnutChart/PieDoughnutChart.jsx

fix: overflow

---

tools/ice-devtools/CHANGELOG.md
tools/ice-devtools/config/webpack.block.js
tools/ice-devtools/lib/block/build.js
tools/ice-devtools/package.json

fix: https://github.com/alibaba/ice/issues/1444

fix: build error

---

tools/ice-scripts/CHANGELOG.md
tools/ice-scripts/bin/ice-dev.js
tools/ice-scripts/lib/config/getRules.js
tools/ice-scripts/package.json

原 ice-scripts-midway 分支
ice-scropts 适配新 node 模板 改动

Release/ice scripts 1.8.4

---

templates/ice-midway-template/templates/server/package.json
templates/ice-midway-template/templates/server/src/app/controller/home.ts
templates/ice-midway-template/templates/server/src/app/middleware/assets_info.ts
templates/ice-midway-template/templates/server/src/app/view/index.ejs
templates/ice-midway-template/templates/server/src/config/config.default.ts
templates/ice-midway-template/templates/server/src/config/plugin.ts

feat: add asset prefix for ejs view/

---

scripts/sync-db.js

* 清除多余的 bizcharts [日志](https://travis-ci.org/alibaba/ice/builds/495229859#L1730)，日志太多导致查看构建结构太冗余

chore: clear redundant logs

---

react-materials/components/notification/README.md

https://alibaba.github.io/ice/component/notification

docs: fix markdown table display error

---

react-materials/scaffolds/ice-design-pro/package.json
react-materials/scaffolds/ice-design-pro/src/layouts/BasicLayout/components/Aside/index.js
react-materials/scaffolds/ice-design-pro/src/pages/GeneralTable/GeneralTable.jsx
react-materials/scaffolds/ice-design-pro/src/pages/GeneralTable/components/CustomForm/CustomForm.jsx
react-materials/scaffolds/ice-design-pro/src/pages/ProjectList/components/OverviewChart/index.js

* 修复：升级 @alifd/next 之后 API 变动导致菜单栏响应式时无法收起
* 修复：响应式时表格错乱

chore: pro optimize

---

templates/ice-react-component-template/package.json
templates/ice-react-component-template/template/_package.json
templates/ice-react-materials-template/template/blocks/Greeting/package.json
tools/ice-devtools/CHANGELOG.md
tools/ice-devtools/config/webpack.base.js
tools/ice-devtools/package.json
tools/ice-devtools/template/component/demo.hbs
tools/ice-devtools/template/component/home.hbs
tools/ice-devtools/template/preview/block.react.html.hbs

后续支持 vue 开发同理，工程层面尽量不耦合框架或者 UI 库

chore: devtools 开发组件和区块不 external react

---

react-materials/scaffolds/ice-design-analysis/package.json

* 修复飞冰群用户反馈缺失 moment 依赖导致报错的问题

fix: add moment deps

---

tools/ice-scripts/CHANGELOG.md
tools/ice-scripts/package.json
tools/ice-skin-loader/CHANGELOG.md
tools/ice-skin-loader/lib/index.js
tools/ice-skin-loader/package.json

Fix import next vars file

---

templates/ice-react-materials-template/package.json
templates/ice-react-materials-template/template/blocks/Greeting/package.json

https://github.com/alibaba/ice/commit/6168f1a86a37fe6b231e51781b8be393c112cef7#diff-e5e08776f7b7768031fb32bb221535f5
改错了。。。

fix: template-version

---

docs/pro/i18n.md

* 增加 pro 模板预览地址
* 增加基础组件国际化部分文档

docs: add ConfigProvider docs

---

tools/ice-devtools/CHANGELOG.md
tools/ice-devtools/package.json
tools/ice-devtools/utils/generate-marterials-database.js
tools/ice-devtools/utils/inner-net.js
tools/ice-devtools/utils/npm.js

更新模板默认生成的 npm registry 为 https://registry.npmjs.org
https://docs.npmjs.com/misc/registry

fix: npm registry

---

templates/ice-react-block-template/package.json
templates/ice-react-block-template/template/package.json
templates/ice-react-materials-template/package.json
templates/ice-react-materials-template/template/blocks/Greeting/package.json
tools/ice-devtools/CHANGELOG.md
tools/ice-devtools/config/webpack.block.js
tools/ice-devtools/lib/build.js
tools/ice-devtools/lib/start.js
tools/ice-devtools/package.json
tools/ice-devtools/template/preview/block-react-index.js.hbs

1. 更新模板中的默认依赖
2. 修复 js entry 的依赖路径问题
3. 修复 node env

修复 block 预览错误

---

react-materials/scaffolds/ice-typescript-starter/package.json

* 添加 tsconfig.json 文件确保 npm 发布存在

fix: add tsconfig

---

react-materials/scaffolds/ice-design-pro/package.json
react-materials/scaffolds/ice-design-pro/src/pages/Dashboard/components/ProjectAnalysis/ProjectList.js
react-materials/scaffolds/ice-design-pro/src/pages/GeneralTable/components/SearchFilter/SearchFilter.jsx
react-materials/scaffolds/ice-design-pro/src/pages/ProjectList/components/OverviewChart/index.js
react-materials/scaffolds/ice-design-pro/src/pages/ProjectList/components/ProjectTable/data.js

* 规范 lodash 的引用方式
* 修复相关 Warning

Fix pro deps

---

tools/ice-scripts/lib/config/getResolveAlias.js
tools/ice-scripts/lib/config/getRules.js
tools/ice-scripts/lib/config/webpack.config.basic.js
tools/ice-scripts/lib/loaders/uniteBaseComponentSassLoader.js

- 通过 alias 解决 js 里 import
- 通过 loader 解决 css 里 import

工程层面统一基础组件包

---

tools/iceworks/app/package.json
tools/iceworks/renderer/package.json
tools/iceworks/renderer/src/components/CustomScaffold/Recent.jsx

* template-builder 升级到 2.x 版本将 `@icedesign/base` 替换为 `@alifd/next` 
* 去掉主题配置选项
* 如需测试，请替换 `@icedesign/template-builder` 的版本为 `2.0.0-beta.1`

feat: upgrate iceworks template-builder deps

---

react-materials/scaffolds/ice-design-pro/package.json
react-materials/scaffolds/ice-design-pro/src/layouts/BasicLayout/components/Aside/index.js
react-materials/scaffolds/ice-design-pro/src/layouts/BasicLayout/components/Aside/index.scss

fix: ice-design-pro menu collapse

---

tools/iceworks/app/main/template/utils/getTarballURLBySource.js
tools/iceworks/renderer/src/lib/project-scripts.js

fix: default use cnpm registry

---

tools/iceworks/app/main/paths.js
tools/iceworks/app/main/services/index.js
tools/iceworks/app/main/services/nrm.js
tools/iceworks/app/package.json
tools/iceworks/renderer/src/pages/Settings/Settings.jsx

Feat speed test support

---

tools/iceworks/app/main/paths.js
tools/iceworks/app/main/scaffolder/lib/utils.js
tools/iceworks/app/main/services/index.js
tools/iceworks/app/main/services/nrm.js
tools/iceworks/app/main/services/tracking/index.js
tools/iceworks/app/main/template/utils/getTarballURLBySource.js
tools/iceworks/app/package.json
tools/iceworks/renderer/src/components/PageBlockPicker/index.jsx
tools/iceworks/renderer/src/lib/project-scripts.js
tools/iceworks/renderer/src/pages/Settings/Settings.jsx

* 添加下载流程日志，如 `正在请求区块数据 => 正在解压区块 => 安装依赖` 等详细步骤日志
* 添加具体的容错处理，之前的下载流程没有补获具体的步骤错误，统一都是区块下载失败，这里改成了具体的错误具体抛出
* 部分下载代码重构
* 默认使用 cnpm 源进行下载
* 如果不是使用的 cnpm 源则给出提示，推荐使用 cnpm 源进行下载
fix: https://github.com/alibaba/ice/pull/1564  2 、10

Iceworks download process optim

---

tools/ice-scripts/CHANGELOG.md
tools/ice-scripts/lib/devMiddleware.js
tools/ice-scripts/package.json

- Close #1596 
- 引入问题的 MR：https://github.com/alibaba/ice/pull/1555/files

fix: 修改 const 变量

---

docs/advanced/webpackrc.md
tools/ice-scripts/lib/config/getPlugins.js
tools/ice-scripts/lib/config/webpack.config.basic.js

- 修复 externals 的逻辑，支持用户配置
- 修复无法配置 `buildConfig.output.path` 的问题
- 支持配置 `buildConfig.outputAssetsDir`

Fix ice scripts externals

---

docs/advanced/how-to-dynamic-load.md

fix: 优化动态加载资源文档

---

react-materials/scaffolds/ice-design-pro/package.json
react-materials/scaffolds/ice-design-pro/src/layouts/BasicLayout/index.js
react-materials/scaffolds/ice-design-pro/src/pages/Dashboard/components/Card/Card.jsx
react-materials/scaffolds/ice-design-pro/src/pages/Dashboard/components/TabChart/BasicLine.jsx
react-materials/scaffolds/ice-design-pro/src/pages/Dashboard/components/TabChart/SeriesLine.jsx

https://github.com/alibaba/ice/issues/1619

chore: fix pro ui

---

tools/ice-devtools/utils/demo-loader.js
tools/ice-devtools/utils/demo-router.js
tools/ice-devtools/utils/get-demos.js
tools/ice-devtools/utils/markdown-helper.js

* 修复 markdown 中 code 解析时的默认 lang
* 修复 README 中代码片段被 slice 的问题

fix: markdown code parse error

---

react-materials/components/balloon-confirm/src/BalloonConfirm.jsx

fix BallonConfirm visible
修复BallonConfirm的显示问题
#1640

fix: fix BallonConfirm visible

---

tools/ice-devtools/lib/clear.js
tools/ice-devtools/utils/db.js
tools/ice-devtools/utils/inner-site.js
tools/ice-devtools/utils/site.js

feat: add single material sync

---

tools/iceworks/.buildrc

windows 安装 iceworks 时提供选择安装路径的选择能力

[Iceworks]Iceworks/win change dir

---

tools/iceworks/renderer/src/App.jsx
tools/iceworks/renderer/src/components/RegistryNotice/index.js

* 目前错误率主要是 get-tarball-info-error ，从错误信息来看主要还是走的 npm 源，在启动 iceworks 时给出提示，让用户选择使用 npm 淘宝镜像源下载

[iceworks]add registry check

---

tools/iceworks/app/main/scaffolder/templates/react.index.js.ejs
tools/iceworks/app/main/scaffolder/templates/vue.index.js.ejs
tools/iceworks/renderer/src/components/Block/Block.jsx
tools/iceworks/renderer/src/components/Block/index.scss
tools/iceworks/renderer/src/components/BlockGroupCategory/BlockGroup.jsx
tools/iceworks/renderer/src/components/BlockGroupCategory/index.jsx
tools/iceworks/renderer/src/components/BlockPicker/Panel.jsx
tools/iceworks/renderer/src/pages/Home/CreatPage/index.jsx
tools/iceworks/renderer/src/stores/newpage.js

1. 区块代码生成 description 注释
2. 区块面板增加 description 字段
3. 移除预览页面功能

[Iceworks]descriptions

---

docs/advanced/use-theme.md

docs: add custom icon

---

tools/iceworks/README.md
tools/iceworks/app/package.json

* 在发布之前需要将官网提供的物料数据进行更新，并打包在 iceworks 中

chore: update iceworks readme

---

tools/iceworks/app/main/scaffolder/templates/react.index.js.ejs
tools/iceworks/app/main/scaffolder/templates/vue.index.js.ejs
tools/iceworks/renderer/src/pages/Home/ProjectDashboard/Pages/index.jsx
tools/iceworks/renderer/yarn.lock

fix: editorOpenError

---

tools/iceworks/renderer/src/lib/request-material.js

feat: distinguish between official and custom materials

---

tools/iceworks/app/main/services/editors/index.js
tools/iceworks/renderer/src/pages/Home/ProjectDashboard/Pages/index.jsx

fix: notice reverse

---

tools/iceworks/renderer/src/pages/Home/ProjectDashboard/Aliyun.jsx

fix: oss can't find vue build path

---

tools/ice-devtools/CHANGELOG.md
tools/ice-devtools/lib/generate.js
tools/ice-devtools/lib/sync-unpkg.js
tools/ice-devtools/lib/sync.js
tools/ice-devtools/package.json
tools/ice-devtools/utils/db.js
tools/ice-devtools/utils/generate-marterials-database.js
tools/ice-devtools/utils/inner-site.js
tools/ice-devtools/utils/npm.js
tools/ice-devtools/utils/token.js

- [feat] 移除 materialConfig.type 的兼容逻辑，统一生成 `materials.json`
- [fix] getNpmTime 出错直接终止命令
- [fix] sync 命令异常处理不恰当，无法获取错误堆栈以及退出状态码不符合标准

ice-devtools/2.2.5

---

tools/iceworks/package.json

see: https://github.com/alibaba/ice/issues/1680

[Iceworks] electron 升级到稳定版本

---

tools/iceworks/app/main/shared.js

[iceworks]remove miniapp material

---

tools/iceworks/renderer/src/pages/Blocks/index.jsx

[iceworks]hidden iceland module

---

tools/iceworks/renderer/package.json
tools/iceworks/renderer/src/pages/Home/ProjectPanel/AddPackage.jsx

* 添加依赖进行版本对比，主要解决某些用户因为无意识升级了大版本导致 API 变化引起的各类问题

feat: contrast version when adding dependencies

---

tools/iceworks/renderer/src/App.jsx

fix: https://github.com/alibaba/ice/issues/1671

fix: materials data error

---

tools/ice-scripts/lib/build.js
tools/ice-scripts/lib/component/build.js
tools/ice-scripts/lib/component/buildDemo.js
tools/ice-scripts/lib/component/generateEntryJs.js
tools/ice-scripts/lib/config/getBuildConfig.js
tools/ice-scripts/lib/config/paths.js
tools/ice-scripts/lib/dev.js

- 内置区块开发的 buildConfig
- 抽象 getBuildConfig 逻辑

[ice-scripts] inner block config

---

packages/iceworks-client/.eslintrc
packages/iceworks-client/.webpackrc.js
packages/iceworks-client/src/components/Aside/index.js
packages/iceworks-client/src/components/RouteRender/index.js
packages/iceworks-client/src/index.js
packages/iceworks-client/src/layouts/MainLayout.js
packages/iceworks-client/src/pages/Dev/index.js
packages/iceworks-client/src/pages/Material/index.js
packages/iceworks-client/src/pages/Project/index.js
packages/iceworks-client/src/pages/Setting/index.js
packages/iceworks-client/src/pages/Work/index.js
packages/iceworks-server/procfile.js

chore: refactor code

---

docs/pro/router.md

/noraml 更改为  /normal
NoramlLayout 更改为 NormalLayout

chore: 修改 docs/pro/router.md中的错误

---

packages/iceworks-client/.webpackrc.js
packages/iceworks-client/package.json
packages/iceworks-client/src/index.js
packages/iceworks-client/src/utils/logger.js

```javascript
import log from '@utils/logger';
const logger = log.getLogger('moduleName');
logger.debug(msg);
logger.info(msg);
logger.warn(msg);
logger.error(new Error(msg));
```

[iceworks][3.x] 前端日志

---

tools/ice-scripts/lib/config/getBuildConfig.js

- 区块/组件 build 的时候指定 publicPath 为 `./`

[ice-scripts] fix build public path

---

tools/ice-devtools/lib/generate.js
tools/ice-devtools/lib/sync.js
tools/ice-devtools/utils/generate-marterials-database.js

捕获 generate 命令和 sync 命令的异常，并手动退出。

fix: catch error and exit with code 1

---

packages/iceworks-client/src/components/Card/index.js
packages/iceworks-client/src/pages/Dev/index.js
packages/iceworks-client/src/pages/Work/index.js
packages/iceworks-client/src/pages/Work/index.module.scss

[iceworks]add card component

---

tools/ice-scripts/lib/config/getCertificate.js

[ice-scripts] fix: create ICE_CA folder if not exists

---

tools/iceworks/renderer/src/datacenter/materials.js
tools/iceworks/renderer/src/stores/materials.js

https://github.com/alibaba/ice/issues/1873

fix: 兼容物料源为空的场景

---

tools/iceworks/renderer/src/pages/Home/ProjectDashboard/Assets.jsx

fix issue: https://github.com/alibaba/ice/issues/1808
白屏错误原因：
1. 使用了未定义的 logger 对象
2. 代码判断逻辑错误 & 兼容

[iceworks]compatibility code

---

docs/guide/resource/tools.md

- 常用工具推荐文档 https://github.com/alibaba/ice/blob/09b3badfb3a0784bdfd821becddfa53dd0724505/docs/guide/resource/tools.md

chore: recommend tools

---

packages/iceworks-client/src/components/DynamicForm/index.js
packages/iceworks-client/src/components/DynamicForm/index.module.scss
packages/iceworks-client/src/menuConfig.js
packages/iceworks-client/src/pages/Configuration/index.js
packages/iceworks-client/src/pages/Configuration/stores/configuration.js
packages/iceworks-client/src/pages/Configuration/stores/index.js
packages/iceworks-client/src/routerConfig.js
packages/iceworks-server/src/app/io/controller/project/configuration.ts
packages/iceworks-server/src/app/router.ts
packages/iceworks-server/src/interface/project.ts
packages/iceworks-server/src/lib/adapter/config/configurationSettings.ts
packages/iceworks-server/src/lib/adapter/config/index.ts
packages/iceworks-server/src/lib/adapter/project.ts
packages/iceworks-server/src/lib/service/configuration.ts

[iceworks]Feat project interface

---

docs/guide/backend/java.md
docs/guide/backend/nodejs.md
docs/guide/backend/static.md

增加Java 集成、Node.js 集成、HTML 托管服务集成文档

docs: 更新后端集成文档

---

tools/ice-devtools/package.json
tools/ice-devtools/utils/download.js

Upgrade tar to latest version.

chore: upgrade tar to latest version

---

README.md

fix: website url

---

packages/iceworks-server/src/app/router.ts

- Normalizing error information;
- Record the error of the controller.
To know socket.io packet encode logic, see [Encoder.prototype.encode](https://github.com/socketio/socket.io-parser/blob/master/index.js#L170).

feat: handle controller error

---

packages/iceworks-server/src/interface/base.ts
packages/iceworks-server/src/lib/plugin/project-manager/app.ts

I don't have a better name for Project's `package.json` data, Now I call it "packageJSON".

feat: project package.json data for Adapter

---

tools/ice-scripts/lib/core/Service.js

```js
// ice.config.js
module.exports = {
entry: 'src/index.js',
chainWebpack: (config, { command, commandArgs }) => {
}
}
```

[ice-scripts] add options to chainWebpack 

---

packages/iceworks-client/src/pages/Build/index.js
packages/iceworks-server/src/app/io/controller/project/build.ts
packages/iceworks-server/src/app/io/controller/project/dev.ts
packages/iceworks-server/src/app/router.ts
packages/iceworks-server/src/lib/adapter/build/index.ts
packages/iceworks-server/src/lib/adapter/index.ts

[iceworks]feat: run build task

---

tools/ice-scripts/package.json

camelcase is required in file /lib/utils/cliInstance.js

fix: add camelcase dep

---

docs/cli/en-us/about.md
docs/cli/en-us/basic/start.md
package.json
scripts/docConfig.js
scripts/generate-docs-database.js
scripts/upload-oss.js

feat: rework docs generate for different versions&locales

---

tools/ice-devtools/CHANGELOG.md
tools/ice-devtools/lib/component/add.js
tools/ice-devtools/package.json
tools/ice-devtools/template/component/adaptor/index.js

[ice-devtools] release-2.3.2

---

packages/iceworks-client/src/pages/Project/components/SubMenu/index.js
packages/iceworks-client/src/pages/Project/index.js

* fix warning
* using `task` instead of `dev`

[iceworks]fix project panel

---

packages/ice-npm-utils/.gitignore
packages/ice-npm-utils/README.md
packages/ice-npm-utils/lib/index.js
packages/ice-npm-utils/package.json
packages/ice-npm-utils/test/index.test.js

- getNpmTarball
- getAndExtractTarball
Iceworks-cli/ iceworks-server / iceworks-app use these function.

feat: get and extract tarball

---

tools/iceworks/app/main/glodlog.js
tools/iceworks/app/main/services/worker/generate-project.js
tools/iceworks/app/package.json

fix: https://github.com/alibaba/ice/issues/2060

fix: generate abc.json consider ice-scripts@2.x

---

tools/iceworks/app/main/template/createProject.js

https://github.com/alibaba/ice/issues/2041

fix: no reset the template version

---

packages/iceworks-client/src/components/ConnectBar/index.js
packages/iceworks-client/src/components/ConnectBar/index.module.scss
packages/iceworks-client/src/layouts/MainLayout/index.js
packages/iceworks-client/src/socket.js

[iceworks]feat connect bar

---

tools/iceworks/app/main/template/createProject.js
tools/iceworks/app/package.json

[iceworks] remove unnecessary dependencies

---

tools/ice-scripts/bin/ice-scripts-build.js
tools/ice-scripts/bin/ice-scripts-dev.js
tools/ice-scripts/lib/commands/build.js
tools/ice-scripts/lib/config/postcssConfig.js
tools/ice-scripts/lib/core/Context.js

[ice-scripts] fix console error

---

packages/iceworks-client/src/components/ConnectModal/index.js
packages/iceworks-client/src/layouts/MainLayout/index.js
packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/socket.js
packages/iceworks-server/src/app/io/controller/home/system.ts
packages/iceworks-server/src/app/router.ts

* socket 断开重试机制优化 https://github.com/alibaba/ice/issues/2183

[iceworks] refactor socket logic

---

packages/iceworks-client/ice.config.js
packages/iceworks-client/src/components/BlockCard/index.module.scss
packages/iceworks-client/src/components/ComponentCard/index.module.scss
packages/iceworks-client/src/components/MaterialCategories/index.module.scss
packages/iceworks-client/src/components/ScaffoldCard/index.js
packages/iceworks-client/src/components/ScaffoldCard/index.module.scss

https://github.com/alibaba/ice/issues/2200

feat: support dark theme in material page

---

packages/iceworks-client/package.json
packages/iceworks-client/src/components/MaterialCategories/index.js
packages/iceworks-client/src/components/MaterialCategories/index.module.scss
packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/pages/Material/components/BlockPanel/index.js
packages/iceworks-client/src/pages/Material/components/ComponentPanel/index.js
packages/iceworks-client/src/pages/Material/components/ScaffoldPanel/index.js
packages/iceworks-client/src/pages/Material/index.js
packages/iceworks-client/src/stores/material.js
packages/iceworks-server/src/app/io/controller/material/index.ts
packages/iceworks-server/src/app/router.ts

1. 物料分类统一在服务端进行声明；
2. 分类切换使用状态进行管理。

refactor: material category

---

packages/iceworks-client/package.json
packages/iceworks-client/src/components/GlobalBar/index.js
packages/iceworks-client/src/components/XtermTerminal/index.js
packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/pages/Task/index.js
packages/iceworks-client/src/utils/termManager.js

* 将全局的终端改为日志输出
* 封装通用的 writeLog 方法
* 方法名 foramtWrite 优化伟 writeChunk
https://github.com/alibaba/ice/issues/2195

[iceworks] feat: write log to global

---

packages/iceworks-client/src/pages/Project/index.js

fix: sort panel

---

tools/ice-scripts/bin/child-process-dev.js
tools/ice-scripts/bin/ice-scripts-build.js
tools/ice-scripts/lib/core/Context.js

support custom config file via --config #2188

feat: support --config to use custom config

---

tools/ice-scripts/lib/plugins/userConfig/configs/hash.js
tools/ice-scripts/lib/plugins/userConfig/configs/outputAssetsPath.js
tools/ice-scripts/lib/plugins/userConfig/utils/formatWinPath.js

fix: formate windows output path

---

packages/iceworks-client/src/components/Icon/index.js
packages/iceworks-client/src/components/MenuTreeConfig/index.js
packages/iceworks-client/src/components/SelectWorkFolderModal/index.js
packages/iceworks-client/src/pages/Material/components/SubMenu/index.js
packages/iceworks-client/src/pages/Project/components/Guide/index.js
packages/iceworks-client/src/pages/Project/components/MenuPanel/index.js
packages/iceworks-client/src/pages/Project/components/RouterPanel/index.js
packages/iceworks-client/src/pages/Project/components/SubMenu/index.js
packages/iceworks-client/src/pages/Project/panels.js

- icon [ref](2224)
- 增加导航、路由面板透出

[优化] Icon 优化

---

packages/iceworks-client/src/pages/Task/index.js

[iceworks] fix: task setting

---

packages/iceworks-client/src/components/Locale/index.js
packages/iceworks-client/src/index.js
packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/pages/Setting/components/General/index.js

#2228 
修复问题
1. 修复国家化按钮文本
2. 修复初始化抖动问题
3. 修复todo面板名称

fix: fix theme init bug & locale

---

packages/iceworks-client/src/components/TipIcon/index.js
packages/iceworks-client/src/components/TipIcon/index.module.scss
packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/pages/Project/components/DependencyPanel/index.js
packages/iceworks-client/src/pages/Project/components/GitPanel/index.js
packages/iceworks-client/src/pages/Project/components/LayoutPanel/index.js
packages/iceworks-client/src/pages/Project/components/LayoutPanel/index.module.scss
packages/iceworks-client/src/pages/Project/components/MenuPanel/index.js
packages/iceworks-client/src/pages/Project/components/MenuPanel/index.module.scss
packages/iceworks-client/src/pages/Project/components/OSSPanel/index.js
packages/iceworks-client/src/pages/Project/components/PagePanel/index.js
packages/iceworks-client/src/pages/Project/components/RouterPanel/CreateRouterModal.js
packages/iceworks-client/src/pages/Project/components/RouterPanel/index.js
packages/iceworks-client/src/pages/Project/components/RouterPanel/index.module.scss
packages/iceworks-client/src/pages/Project/components/TodoPanel/index.js

feature: panel icons add tooltip/add refresh for layout

---

packages/iceworks-server/src/lib/adapter/index.ts
packages/iceworks-server/src/lib/plugin/i18n/app.ts
packages/iceworks-server/src/lib/plugin/project-manager/app.ts

配置字段统一改成与前端对应，修复前面OSS，DEF面板丢失问题

Fix: fix module name

---

tools/iceworks/app/main/scaffolder/lib/utils.js
tools/iceworks/app/main/template/createProject.js

fix: log download block error

---

packages/iceworks-client/src/pages/Project/components/TodoPanel/index.module.scss

Fix: fix todo icon

---

packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/pages/Project/components/GitPanel/Main.js
packages/iceworks-client/src/pages/Project/components/GitPanel/index.js
packages/iceworks-client/src/pages/Project/stores/git.js
packages/iceworks-server/src/interface/git.ts
packages/iceworks-server/src/lib/adapter/modules/git/index.ts

- 初始项目时终端控制台出现 git 相关错误
- git 修改仓库地址后，再次修改状态没有刷新
- git 点击切换分支无反应，服务端报错
- git 提交成功需给出提示，以及无文件时的提示

fix: Git 面板相关 Bug

---

packages/iceworks-client/src/hooks/useMaterial.js
packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/pages/Material/components/AddMaterialModal/index.js
packages/iceworks-client/src/pages/Material/components/DeleteMaterialModal/index.js
packages/iceworks-client/src/pages/Material/components/DeleteMaterialModal/index.module.scss
packages/iceworks-client/src/pages/Material/index.js

- add some tips
- confirm before delete material

fix: material page bugfix

---

package.json

fix eslint error

---

packages/iceworks-client/src/components/DynamicForm/index.js
packages/iceworks-server/src/lib/adapter/utils/cliConf.ts

https://github.com/alibaba/ice/pull/2309

fix: ast parse error

---

packages/iceworks-client/src/pages/Material/index.js

https://github.com/alibaba/ice/issues/2228#issuecomment-504271118

fix: larger tab size

---

packages/iceworks-client/ice.config.js
packages/iceworks-client/src/components/TipIcon/index.js
packages/iceworks-client/src/components/TipIcon/index.module.scss
packages/iceworks-client/src/pages/Project/components/Panel/head.js
packages/iceworks-client/src/pages/Project/components/Panel/head.module.scss

Optimize tip icon

---

packages/iceworks-server/src/interface/base.ts
packages/iceworks-server/src/lib/adapter-vue-v1/modules/configuration/index.ts
packages/iceworks-server/src/lib/adapter-vue-v1/modules/task/getTaskConfig.ts
packages/iceworks-server/src/lib/adapter-vue-v1/modules/task/index.ts

Fix vue adapter

---

packages/iceworks-client/src/components/XtermTerminal/index.js

[iceworks] clear log error

---

packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/pages/Engineering/components/Configuration/index.js
packages/iceworks-client/src/pages/Project/components/GuidePanel/index.js
packages/iceworks-client/src/pages/Project/components/OSSPanel/index.js
packages/iceworks-client/src/pages/Project/components/QuickStart/index.js
packages/iceworks-client/src/pages/Project/components/RouterPanel/index.js
packages/iceworks-client/src/pages/Project/components/SettingPanel/index.js

fix: fix i18n setting

---

packages/iceworks-client/src/pages/Engineering/components/Configuration/index.js
packages/iceworks-client/src/pages/Engineering/components/Task/index.js

fix: engineering configuration write failed

---

packages/iceworks-client/src/pages/Project/components/GitPanel/SwtichBranchModal.js
packages/iceworks-client/src/pages/Project/components/GitPanel/index.js
packages/iceworks-client/src/pages/Project/stores/git.js
packages/iceworks-server/src/lib/adapter/modules/git/index.ts

fix: fix git panel bug

---

packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/pages/Project/index.js
packages/iceworks-client/src/pages/Project/index.module.scss
packages/iceworks-client/src/stores/project.js
packages/iceworks-server/src/app/io/controller/home/project.ts
packages/iceworks-server/src/app/router.ts
packages/iceworks-server/src/lib/plugin/project-manager/app.ts

*  在代码添加 Adapter 时，iceworks 支持重新更新 Adapter 数据
* 添加 Adapter 适配文档地址
* 兼容 Adapter 不匹配的情况

[iceworks] reload adapter support

---

packages/iceworks-client/src/components/NavigationBar/index.module.scss
packages/iceworks-client/src/pages/Material/index.js

chore: adjust style

---

packages/iceworks-server/src/lib/adapter/index.ts
packages/iceworks-server/tsconfig.json

fix: fix adapter locales

---

packages/iceworks-client/src/pages/Project/components/SubMenu/index.module.scss
packages/iceworks-server/src/lib/scanDirectory.ts

fix: project style && file name

---

packages/iceworks-client/package.json
packages/iceworks-server/package.json
packages/iceworks-server/src/lib/adapter/locales/en-US.json
packages/iceworks-server/src/lib/adapter/locales/zh-CN.json
packages/iceworks-server/src/lib/adapter/modules/task/index.ts
tools/iceworks-cli/package.json

需求列表：https://github.com/alibaba/ice/issues/2369#issuecomment-509886551

[iceworks] release-3.0.0-beta.3

---

tools/iceworks-cli/command/start.js

详见 https://github.com/alibaba/ice/issues/2402  问题二

fix: spinner start

---

tools/iceworks-cli/command/start.js
tools/iceworks-cli/package.json

feat: opens the URL in the default browser

---

scripts/upload-oss.js

This reverts commit dd11425033213fa9f4d21652cd95f1b1f5816b63.

Revert "feat: upload assets to oss"

---

packages/iceworks-server/src/lib/adapter-react-v2/index.ts
packages/iceworks-server/src/lib/adapter-vue-v1/index.ts

修复从baseAdapter中import出的module与自定义module重名

fix: adapter local variable conflict

---

packages/iceworks-client/src/pages/Material/components/AddMaterialModal/index.module.scss
packages/iceworks-client/src/pages/Project/components/DependencyPanel/CreateDependencyModal.js
packages/iceworks-client/src/pages/Project/components/PagePanel/BuildPageModal.js
packages/iceworks-client/src/pages/Project/components/PagePanel/SavePageModal.js
packages/iceworks-server/src/lib/adapter/locales/en-US.json
packages/iceworks-server/src/lib/adapter/locales/zh-CN.json
packages/iceworks-server/src/lib/adapter/modules/page/index.ts
packages/iceworks-server/src/lib/plugin/project-manager/app.ts

- 添加依赖时未指定版本，安装失败； https://github.com/alibaba/ice/issues/2447
- 从 iceworks 中删除项目后 db.json 里的 panelSettings 内容还存在；
- 下载物料失败透出 URL 地址；
- 添加物料的 Dialog 太小，需优化；

fix: P2 bugs

---

packages/iceworks-server/src/app/router.ts

* 需求说明： https://github.com/alibaba/ice/issues/2475

feat: add log

---

packages/iceworks-client/src/components/GlobalBar/index.js

fix: update theme text

---

packages/iceworks-server/src/app/io/controller/material/index.ts
packages/iceworks-server/src/lib/storage.ts

[Iceworks]bug: fix vue materials don't appear in material panel

---

packages/iceworks-server/package.json
packages/iceworks-server/src/app/io/controller/home/project.ts
packages/iceworks-server/src/app/io/controller/home/setting.ts
packages/iceworks-server/src/lib/adapter/modules/task/index.ts
packages/iceworks-server/src/lib/plugin/project-manager/app.ts

- Use shell path for env;
- Use Logger for ProjectManager.

refactor: use shell path for env

---

packages/iceworks-client/src/pages/Material/components/MaterialPanel/index.js
packages/iceworks-client/src/pages/Material/components/MaterialPanel/index.module.scss
packages/iceworks-client/src/pages/Material/index.js

[Iceworks]feat: add material page loading

---

packages/iceworks-client/src/pages/Project/components/QuickBuildPanel/index.js

[iceworks 3.0] Fix typo in QuickBuildPanel

---

packages/ice-npm-utils/.npmrc
packages/ice-npm-utils/CHANGELOG.md
packages/ice-npm-utils/README.md
packages/ice-npm-utils/lib/index.js
packages/ice-npm-utils/package.json
packages/ice-npm-utils/test/index.test.js

[ice-npm-utils] release 1.2.0

---

tools/iceworks-app/app/error.css
tools/iceworks-app/app/error.html
tools/iceworks-app/app/error.js
tools/iceworks-app/app/index.js

- refactor: Better logs;
- feature: Error page display logs;
- fix: window can't close.

feat: iceworks electron

---

docs/guide/about.md

* 前端基础知识 路径改到资源底下，文档中对应的路由要相应变化

fix: doc path

---

tools/iceworks/app/main/autoUpdater.js
tools/iceworks/app/package.json
tools/iceworks/renderer/src/Layout/Layout.jsx
tools/iceworks/renderer/src/Layout/Layout.scss

[iceworks] release-2.23.0

---

CHANGELOG.md
packages/iceworks-client/package.json
packages/iceworks-client/src/pages/Material/components/MaterialPanel/index.js
packages/iceworks-client/src/pages/Material/components/MaterialPanel/index.module.scss
packages/iceworks-server/package.json
tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/command/start.js
tools/iceworks-cli/package.json

- [fix] adjust material panel style https://github.com/alibaba/ice/pull/2524

[iceworks] release-3.0.0-beta.10

---

tools/iceworks-app/app/autoUpdate.js
tools/iceworks-app/app/index.js
tools/iceworks-app/renderer/src/pages/About/index.jsx
tools/iceworks-app/renderer/src/pages/About/index.scss
tools/iceworks-app/renderer/src/pages/Updater/index.jsx
tools/iceworks-app/renderer/src/pages/Updater/index.scss

- fix: upgrade logic;
- feature: more menus.

Upgrade logic and more menus

---

packages/iceworks-client/src/pages/Project/components/QuickStart/index.module.scss
packages/iceworks-server/src/app/io/controller/material/index.ts

* issue：https://github.com/alibaba/ice/issues/2556
>  注释：模板数据存在问题导致预览图片不存在，虚左在数据层面根据

fix: show recommend scaffold

---

CHANGELOG.md
packages/iceworks-client/package.json
packages/iceworks-client/src/pages/Project/components/PagePanel/BuildPageModal.js
packages/iceworks-client/src/pages/Project/components/PagePanel/SavePageModal.js
packages/iceworks-client/src/pages/Project/components/QuickStart/index.module.scss
packages/iceworks-server/package.json
packages/iceworks-server/src/app/io/controller/material/index.ts
packages/iceworks-server/src/lib/adapter/modules/dependency/index.ts
packages/iceworks-server/src/lib/adapter/modules/router/index.ts
packages/iceworks-server/src/lib/remoteLogger/index.ts

- [fix] router sort logic #2559 
- [fix] failed to create page #2564 
- [fix] failed to re-install dependencies #2565 
- [fix] show recommend scaffold #2558

[iceworks] release-3.0.1

---

packages/iceworks-server/package.json

fix: copy ejs file to dist

---

README.en-US.md
README.md
docs/guide/about.md
docs/guide/backend/java.md
scripts/docConfig.js

fix: 修复 icestark doc 链接
fix: 删除前后端通信 java 中多余代码

Fix doc bug

---

packages/iceworks-client/src/components/SelectWorkFolderModal/index.js
packages/iceworks-client/src/components/SelectWorkFolderModal/index.module.scss
packages/iceworks-server/src/app/io/controller/home/setting.ts
packages/iceworks-server/src/app/router.ts
packages/iceworks-server/src/lib/scanDirectory.ts
packages/iceworks-server/src/locales/en-US.json
packages/iceworks-server/src/locales/zh-CN.json

Unable to access system root directory on Windows, so we provide input to set working path. Related issue: https://github.com/alibaba/ice/issues/2600.

feat: user can set working path by inputting

---

packages/iceworks-server/src/lib/plugin/project-manager/app.ts

Fix iceworks-server unable to start if project directory is not present in local environment

---

docs/guide/dev/ajax.md

修复 useRequest 文档 bug，具体参考 pro 模板 [PR](https://github.com/ice-lab/react-materials/pull/108)

fix: ajax doc

---

packages/iceworks-server/src/lib/plugin/project-manager/app.ts

Refactor code for project-manager/app.ts

---

packages/iceworks-client/src/components/CreateProjectModal/index.js
packages/iceworks-client/src/hooks/useProject.js
packages/iceworks-client/src/pages/Material/index.js
packages/iceworks-client/src/pages/Project/components/PagePanel/SavePageModal.js
packages/iceworks-server/src/lib/plugin/project-manager/app.ts

- 修复使用小二工作台模板，不能正常跳转回项目的问题
- 填写页面信息，如果路由分组包含/，则默认选上/

fix：修复小二工作台相关体验问题

---

packages/iceworks-server/package.json
packages/iceworks-server/src/app/controller/goldlog.ts
packages/iceworks-server/src/app/io/controller/material/index.ts
packages/iceworks-server/src/app/router.ts
packages/iceworks-server/src/config/config.default.ts
packages/iceworks-server/src/lib/remoteLogger/index.ts

https://github.com/alibaba/ice/issues/2603
Some uncovered errors cause processes to crash and socket to disconnect and reconnect:
1. ETIMEDOUT ERROR
Request error are not captured and cause the process to crash. The common request error is timeout.
2. EPIPE ERROR
For this case, data stream from read stream(request from remote) to write stream(write into local file), in some cases (timeout) read stream are closed and write failures are triggered. That's just my guess, because when I delete [this line of code](https://github.com/alibaba/ice/blob/958f424b345e6cc496bfaa6803277746eb5de58e/packages/iceworks-server/src/app/router.ts#L55), the error disappears.

fix: socket disconnect

---

packages/iceworks-client/ice.config.js
packages/iceworks-client/src/components/GlobalBar/index.js
packages/iceworks-client/src/components/GlobalBar/index.module.scss
packages/iceworks-client/src/utils/writeGlobalLog.js

当globalOperationLog还没实例化时，启动调试，会报错

fix: fail-to-run-dev-task

---

CHANGELOG.md
packages/iceworks-client/ice.config.js
packages/iceworks-client/package.json
packages/iceworks-client/src/components/GlobalBar/index.js
packages/iceworks-client/src/components/GlobalBar/index.module.scss
packages/iceworks-client/src/components/XtermTerminal/index.js
packages/iceworks-client/src/utils/writeGlobalLog.js
packages/iceworks-server/package.json

[iceworks] release 3.0.4

---

docs/guide/start.md
docs/materials/reference/env.md

* 修复 idev 文档的拼写问题
* 更新 iceworks 的快速开始文档到 3.0

docs: fix typo

---

packages/iceworks-client/jsconfig.json
packages/iceworks-client/src/components/ScaffoldCard/index.js

fix: 兼容物料数据里 screentshots 字段不存在的情况

---

packages/iceworks-server/package.json
packages/iceworks-server/src/lib/adapter/modules/page/index.ts

https://github.com/alibaba/ice/issues/2630
using the same logic to handle page name.

fix: page name

---

packages/iceworks-server/src/lib/adapter/modules/task/index.ts

* issue：https://github.com/alibaba/ice/issues/2608
*  https://www.infoq.cn/article/nodejs-about-buffer
* 目前 webpack 的流数据是通过 webpack ProgressPlugin 解决的，已经处理了流数据不需要在额外的处理  https://github.com/ice-lab/ice-scripts/pull/22/files#diff-a8ecc94d4d739b114c79101076479eeaR34

[iceworks] fix encode error for log

---

tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/lib/downloadServer.js
tools/iceworks-cli/package.json

[iceworks-cli] release 3.0.3

---

packages/iceworks-client/src/components/TaskBar/index.js
packages/iceworks-client/src/hooks/useTask.js
packages/iceworks-client/src/locales/en-US/index.js
packages/iceworks-client/src/locales/zh-CN/index.js
packages/iceworks-client/src/pages/Engineering/components/Task/index.js

* 需求：https://github.com/alibaba/ice/issues/2610

[iceworks]: feat add install dependence to task

---

packages/iceworks-server/src/lib/adapter/modules/page/index.ts

https://github.com/alibaba/ice/issues/2673#issuecomment-521091462

fix: move block

---

packages/iceworks-client/ice.config.js
packages/iceworks-client/package.json

https://github.com/alibaba/ice/issues/2522

feat: set progress color for dark

---

packages/iceworks-server/src/app/middleware/client.ts

* 支持从 unpkg 获取对应的 client 静态资源，用户回退版本，关联 MR ：https://github.com/alibaba/ice/pull/2695

[iceworks] support unpkg assets

---

packages/iceworks-server/src/lib/adapter/modules/dependency/index.ts
packages/iceworks-server/src/lib/plugin/project-manager/app.ts

* fix issue：https://github.com/alibaba/ice/issues/2607

[iceworks] fix cnpm client

---

packages/iceworks-client/src/components/SelectWorkFolderModal/index.js
packages/iceworks-client/src/hooks/useProject.js
packages/iceworks-client/src/pages/Project/index.js

https://github.com/alibaba/ice/issues/2606
Two projects occurred because the request to open project triggered two times.

feat: add loading for open project

---

packages/iceworks-server/src/app/io/controller/home/setting.ts
packages/iceworks-server/src/lib/adapter/modules/layout/index.ts
packages/iceworks-server/src/lib/scanDirectory.ts

https://github.com/alibaba/ice/issues/2670

fix: allow select empty folders as work folder

---

tools/iceworks-cli/bin/iceworks.js
tools/iceworks-cli/command/start.js
tools/iceworks-cli/lib/downloadServer.js
tools/iceworks-cli/package.json

* 增加降级逻辑，可以通过以下命令指定 iceworks 的版本进行使用，详见 https://github.com/alibaba/ice/issues/2693
* 关联 MR：https://github.com/alibaba/ice/pull/2696
```bash
$ iceworks use <version>
```

[iceworks-cli] add backup logic

---

packages/iceworks-server/src/lib/adapter/modules/page/index.ts
packages/iceworks-server/src/lib/scanDirectory.ts

https://github.com/alibaba/ice/issues/2705

fix:  block dependencies need to be installed at the same time when adding blocks

---

tools/iceworks-cli/bin/iceworks.js
tools/iceworks-cli/command/start.js

issue: https://github.com/alibaba/ice/issues/2690

[iceworks-cli] add changelog url

---

docs/iceworks/Installation.md

多次有用户反馈如下问题，为了减少不必要的问题因此将文档进行修改

docs: fix iceworks installation

---

tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/bin/iceworks.js
tools/iceworks-cli/command/start.js
tools/iceworks-cli/lib/downloadServer.js
tools/iceworks-cli/package.json

[iceworks-cli] release 3.0.4

---

scripts/docConfig.js

feat: icestore docConfig

---

packages/iceworks-server/src/lib/adapter-vue-v2/modules/page/template.vue.ejs

[Iceworks]fix: register vue component

---

tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/package.json

fix: update engines version

---

packages/iceworks-server/src/lib/adapter/modules/page/index.ts

- Catch add blocks error and remove page dir when add blocks got error;
- Asynchronous operations need to create multiple different temporary directories.

fix: create page

---

packages/iceworks-server/src/interface/base.ts
packages/iceworks-server/src/lib/adapter-react-v2/modules/menu/index.ts
packages/iceworks-server/src/lib/adapter-react-v2/modules/router/index.ts
packages/iceworks-server/src/lib/adapter/modules/menu/index.ts
packages/iceworks-server/src/lib/adapter/modules/router/index.ts
packages/iceworks-server/src/lib/plugin/project-manager/app.ts

- issue: https://github.com/alibaba/ice/issues/2741
- How to: 
- Determine the programming language used by the project through feature checking;
- Route and Menu configuration files use the programming language suffix of the project.

fix: delete router and menu

---

docs/iceworks/migrate.md

docs: add vue migrate docs

---

tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/bin/iceworks.js
tools/iceworks-cli/command/start.js
tools/iceworks-cli/lib/downloadServer.js
tools/iceworks-cli/package.json

* 将 iceworks-core 代码下载到 userHome 目录下，解决用户安装权限问题

iceworks cli/release 3.0.7

---

packages/ice-chart-material-template/package.json
packages/ice-chart-material-template/template/component/gui.schema.js
packages/ice-chart-material-template/template/component/package.json.ejs

1. 增加 .idea gitignore, 适应 webstorm 开发环境
2. 增加 gui.schema.js 用于完善可视化搭建物料的表单 schema 生成
3. package.json 修改 schema 的命令增加 schema 监听修改
4. package.json 修改构建命令顺序，防止 README.md 未生成前被打包

fix: 完善 chart template 编辑流程

---

package.json
tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/command/add/index.js
tools/iceworks-cli/command/generate/index.js
tools/iceworks-cli/command/start/downloadServer.js
tools/iceworks-cli/command/sync/index.js
tools/iceworks-cli/lib/config.js
tools/iceworks-cli/package.json

- 修复第一次写入 config 出错问题
- 增加埋点
- 修复 egg-scripts 不存在问题

[iceworks-cli] release 3.1.1

---

docs/cli/plugin-list/fusion.md

docs: example for custom font path

---

packages/ice-chart-material-template/package.json
packages/ice-chart-material-template/template/component/package.json.ejs

fix: 修复package.json中files缺少的文件

---

packages/ice-react-material-template/package.json
packages/ice-react-material-template/template/block/_package.json
packages/ice-react-ts-material-template/package.json
packages/ice-react-ts-material-template/template/block/_package.json
packages/ice-screenshot/CHANGELOG.md
packages/ice-screenshot/bin/index.js
packages/ice-screenshot/package.json
packages/ice-screenshot/utils/getPuppeteer.js
packages/ice-vue-material-template/package.json
packages/ice-vue-material-template/template/block/_package.json

- 同步 screenshot 最新代码，直接迁移的时候丢失了，主要是 timeout 改动
- 修复 block 在 windows 下截图失败问题：Close https://github.com/alibaba/ice/issues/2641

fix: block screenshot error

---

tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/command/start/downloadServer.js
tools/iceworks-cli/command/start/index.js
tools/iceworks-cli/package.json

```bash
$ npm i -g iceworks@beta --registry=https://registry.npm.taobao.org
```

show help message when iceworks start error

---

docs/guide/dev/ajax.md

fix: useRequest typo error

---

packages/ice-screenshot/CHANGELOG.md
packages/ice-screenshot/bin/index.js
packages/ice-screenshot/package.json

fix: consider -s undefined when format selector

---

docs/guide/dev/ajax.md

* 更新 useRequest 相关源码，与 pro 模板保持一致

feat: update useRequest source in ajax doc

---

README.en-US.md
README.md

docs: fix readme typo error

---

packages/ice-npm-utils/CHANGELOG.md
packages/ice-npm-utils/lib/index.js
packages/ice-npm-utils/package.json
packages/ice-npm-utils/test/index.test.js
tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/command/init/initMaterialAndComponent.js
tools/iceworks-cli/package.json

[iceworks-cli] release 3.1.8

---

packages/material-template-react-deep/template/component/demo/usage.md
packages/material-template-react-deep/template/component/ice.config.js
packages/material-template-react-deep/template/component/package.json.ejs
packages/material-template-react-deep/template/component/src/index.tsx.ejs
packages/material-template-react-deep/template/component/src/main.scss.ejs

deep template

---

packages/iceworks-server/package.json
packages/iceworks-server/src/lib/plugin/project-manager/app.ts

- Replace `shell-path` with `shell-env`, `shell-path` hasn't been updated for a long time;
- Make sure the `PATH` field is a string.

fix: shell path

---

README.en-US.md
README.md

图像看起来会被 Github 缓存，需要重新发布一下，另外加了外链。

docs: add link for QR Code

---

tools/iceworks-cli/command/init/addSingleMaterial.js

fix: just a spelling mistake

---

tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/command/init/addSingleMaterial.js
tools/iceworks-cli/package.json

[iceworks-cli] release 3.1.10

---

docs/guide-0.x/about.md
docs/guide/about.md

docs: fix url

---

tools/iceworks-cli/bin/iceworks.js
tools/iceworks-cli/package.json

- 执行 `iceworks` 时输出 `--help` 的信息
- 新增 `iceworks start` 命令启动 iceworks

refactor: remove iceworks server

---

docs/cli/config/config-file.md
docs/guide/basic/app.md
docs/guide/basic/router.md
docs/guide/migrate.md

- 路由配置补充 fallback 选项
- 补充完善的路由 API 文档
- 调整路由文档顺序

docs: adjust router docs

---

docs/guide/basic/store.md

- 补充 store 文档对应的完整示例 https://github.com/ice-lab/icejs/pull/81

docs: add example 

---

docs/guide/basic/router.md

https://github.com/ice-lab/icejs/blob/release-next/packages/plugin-router/src/index.ts#L20

docs: fix router configPath

---

packages/ice-npm-utils/CHANGELOG.md
packages/ice-npm-utils/package.json
packages/ice-npm-utils/src/__tests__/index.ts
packages/ice-npm-utils/src/index.ts
tools/iceworks-cli/CHANGELOG.md
tools/iceworks-cli/bin/iceworks.js
tools/iceworks-cli/command/init/initMaterialAndComponent.js
tools/iceworks-cli/command/sync/fusionSDK.js
tools/iceworks-cli/command/sync/index.js
tools/iceworks-cli/package.json
tools/iceworks-cli/template/initMaterial/_gitignore
tools/iceworks-cli/template/initMaterial/_package.json.ejs

- ice-npm-utils 去除 cache 逻辑，满足 server 类型的场景
- iceworks CLI 支持 sync --env 参数
- iceworks CLI sync 内外网判断逻辑优化
- 物料集合模板优化

chore: remove cacheData

---

docs/materials/guide/init.md

mkdir my-materials & cd my-materials缺少一个&

mkdir my-materials & cd my-materials缺少一个&

---

docs/guide/basic/router.md

docs: enhance docs

---

packages/plugin-react-app/package.json
packages/plugin-react-app/src/index.js
yarn.lock

fix: define webpackPluginImport in plugin-react-app

---

docs/guide/advance/error-boundaries.md
packages/plugin-core/src/generator/templates/app/types.ts.ejs

issue：https://github.com/alibaba/ice/issues/3218

fix: types

---

packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
packages/plugin-core/src/generator/templates/app/history.ts.ejs
packages/plugin-core/src/generator/templates/app/index.ts.ejs
packages/plugin-core/src/generator/templates/app/runtimeModule.tsx.ejs
packages/plugin-icestark/src/module.tsx
packages/plugin-icestark/src/runtime/_history.ts
packages/plugin-icestark/tsconfig.json

相关 issue：https://github.com/alibaba/ice/issues/3177

refactor: history api

---

docs/guide/basic/request.md
examples/basic-request/mock/index.js
examples/basic-request/src/app.ts
examples/basic-request/src/pages/Home/index.tsx
packages/plugin-request/request/axiosInstance.ts
packages/plugin-request/request/createAxiosInstance.ts
packages/plugin-request/request/request.ts
packages/plugin-request/src/_axiosInstance.ts
packages/plugin-request/src/_createAxiosInstance.ts
packages/plugin-request/src/index.ts
packages/plugin-request/src/module.ts
packages/plugin-request/src/types/index.ts
packages/plugin-request/tsconfig.json

- request 支持创建多实例和配置： https://github.com/alibaba/ice/issues/3170

feat: allow creating multi request instances

---

docs/guide/basic/request.md

文档
数据请求：
` effects: (dispatch) => {
async fetchUserInfo() {
const data = await userService.getUser();
dispatch.user.update(data);
}
}`
报错

docs: effects: (dispatch) => ()

---

examples/icestark-child/src/app.tsx
examples/icestark-layout/src/app.tsx
packages/plugin-icestark/src/module.tsx

fix: https://github.com/alibaba/ice/issues/3255

fix: icestark Suspense fallback

---

packages/plugin-store/src/generator.ts

https://github.com/alibaba/ice/issues/3241

fix: ignore dot file

---

packages/plugin-auth/src/module.tsx

issue: https://github.com/alibaba/ice/issues/3260

fix: authorized by default

---

docs/guide/basic/build.md
docs/guide/develop/plugin-list.md

docs: update build configs

---

docs/guide/develop/plugin-list.md

issue: https://github.com/alibaba/ice/issues/3175

docs: add build-jsx-plus-plugins

---

packages/icejs/src/index.ts
packages/plugin-mpa/package.json
packages/plugin-mpa/src/index.ts

issue: https://github.com/alibaba/ice/issues/3276

feat: compatibility index entry

---

docs/guide/migrate.md

- 从 ice-scripts#1.x 迁移到 ice.js

docs: from ice-scripts@1.x to icejs

---

docs/guide/advance/mpa.md
examples/basic-mpa/package.json
packages/plugin-mpa/src/index.ts
packages/plugin-react-app/src/userConfig/entry.js

issue：https://github.com/alibaba/ice/issues/3282

feat: support --mpa-entry

---

packages/plugin-core/src/utils/getRoutes.ts

fix: mpa router path error

---

examples/basic-auth/src/routes.ts
packages/plugin-auth/src/module.tsx

https://github.com/alibaba/ice/issues/3298
https://github.com/alibaba/ice/issues/3304

fix: auth error with lazy

---

docs/guide/basic/build.md
examples/basic-store/build.json
examples/basic-store/src/typings.d.ts
examples/basic-store/src/typings.d.ts 
packages/plugin-core/src/generator/templates/app/components/ErrorBoundary.tsx.ejs
packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
packages/plugin-core/src/generator/templates/app/history.ts.ejs
packages/plugin-core/src/generator/templates/app/types.ts.ejs
packages/plugin-react-app/package.json
packages/plugin-react-app/src/config/default.config.js
packages/plugin-react-app/src/config/validation.js
packages/plugin-react-app/src/index.js
packages/plugin-react-app/src/userConfig/tsChecker.js
packages/plugin-router/src/types/index.ts
yarn.lock

https://github.com/alibaba/ice/issues/3311

feat: support ts type chcker on a separate process

---

docs/guide/basic/build.md
packages/icejs/bin/ice-cli.js

[issue 3316](https://github.com/alibaba/ice/issues/3316)

chore: sync cli options with docs

---

packages/plugin-core/src/index.ts

[issue 3251 新增页面需要重新npm start (JS) ](https://github.com/alibaba/ice/issues/3251)

fix: file change not handled on windows

---

packages/plugin-store/src/generator.ts

https://github.com/alibaba/ice/issues/3328

fix: statement error

---

docs/iceworks/setup.md

Add download Iceworks zip document.

Feat docs add download zip

---

examples/basic-spa/jest.config.js
examples/basic-spa/src/__tests__/services.ts
examples/basic-spa/src/services/requests.ts
examples/basic-store/jest.config.js
examples/basic-store/package.json
examples/basic-store/src/models/title.ts
examples/basic-store/src/pages/Home/__tests__/index.tsx
examples/basic-store/src/pages/Home/index.tsx
packages/plugin-react-app/src/index.js
packages/plugin-router/src/index.ts

[Issue 单元测试](https://github.com/alibaba/ice/issues/3359)

fix: escape the beginning $ in jest moduleNameMapper

---

packages/create-app-shared/README.md
packages/create-app-shared/package.json
packages/create-app-shared/src/collectAppLifeCycle.js
packages/create-app-shared/src/createBaseApp.js
packages/create-app-shared/src/index.js
packages/create-app-shared/src/pageLifeCycles.js
packages/miniapp-renderer/package.json
packages/plugin-core/src/generator/templates/common/index.ts.ejs
packages/plugin-core/src/generator/templates/runApp.ts.ejs
packages/plugin-router/templates/react-router-dom.ts
packages/rax-renderer/README.md
packages/rax-renderer/package.json
packages/rax-renderer/src/raxRenderer.tsx

rax-app 2.x 改为直接依赖 @ice/create-app-shared 和 @ice/rax-renderer，避免维护多套代码。

chore: use middleground package instead of old logic

---

examples/basic-request/src/pages/Home/index.tsx
packages/plugin-request/template/useRequest.ts

[issue 3383](https://github.com/alibaba/ice/issues/3383)

fix: function as parameter in useRequest

---

examples/with-react-miniapp/build.json
packages/plugin-react-app/src/constants.js
packages/plugin-react-app/src/index.js
packages/plugin-react-app/src/utils/getMiniappOutputPath.js

feat: optimize build log

---

packages/plugin-app-core/src/generator/templates/common/types.ts.ejs

feat: add lifecycle types

---

docs/miniprogram/basic/engineering.md
docs/miniprogram/basic/structure.md
docs/miniprogram/basic/style.md

- 推荐使用 css module + less
- 添加一些常用的工程配置

docs: enhance miniapp docs

---

packages/create-app-shared/src/runtimeModule.ts
packages/plugin-app-core/package.json
packages/react-app-renderer/package.json

- 修复 history API
- 修复 createElement  透传 children 问题

fix: history api

---

examples/icestark-child/src/pages/index.tsx
packages/create-app-shared/package.json
packages/create-app-shared/src/history.ts
packages/create-app-shared/src/index.ts
packages/plugin-app-core/package.json
packages/plugin-app-core/src/generator/templates/common/runApp.ts.ejs
packages/react-app-renderer/package.json
packages/react-app-renderer/src/index.ts
packages/react-app-renderer/src/renderer.tsx

fix: export history instance with icestark

---

packages/plugin-app-core/src/config/setAlias.ts
packages/plugin-app-core/src/index.ts

[问题及复现步骤](https://github.com/alibaba/ice/pull/3422#issuecomment-671865879)

fix: duplicate dependency - react & react-dom

---

examples/with-rax-miniapp/src/app.json
packages/create-app-container/README.md
packages/create-app-container/package.json
packages/create-app-container/src/createAppNavigation.ts
packages/create-app-container/src/createTabBar.ts
packages/create-app-container/src/getSafeAreaInsetBottom.ts
packages/create-app-container/src/index.ts
packages/create-app-container/tsconfig.json
packages/rax-app-renderer/src/renderer.tsx
tsconfig.json

提供通用的 app 容器：
```ts
import { render, createElement, useEffect, useState, Fragment } from 'rax'; // or react
import  { createAppNavigation, createAppTabBar } from 'create-app-container';
const api = { createElement, useEffect, useState, Fragment };
const AppNavigation = createAppNavigation(api);
const AppTabBar = createAppTabBar(api);
```

feat: provides common app container

---

examples/with-react-miniapp-todos/package.json
examples/with-react-miniapp-todos/src/pages/add-todo/index.jsx
examples/with-react-miniapp-todos/src/pages/todos/index.jsx
examples/with-react-miniapp-todos/tsconfig.json

解决 `examples/with-react-miniapp-todos` 手机端无法获取用户头像及不能添加 todo的问题。

fix: todos miniapp getUserInfo

---

docs/guide/start.md
packages/create-ice/package.json
packages/create-ice/src/index.ts
yarn.lock

[Issue: create-ice 支持在当前目录创建项目 #3429](https://github.com/alibaba/ice/issues/3429)

feat: support init project in current dir

---

packages/plugin-app-core/src/utils/getSourceDir.ts

**相关 PR**: [Fix/src rename](https://github.com/alibaba/ice/pull/3422)
**examples 测试**

fix: getSourceDir compatibility

---

packages/plugin-app-core/src/utils/getSourceDir.ts

测试 `baisc-store` 在 `Windows` `Ubuntu` 均正常。

fix: getSourceDir not work on windows

---

packages/plugin-app-core/src/dev.ts

[原有 PR](https://github.com/alibaba/ice/pull/3327)

fix: windows file change not handled

---

packages/plugin-store/src/template/pageComponent.tsx.ejs

fix: types error

---

packages/plugin-react-app/src/userConfig/dll.js

[Issue: dll 构建失败](https://github.com/alibaba/ice/issues/3459)

fix: dll escape invalid char & log error

---

docs/iceworks/guide/application-view.md
docs/iceworks/guide/create-application.md
docs/iceworks/guide/material.md
docs/iceworks/guide/visual-construction.md

Feat: update screenshot

---

packages/create-app-shared/package.json
packages/create-app-shared/src/env.ts
packages/icejs/package.json
packages/plugin-app-core/package.json
packages/plugin-app-core/src/generator/templates/common/runApp.ts.ejs

- 解决小程序容器内嵌 h5 页面时误判为小程序应用的问题 https://github.com/alibaba/ice/issues/3441

fix: miniapp env

---

docs/guide/basic/build.md

docs: dll output

---

packages/plugin-app-core/src/index.ts
packages/plugin-react-app/src/base.js
packages/plugin-react-app/src/index.js
packages/plugin-react-app/src/userConfig/outputDir.js
packages/plugin-react-app/src/utils/getWebOutputPath.js

https://github.com/alibaba/ice/issues/3486
1. 不配置 targets 时即兼容逻辑，构建结构如下：
2. 配置 miniapp 、wechat-miniprogram
```json
"targets": ["miniapp", "wechat-miniprogram"]
```
3. 配置 web、miniapp、 wechat-miniprogram 
```json
"targets": ["web", "miniapp", "wechat-miniprogram"]
```

feat: build the asset path

---

docs/guide/basic/store.md

https://github.com/alibaba/ice/issues/3473

docs: update store guide

---

packages/plugin-antd/src/index.js

https://ant.design/docs/react/faq#How-to-spell-Ant-Design-correctly

fix: Antd typo

---

packages/create-cli-utils/src/create-cli.js
packages/icejs/src/index.ts

支持基于icejs扩展除start，build，test外的其它命令

feat: 扩展icejs cli,使之支持start,build,test外的其它命令

---

examples/basic-spa/mock/index.js
examples/basic-spa/mock/projects.js
packages/plugin-react-app/package.json
packages/webpack-dev-mock/README.md
packages/webpack-dev-mock/demo/mock/bar.js
packages/webpack-dev-mock/demo/mock/foo.json
packages/webpack-dev-mock/demo/mock/index.js
packages/webpack-dev-mock/demo/server.js
packages/webpack-dev-mock/package.json
packages/webpack-dev-mock/src/index.ts
packages/webpack-dev-mock/src/matchPath.ts
packages/webpack-dev-mock/tsconfig.json
tsconfig.json
yarn.lock

- Mock 引用文件出错控制台需要给出提示 Mock https://github.com/alibaba/ice/issues/3504

feat: webpack dev mock

---

packages/plugin-fusion/src/webpackPlugins/checkIceComponentsDepPlugin/index.js

chore: remove unless log

---

packages/plugin-react-app/src/index.js

MPA 模式下支持打开特定的 URL 页面 https://github.com/alibaba/ice/issues/3511
在 MPA 模式下默认启动 pages 下的第一个页面作为启动页
```diff
"scripts": {
+   "start": "icejs start",
"build": "icejs build"
},
```
```diff
"scripts": {
-   "start": "icejs start",
+   "start": "icejs start --mpa-entry Home",
"build": "icejs build"
},
```

feat: support to open the specify page in mpa mode

---

.eslintignore
packages/create-app-container/src/createNavigation.ts
packages/create-app-container/src/createTabBar.ts
packages/create-use-router/src/index.ts
packages/plugin-app-core/src/config/setAlias.ts
packages/plugin-app-core/src/generator/index.ts
packages/plugin-app-core/src/index.ts
packages/webpack-dev-mock/src/index.ts
yarn.lock

fix: eslint warnings

---

examples/with-rax/build.json
packages/plugin-rax-web/src/index.js
packages/plugin-ssr/src/index.ts
packages/plugin-ssr/src/ssr/getBase.js
packages/plugin-ssr/src/ssr/setDev.js

- 修复 SSR 静态资源加载问题
- 修复 SSR 执行环境问题

fix(rax-app): ssr public url

---

packages/plugin-app-base/src/base.js
packages/plugin-app-core/src/generator/templates/app/rax/ErrorBoundary/index.tsx.ejs
packages/plugin-app-core/src/generator/templates/app/rax/index.ts.ejs

feat: add friendly-errors-webpack-plugin

---

packages/plugin-app-base/package.json
packages/plugin-ssr/package.json

fix(rax-app): add deps in package.json

---

docs/guide/basic/logger.md
scripts/generate-docs-database.js

- 修复文档错误  https://github.com/ice-lab/icestark/issues/174 ，详见 [loglevel](https://github.com/pimterry/loglevel/blob/026fcf4b60f3374906efe08540879084bddfd080/lib/loglevel.js#L184) 配置

fix: logger docs

---

packages/plugin-ssr/src/index.ts

fix: log style

---

docs/guide/basic/store.md
examples/basic-nested-store/src/pages/About/model.ts
examples/basic-nested-store/src/pages/About/store.ts
packages/plugin-store/src/template/types.ts.ejs

docs: update store docs

---

docs/guide/basic/store.md

fix: docs typo.

---

docs/guide/advance/auth.md
examples/basic-auth/src/app.tsx
packages/plugin-auth/src/runtime.tsx

https://github.com/alibaba/ice/issues/3310

feat: support function component

---

docs/guide/cli-start.md
docs/guide/iceworks-start.md
docs/guide/migrate.md
docs/guide/start.md

Ref: https://github.com/alibaba/ice/issues/3613

Docs: node env preparation

---

examples/with-rax/build.json
packages/plugin-app-base/src/base.js
packages/plugin-rax-kraken/src/index.js
packages/plugin-rax-miniapp/src/index.js
packages/plugin-rax-web/src/index.js
packages/plugin-rax-weex/src/index.js
packages/plugin-ssr/src/index.ts

- Fix: Define public url
- Chore: optimize copy public dir

chore: optimize project code

---

packages/build-app-helpers/src/formatPath.ts
packages/build-app-helpers/src/index.ts
packages/build-mpa-config/package.json
packages/build-mpa-config/src/index.ts
packages/build-mpa-config/src/mpa-loader.ts
tsconfig.json
yarn.lock

fix(rax-app): mpa windows error

---

packages/build-app-helpers/package.json
packages/build-app-helpers/src/formatPath.ts
packages/build-app-helpers/src/index.ts
packages/build-mpa-config/package.json
packages/build-mpa-config/src/index.ts
packages/build-mpa-config/src/mpa-loader.ts
packages/plugin-app-base/package.json
packages/plugin-app-base/src/userConfig/externals.js
packages/plugin-rax-kraken/package.json
packages/plugin-rax-web/package.json
packages/plugin-rax-weex/package.json
packages/plugin-ssr/package.json
packages/rax-app/package.json
tsconfig.json
yarn.lock

- 修复 windows 报错
- 修复低版本 ios 报错
- 更新 node 最低版本提示
- 修复 externals 不生效的问题

release: rax-app v3.0.5

---

examples/basic-store/package.json
examples/basic-store/src/models/counter.ts
packages/plugin-app-core/src/generator/templates/app/react/index.ts.ejs
packages/plugin-app-core/src/generator/templates/common/appMode.ts.ejs

https://github.com/alibaba/ice/issues/3630

fix: appMode is undefined

---

packages/create-ice/package.json
packages/create-ice/src/create.ts

Add tips after create：
* AliInternal user recommended.
* iceworks information.

Feat add tips after create

---

packages/plugin-store/src/generator.ts
packages/plugin-store/src/template/types.ts.ejs

修复：在自定义创建 store 条件下，store 相关的 types 没有导出

Fix: store types not existed

---

packages/plugin-app-core/src/generator/templates/app/react/index.ts.ejs

Feat: create app warning

---

examples/with-rax/src/app.json
packages/create-app-shared/package.json
packages/create-app-shared/src/constants.ts
packages/create-app-shared/src/nativeEventListener.ts
packages/create-app-shared/src/pageLifeCycles.ts

chore: change page lifecycle

---

packages/eslint-reporting-webpack-plugin/package.json
packages/eslint-reporting-webpack-plugin/src/index.js

Feat update eslint webpack console

feat update eslint webpack plugin

---

packages/plugin-mpa/src/index.ts

mpa 如果没有配置使用的html模版，默认使用index.html

mpa 如果没有配置使用的html模版，默认使用index.html

---

packages/build-user-config/src/getEnhancedWebpackConfig.js

fix eslint plugin probably be used twice.

fix eslint plugin init

---

packages/plugin-rax-app/src/config.js
packages/plugin-rax-app/src/setDev.js
packages/plugin-rax-web/src/index.js
packages/plugin-ssr/src/ssr/entryLoader.js

- 新增 `-- --mpa-entry=home` 指定多页模式启动时打开的页面
- 修复 `polyfill` 默认值为 `entry` 的问题

chore: enhance open browser logic

---

packages/plugin-rax-app/src/base.js
packages/plugin-rax-app/src/config.js
packages/plugin-rax-kraken/src/setEntry.js
packages/plugin-rax-miniapp/src/index.js
packages/plugin-rax-miniapp/src/setEntry.js
packages/plugin-rax-web/src/setEntry.js
packages/plugin-rax-weex/src/setEntry.js

`compileDependencies` 默认值改为 `['']`，即编译 node_modules，移除三方包中其他端的代码是必要操作。需要在文档中给出提示，假如需要更快的编译速度，可以将这个值改为 `[]` 或者部分包选择性编译。

chore: change compileDependencies default value

---

packages/build-user-config/src/userConfig/polyfill.js
packages/plugin-rax-app/package.json
packages/plugin-rax-app/src/config.js
packages/plugin-rax-app/src/setDev.js
packages/plugin-rax-kraken/package.json
packages/plugin-rax-kraken/src/setEntry.js
packages/rax-app/package.json

- Fix: mpa restart logic
- Fix: polyfill default value
- Fix: kraken error

hotfix: rax-app v3.0.8

---

packages/build-user-config/package.json
packages/build-user-config/src/userConfig/externals.js
packages/build-user-config/src/userConfig/polyfill.js
packages/build-user-config/src/utils/processPresetEnv.js
packages/icejs/package.json
packages/plugin-rax-app/package.json
packages/plugin-rax-app/src/config.js
packages/plugin-rax-app/src/setDev.js
packages/plugin-rax-kraken/package.json
packages/plugin-rax-kraken/src/setEntry.js
packages/plugin-react-app/package.json
packages/plugin-react-app/src/index.js
packages/rax-app/package.json

hotfix icejs@1.11.1

---

packages/eslint-reporting-webpack-plugin/package.json
packages/eslint-reporting-webpack-plugin/src/index.js

Fix local eslint error

---

packages/build-user-config/src/applyCliOption.js

feat: support framework custom cli options

---

packages/build-user-config/src/config/user.config.js
packages/build-user-config/src/getEnhancedWebpackConfig.js
packages/build-user-config/src/userConfig/eslint.js

Feat support off ESLint. eslint: false off all ESLint actions.
https://github.com/alibaba/ice/issues/3830

Feat support off ESLint

---

packages/build-user-config/src/index.ts
packages/build-user-config/src/utils/generateDefaultConfig.js
packages/plugin-react-app/src/utils/getMiniappOutputPath.js
packages/plugin-react-app/src/utils/getWebOutputPath.js

- @builder/user-config 补全导出 defaultConfig
- 移除原先 build-plugin-react-app 里关于 outputDir 的无效代码

fix: default config output dir

---

packages/build-mpa-config/package.json
packages/build-mpa-config/src/template/rax.ts
packages/build-mpa-config/src/template/react.ts
packages/icejs/package.json
packages/plugin-mpa/package.json
packages/plugin-mpa/src/index.ts

兼容既设置 mpa 为 true，又设置 disableRuntime 为 true 的场景

fix: do not generate mpa entries when disableRuntime

---

packages/icejs/package.json
packages/icejs/src/getBuiltInPlugins.ts
packages/plugin-app-core/package.json
packages/plugin-app-core/src/constant.ts

feat: support disable auth

---

packages/build-user-config/package.json
packages/build-user-config/src/userConfig/eslint.js

去除 cache 。 防止有cache 情况下， 用户修改配置无效。

Feat remove cache

---

examples/basic-ssr/src/app.ts
examples/basic-ssr/src/config.ts
examples/basic-ssr/src/pages/About/index.tsx
examples/basic-ssr/src/pages/Dashboard/index.tsx
examples/basic-ssr/src/pages/Home/index.tsx
examples/basic-ssr/src/routes.ts
packages/plugin-ice-ssr/src/index.ts
packages/plugin-ice-ssr/src/server.ts.ejs

Feat: support redirect in ssr

---

examples/basic-spa/src/app.tsx
packages/icejs/package.json
packages/plugin-app-core/package.json
packages/plugin-app-core/src/generator/templates/app/react/index.ts.ejs
packages/plugin-app-core/src/generator/templates/common/appMode.ts.ejs

revert: https://github.com/alibaba/ice/pull/3709

hotfix: runtime APP_MODE

---

packages/plugin-fusion/src/index.js
packages/plugin-load-assets/src/index.js

Ref: https://github.com/alibaba/ice/issues/3803

fix: compatible with component dev

---

packages/eslint-reporting-webpack-plugin/README.md
packages/eslint-reporting-webpack-plugin/package.json
packages/eslint-reporting-webpack-plugin/src/index.js

Update ESLibt plugin only run after the project is complete compiled.

Feat update eslint plugin runtime

---

packages/plugin-react-app/src/setDev.js

feat: support webIDE dev url

---

packages/icejs/package.json
packages/plugin-app-core/package.json
packages/plugin-app-core/src/generator/templates/app/rax/index.ts.ejs
packages/plugin-app-core/src/generator/templates/app/react/index.ts.ejs
packages/plugin-app-core/src/generator/templates/common/appMode.ts.ejs
packages/plugin-app-core/src/generator/templates/common/runApp.ts.ejs
packages/plugin-config/package.json
packages/plugin-config/src/index.ts

Ref: 
- https://github.com/alibaba/ice/pull/3882
- https://github.com/alibaba/ice/issues/3630
Description:
- 确保 `APP_MODE` 变量导出在 `.ice/config.ts` 导入之后（即 `src/config.ts` 中 `window.__app_mode__` 被赋值后）
- `createApp` 的改造放在 `runApp.ts` 中

fix: store load time early

---

packages/build-mpa-config/src/generateEntry.ts
packages/build-mpa-config/src/template/rax.ts.ejs

feat: define hydrate value when build

---

packages/plugin-app-core/src/utils/getBuildConfig.ts

chore: build config add web

---

docs/guide/basic/build.md
packages/build-scripts-config/package.json
packages/build-scripts-config/src/config/webpack/postcss.config.js
packages/build-user-config/src/config/user.config.js
packages/build-user-config/src/userConfig/postcssOptions.js
yarn.lock

feat: support postcssOptions

---

examples/basic-custom-app-store/src/routes.ts
examples/basic-custom-app-store/src/typings.d.ts
examples/basic-nested-store/src/routes.ts
examples/basic-nested-store/src/typings.d.ts
examples/basic-spa/src/pages/Dashboard/index.tsx
examples/basic-store/src/pages/Detail/model.ts
examples/basic-store/src/routes.ts
examples/basic-store/src/typings.d.ts
examples/with-prerender-spa/src/pages/Home/index.tsx
examples/with-react-miniapp-todos/src/pages/add-todo/index.jsx
packages/build-user-config/src/utils/updateMiniCssLoaderPath.js
packages/create-app-container/src/index.ts
packages/create-cli-utils/src/start.js
packages/eslint-reporting-webpack-plugin/src/index.js
packages/icejs/src/getBuiltInPlugins.ts
packages/plugin-app-core/src/config/setAlias.ts
packages/plugin-app-core/src/index.ts
packages/plugin-router/src/collector/walker.ts
packages/plugin-router/src/runtime/formatRoutes.tsx
packages/plugin-router/src/utils/index.ts
packages/plugin-service/src/index.ts
packages/plugin-store/src/_store.ts
packages/plugin-store/src/generator.ts
scripts/docConfig.js
scripts/fn/getPackages.ts
scripts/owner.ts
scripts/publish-beta-package.ts

引入 `no-multiple-empty-lines` eslint 规则后，对仓库的代码进行 lint:fix

chore: lint
