alibaba/ice

packages/build-app-helpers/src/getMpaEntries.ts, packages/build-mpa-config/src/index.ts
`getMpaEntries` 支持直接通过传入的静态配置内容解析
=> feat: support app json content

packages/build-user-config/package.json, packages/build-user-config/src/userConfig/compileDependencies.js
修复小程序 `compileDependencies` 未生效的问题
=> fix: miniapp compileDependencies

examples/basic-auth/tsconfig.json, examples/basic-custom-app-store/tsconfig.json, examples/basic-mpa/tsconfig.json, examples/basic-nested-store/tsconfig.json, examples/basic-request/tsconfig.json, examples/basic-rml/tsconfig.json, examples/basic-service/tsconfig.json, examples/basic-spa/tsconfig.json, examples/basic-ssr/tsconfig.json, examples/basic-store/tsconfig.json, examples/hello-world/tsconfig.json, examples/icestark-child/tsconfig.json, examples/icestark-layout/tsconfig.json, examples/simple/tsconfig.json, examples/with-fusion-design/tsconfig.json, examples/with-prerender-mpa/tsconfig.json, examples/with-prerender-spa/tsconfig.json, examples/with-react-miniapp-store/tsconfig.json, examples/with-react-miniapp-todos/tsconfig.json, examples/with-react-miniapp/tsconfig.json, examples/with-rematch/tsconfig.json
Ref: https://github.com/alibaba/ice/issues/3861
=> Chore: add compilerOption types

packages/build-user-config/src/loaders/AppConfigLoader/index.js
Ref PR: https://github.com/raxjs/rax-app/pull/551
=> feat: support getInitialProps in rax page component

docs/guide/advance/mpa.md, packages/plugin-mpa/src/index.ts
=> feat: templateParameters of mpa

docs/guide/basic/router.md, packages/create-app-shared/src/createBaseApp.ts
=> fix: custom history

packages/plugin-fusion/CHANGELOG.md, packages/plugin-fusion/package.json, packages/plugin-fusion/src/index.js, packages/plugin-fusion/src/utils/getThemeVars.js
=> fix: plugin-fusion rules

examples/basic-spa/build.json, packages/build-user-config/package.json, packages/build-user-config/src/userConfig/webpackPlugins.js, packages/icejs/package.json
Closed: https://github.com/ice-lab/icestark/issues/231
=> HotFix: use webpack plugin error

packages/plugin-fusion/package.json, packages/plugin-fusion/src/webpackPlugins/appendStyleWebpackPlugin.js, packages/plugin-wrap-code/package.json, packages/plugin-wrap-code/src/wrapCodeWebpackPlugin.js
=> fix: compatible with webpack apis

packages/plugin-ice-ssr/src/server.ts.ejs, packages/react-app-renderer/src/server.tsx
支持传入 publicPath，以生成出来的 html 中的 bundle 地址为传入的 publicPath
=> Fix: publicPath in faas application

packages/icejs/package.json
=> [WIP] Release

packages/webpack-dev-mock/package.json, packages/webpack-dev-mock/src/index.ts
=> fix: use debounce to avoid too much watch events

packages/plugin-fusion/package.json, packages/plugin-fusion/src/index.js
=> fix: external next styles

packages/plugin-icestark/package.json, packages/plugin-icestark/src/babelPluginMicroapp.ts
=> fix: add lifecycle of bootstrap

packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/plugin-icestark/src/babelPluginMicroapp.ts, packages/plugin-icestark/src/index.ts
✅ Closes: https://github.com/ice-lab/icestark/issues/240
=> feat: 🎸 append set library

docs/guide/advance/ssr.md
=> Docs: ssr server render params

docs/icestark/guide/child-app.md
=> docs: fix demo code

packages/build-user-config/src/userConfig/babelPresets.js
=> fix: format path before match

packages/create-app-shared/src/runtimeModule.ts, packages/plugin-app-core/package.json, packages/plugin-app-core/src/generator/templates/common/loadRuntimeModules.ts.ejs, packages/plugin-app-core/src/generator/templates/common/loadStaticModules.ts.ejs, packages/plugin-app-core/src/index.ts, packages/plugin-app-core/src/utils/getRuntimeModules.ts, packages/plugin-auth/package.json, packages/plugin-auth/src/runtime.tsx, packages/plugin-icestark/package.json, packages/plugin-icestark/src/runtime.tsx, packages/plugin-logger/package.json, packages/plugin-logger/src/runtime.ts, packages/plugin-rematch/package.json, packages/plugin-rematch/src/runtime.tsx, packages/plugin-request/src/runtime.ts, packages/plugin-router/src/runtime.tsx, packages/plugin-router/src/runtime/Router.tsx, packages/plugin-store/package.json, packages/plugin-store/src/runtime.tsx
=> refactor: generate runtime module

packages/plugin-app-core/src/config/setProjectType.ts, packages/plugin-app-core/src/constant.ts, packages/plugin-webpack5/package.json, packages/plugin-webpack5/src/analyzeNext.ts, packages/plugin-webpack5/src/babelPluginRemote.ts, packages/plugin-webpack5/src/compileRemote.ts, packages/plugin-webpack5/src/filterPackages.ts, packages/plugin-webpack5/src/index.ts, packages/plugin-webpack5/src/remoteConfig.ts, yarn.lock
fusion design pro 正常启动基本在 1min 左右
首次编译：正常耗时 30s，另编译 remoteEntry 耗时 5s 之内，整体提升 40%
> 通过 remote runtime 编译依赖和样式优化，这块时间还有很大提升空间
方案二次启动平均控制在 10s 之内，二次编译提升 80%
=> feat: remote runtime by module federation

docs/icestark/guide/child-app.md
✅ Closes: https://github.com/ice-lab/icestark/issues/261
=> docs: ✏️ how vue3.0 as mf-child

docs/guide/develop/plugin-list.md
Feat docs add build-plugin-dev-inspector
=> Feat docs add build-plugin-dev-inspector

packages/webpack-dev-mock/src/index.ts
=> fix: update mock config after file change

packages/plugin-icestark/package.json, packages/plugin-icestark/src/babelPluginMicroapp.ts
=> feat: 🎸 turn lifecycles promise

examples/basic-spa/src/routes.ts, packages/create-app-shared/src/createBaseApp.ts, packages/create-app-shared/src/emitLifeCycles.ts, packages/create-app-shared/src/enhanceWithRouter.ts, packages/create-app-shared/src/history.ts, packages/plugin-router/src/types/index.ts
ref: https://github.com/alibaba/ice/issues/4145
=> Fix: api types

packages/plugin-fusion/CHANGELOG.md, packages/plugin-fusion/src/index.js, packages/plugin-fusion/src/utils/getThemeCode.js
relate to https://github.com/alibaba/ice/issues/4191
=> feat: support css variables

packages/plugin-webpack5/CHANGELOG.md, packages/plugin-webpack5/src/babelPluginRemote.ts, packages/plugin-webpack5/src/builtInDependenies.ts, packages/plugin-webpack5/src/compileRemote.ts, packages/plugin-webpack5/src/filterPackages.ts, packages/plugin-webpack5/src/index.ts, packages/plugin-webpack5/src/remoteConfig.ts
=> feat: remote built-in dependencies

examples/basic-ssr-with-lazy-load/package.json, examples/basic-ssr/package.json, packages/plugin-ice-ssr/CHANGELOG.md, packages/plugin-ice-ssr/package.json, packages/plugin-ice-ssr/src/index.ts, packages/plugin-ice-ssr/src/server.ts.ejs
ref: https://github.com/alibaba/ice/issues/4203
=> Fix: not generate server bundle

packages/build-mpa-config/src/generateEntry.ts, packages/build-mpa-config/src/template/rax.ts.ejs
https://github.com/raxjs/rax-app/issues/705
=> feat: custom tab bar in MPA

packages/build-mpa-config/CHANGELOG.md, packages/build-mpa-config/package.json
@build/mpa-config@3.2.0 版本被占了，升一个小版本
=> chore: bump @builder/mpa-config version

packages/create-app-shared/CHANGELOG.md, packages/create-app-shared/src/runtimeModule.ts, packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/src/runtime.tsx, packages/plugin-router/CHANGELOG.md, packages/plugin-router/src/runtime.tsx
=> fix: keepAlive work with plugin-icestark

packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/plugin-icestark/src/runtime.tsx
=> fix: 🐛 make router.basename work in icestark context

packages/plugin-router/src/collector/splicer.ts
=> fix: route order generated by file system

packages/build-user-config/package.json, packages/build-user-config/src/config/user.config.js, packages/build-user-config/src/userConfig/customScriptAttrs.js
add a user-config to custom the attribute of script-tag, like:
```json
{
"customScriptAttrs": {
"crossorigin": "anonymous"
}
}
```
result:
```html
<body>
<script src="/js/index.js" crossorigin="anonymous"></script>
</body>
```
=> feat(build-user-config): add user-config: customScriptAttrs

packages/plugin-ice-ssr/CHANGELOG.md, packages/react-app-renderer/src/server.tsx
=> fix: router in appConfig is undefined in ssr

packages/plugin-fusion/CHANGELOG.md, packages/plugin-fusion/src/index.js, packages/plugin-fusion/src/utils/getCalcVars.js, packages/plugin-fusion/src/utils/getThemeCode.js
=> fix: remove error string in calculated colors

packages/babel-preset-ice/CHANGELOG.md, packages/babel-preset-ice/package.json, packages/babel-preset-ice/src/index.ts, yarn.lock
remove `@babel/plugin-proposal-class-properties` while this plugin is included in `@babel/preset-env`, visit : https://babeljs.io/docs/en/babel-plugin-proposal-class-properties
Fix #4285
=> fix: remove duplicate babel plugin

packages/react-app-renderer/src/renderer.tsx
Fix some bug at https://github.com/alibaba/ice/issues/4259
=> fix: history referenced by GID is undefined (#4259)

packages/plugin-stark-module/CHANGELOG.md, packages/plugin-stark-module/package.json, packages/plugin-stark-module/src/setUMDConfig.ts
=> feat: 🎸 set contentBase the right way

packages/create-app-shared/CHANGELOG.md, packages/create-app-shared/package.json, packages/create-app-shared/src/constants.ts, packages/create-app-shared/src/createBaseApp.ts, packages/create-app-shared/src/history.ts, packages/create-app-shared/src/index.ts, packages/icejs/package.json, packages/plugin-app-core/CHANGELOG.md, packages/plugin-app-core/package.json, packages/plugin-app-core/src/config/importDeclarations.ts, packages/plugin-app-core/src/generator/templates/common/runApp.ts.ejs, packages/react-app-renderer/CHANGELOG.md, packages/react-app-renderer/package.json, packages/react-app-renderer/src/renderer.tsx
Fix some bug at https://github.com/alibaba/ice/issues/4259
=> fix: history referenced by GID is undefined

packages/build-user-config/CHANGELOG.md, packages/build-user-config/package.json, packages/build-user-config/src/utils/babelPluginCorejsLock.js
=> fix: require order of polyfill

packages/build-scripts-config/CHANGELOG.md, packages/build-scripts-config/src/config/webpack/defaultPostcssConfig.js
=> fix: enable stage 3 for postcss preset env

docs/guide/advance/mpa.md, examples/basic-mpa/build.json, packages/plugin-mpa/CHANGELOG.md, packages/plugin-mpa/src/index.ts, packages/plugin-react-app/CHANGELOG.md, packages/plugin-react-app/src/setDev.js
=> feat: devServer rewrites rule for mpa development

packages/plugin-app-core/src/generator/index.ts, packages/plugin-auth/package.json, packages/plugin-auth/src/index.ts, packages/plugin-auth/template/index.tsx.ejs
=> fix: compatible with react-jsx when generate auth runtime

packages/plugin-webpack5/CHANGELOG.md, packages/plugin-webpack5/package.json, packages/plugin-webpack5/src/remoteConfig.ts
=> fix: compatible with win32 when delete original entry

packages/build-user-config/src/cliOption/https.js, yarn.lock
1. 优化提示
改成
2. 解决重复添加undefined域名
=> feat: 启动https服务时使用trusted-cert的优化

README.md, README_zh-CN.md, packages/build-scripts-config/CHANGELOG.md, packages/build-scripts-config/package.json, packages/build-scripts-config/src/config/webpack/setWebpackLoaders.js
https://github.com/alibaba/ice/issues/4370
=> feat: support webp image file

packages/build-user-config/CHANGELOG.md, packages/build-user-config/src/cliOption/https.js, packages/plugin-react-app/CHANGELOG.md, packages/plugin-react-app/src/index.js
启动 https 时，给 `devServer` 配置的 host 签发证书
=> feat: add devServer.host to https cert

packages/plugin-fusion/CHANGELOG.md, packages/plugin-fusion/package.json, packages/plugin-fusion/src/index.js
=> fix: compatible with umd export when external Next

packages/plugin-stark-module/CHANGELOG.md, packages/plugin-stark-module/package.json
=> fix: 🐛 update build-user-config

packages/plugin-react-app/package.json, packages/plugin-react-app/src/config.js, packages/plugin-react-app/src/userConfig/fastRefresh.js
enable fast-refresh for default
=> feat: built-in react fast refresh

packages/create-app-shared/src/runtimeModule.ts, packages/plugin-app-core/src/config/setRegisterMethod.ts, packages/plugin-app-core/src/utils/formatPluginDir.ts, packages/plugin-app-core/src/utils/getRuntimeModules.ts
=> fix: format runtime folder

packages/plugin-jsx-plus/CHANGELOG.md, packages/plugin-jsx-plus/package.json, packages/plugin-jsx-plus/src/index.js
https://github.com/alibaba/ice/issues/4427
=> fix: jsx+ in tsx for list error

packages/build-user-config/src/userConfig/cssLoaderOptions.js, packages/build-user-config/src/userConfig/lessLoaderOptions.js, packages/build-user-config/src/userConfig/sassLoaderOptions.js, yarn.lock
Support `forceEnableCSS` config.
Will create new rule named `less-global` or `sass-global`, should merge config when `forceEnableCSS` is `true`.
支持 `forceEnableCSS` 配置。
会创建名为 `less-global` 或 `sass-global` 的新规则，当 `forceEnableCSS` 为 `true` 的时候需要合并配置。
=> feat: support `forceEnableCSS` config

examples/basic-spa/package.json, packages/babel-preset-ice/package.json, packages/build-scripts-config/package.json, packages/build-scripts-config/src/config/webpack/webpack.build.js, packages/build-user-config/package.json, packages/icejs/package.json, yarn.lock
upgrade and lock dependencies pack version
=> fix: upgrade dependencies pack version

package.json, packages/build-babel-config/package.json, packages/build-jest-config/package.json, packages/build-user-config/package.json, packages/build-webpack-config/package.json, packages/icejs/package.json, yarn.lock
bump pack version to fix terser error https://github.com/ice-lab/builder-deps/pull/6
=> chore: bump @builder/pack version

packages/build-app-templates/src/templates/rax/runApp.ts.ejs, packages/build-app-templates/src/templates/react/runApp.ts.ejs, packages/build-mpa-config/src/generate/BaseGenerator.ts, packages/build-mpa-config/src/generate/RaxGenerator.ts, packages/build-mpa-config/src/generate/ReactGenerator.ts, packages/build-mpa-config/src/relative.ts, packages/build-mpa-config/src/template/rax/index.tsx.ejs, packages/build-mpa-config/src/template/react/index.tsx.ejs, packages/plugin-app-core/src/index.ts
=> chore: optimize file path

examples/basic-spa/build.json, examples/basic-spa/src/app.tsx, examples/basic-spa/src/config.ts, examples/basic-spa/src/pages/Home/index.tsx, examples/basic-ssr-with-lazy-load/src/pages/About/index.tsx, examples/basic-ssr-with-lazy-load/src/pages/Home/index.tsx, examples/basic-ssr-with-lazy-load/src/pages/NotFound/index.tsx, examples/basic-ssr/src/pages/About/index.tsx, examples/basic-ssr/src/pages/Dashboard/index.tsx, examples/basic-ssr/src/pages/Home/index.tsx, examples/basic-ssr/src/pages/NotFound/index.tsx, packages/build-user-config/src/userConfig/esbuild.js, packages/icejs/src/getBuiltInPlugins.ts, packages/plugin-logger/logger/index.ts, packages/plugin-logger/package.json, packages/plugin-logger/src/_logger.ts, packages/plugin-logger/src/index.ts, packages/plugin-logger/src/levels.ts, packages/plugin-logger/src/runtime.ts, packages/plugin-logger/src/runtime/Logger.ts
https://github.com/alibaba/ice/issues/4493
=> refactor: rework logger plugin

packages/build-babel-config/package.json, packages/build-jest-config/package.json, packages/build-user-config/package.json, packages/build-webpack-config/package.json, packages/icejs/package.json, packages/plugin-router/package.json, packages/plugin-store/src/index.ts, packages/plugin-store/src/vitePluginPageRedirect.ts, packages/plugin-theme/package.json, packages/vite-service/src/plugins.ts, yarn.lock
=> fix: build error in vite mode

packages/build-user-config/src/config/user.config.js, packages/plugin-react-app/package.json, packages/plugin-react-app/src/config.js, packages/plugin-react-app/src/userConfig/fastRefresh.js, packages/plugin-react-app/src/userConfig/remoteRuntime/preBuild.ts, yarn.lock
@pmmmwh/react-refresh-webpack-plugin 在源码侧有依赖暂时先不预编译
=> fix: hmr when development

examples/basic-vite/build.json, packages/vite-service/package.json, packages/vite-service/src/wp2vite/index.ts, packages/vite-service/src/wp2vite/plugins.ts
=> Fix: polyfill file in hash and outputAssetsPath

packages/plugin-app-core/src/utils/getRuntimeModules.ts
runtime 中涉及类型文件引入，因此不好通过 esbuild + es-module-lexer 分析，采取正则匹配
整体耗时大致看了下增加约 50ms
=> fix: analyze runtime before generate

packages/plugin-webpack5/CHANGELOG.md, packages/plugin-webpack5/package.json, packages/plugin-webpack5/src/index.ts
Close https://github.com/alibaba/ice/issues/4436
=> fix: OOM when use plugin webpack5

packages/vite-service/src/plugins/polyfill.ts
=> fix: remove assets directory

packages/vite-service/src/wp2vite/config.ts
=> Fix: vite alias config cover

packages/build-mpa-config/package.json, packages/build-user-config/package.json, packages/create-cli-utils/package.json, packages/icejs/package.json, packages/plugin-config/package.json, packages/plugin-dev-inspector/package.json, packages/plugin-helmet/package.json, packages/plugin-icestark/package.json, packages/plugin-logger/package.json, packages/plugin-mpa/package.json, packages/plugin-react-app/package.json, packages/plugin-router/package.json, packages/plugin-stark-module/package.json, packages/plugin-theme/package.json, packages/vite-service/package.json, yarn.lock
Relate to https://github.com/ice-lab/build-scripts/pull/54
=> fix: migrate webpack-dev-server to 4.0.0

packages/vite-service/src/wp2vite/config.ts, packages/vite-service/src/wp2vite/index.ts
选择 vite 模式，兼容性要求并不高，polyfill 跟用户配置主动开启
=> fix: terser options transform

packages/plugin-webpack5/CHANGELOG.md, packages/plugin-webpack5/package.json, packages/plugin-webpack5/src/index.ts
already fixed in 2.0 https://github.com/alibaba/ice/pull/4531
=> fix: oom when installed by cnpm

packages/plugin-app-core/CHANGELOG.md, packages/plugin-app-core/package.json, packages/plugin-app-core/src/config/setRegisterMethod.ts, packages/plugin-app-core/src/utils/getRoutes.ts, packages/plugin-app-core/src/utils/getSourceFile.ts, packages/plugin-config/CHANGELOG.md, packages/plugin-config/package.json, packages/plugin-config/src/index.ts, yarn.lock
相关 issue #4579
store 逻辑已在 2.x 版本中重构
=> fix: ignore project type when get source file

packages/plugin-config/src/template/index.ts.ejs, packages/vite-service/src/plugins/html.ts, packages/vite-service/src/wp2vite/index.ts
- 直接使用 globalThis (node.js 要求 12.0+，browser 环境依赖 core-js 进行 polyfill)
- 移除没必要的 define 信息
=> fix: global polyfill

packages/icejs/package.json, packages/plugin-ice-ssr/CHANGELOG.md, packages/plugin-ice-ssr/package.json, packages/plugin-ice-ssr/src/index.ts, packages/plugin-ice-ssr/src/server.ts.ejs
Ref: https://github.com/alibaba/ice/issues/4428
=> feat: get publicPath from build config

examples/basic-auth/package.json, examples/basic-auth/src/pages/Home/index.tsx, examples/basic-auth/src/routes.ts, packages/plugin-auth/template/index.tsx.ejs, packages/plugin-auth/template/types.ts, packages/plugin-router/src/runtime/Router.tsx
- check route config before assign to component static props
- optimize types of plugin-auth
=> fix: config auth by static props of component

packages/build-user-config/src/utils/babelPluginCorejsLock.js
addSideEffect 将会在文件的最顶部注入依赖
Fix https://github.com/alibaba/ice/issues/4620
=> fix: order of core-js modules

examples/basic-store/src/models/counter.ts, examples/basic-store/src/pages/Home/index.tsx, packages/plugin-store/package.json, yarn.lock
- 增加 immer 的使用示例
- @ice/store 版本升级
=> feat: add immer usage example

packages/plugin-stark-module/src/index.ts, packages/plugin-stark-module/src/setUMDConfig.ts
For stark module to support faas
=> feat: support module with faas

packages/plugin-store/src/index.ts
This reverts commit c852f660021e02190016702ce052c82f658419db.
=> Revert "chore: generator to Generator" commit

examples/basic-spa/src/app.tsx, packages/create-app-shared/CHANGELOG.md, packages/create-app-shared/package.json, packages/create-app-shared/src/storage.ts
Fix: https://github.com/alibaba/ice/issues/4687
=> fix: set history value after initHistory

examples/with-fusion-design/build.json, examples/with-fusion-design/package.json, examples/with-fusion-design/src/pages/Home/index.tsx, packages/plugin-fusion/CHANGELOG.md, packages/plugin-fusion/package.json, packages/plugin-fusion/src/index.js, packages/plugin-fusion/src/vitePluginTheme.ts
=> fix: theme icon in vite mode

packages/build-jest-config/CHANGELOG.md, packages/build-jest-config/package.json, packages/build-jest-config/src/babelTransform.ts, packages/build-jest-config/src/index.ts
=> fix: jest config

examples/basic-ssr/package.json, examples/basic-ssr/src/pages/Dashboard/index.tsx, examples/basic-ssr/src/routes.ts, packages/plugin-ice-ssr/CHANGELOG.md, packages/plugin-ice-ssr/package.json, packages/plugin-ice-ssr/src/server.ts.ejs
Closed: https://github.com/alibaba/ice/issues/4679
=> fix: Component.getInitialProps function isn't be executed

packages/plugin-ice-ssr/CHANGELOG.md, packages/plugin-ice-ssr/src/server.ts.ejs
https://reactrouter.com/web/guides/server-rendering
=> Fix: redirectUrl is undefined

packages/plugin-icestark/package.json, packages/plugin-icestark/src/index.ts, packages/plugin-icestark/src/runtime.tsx, yarn.lock
=> fix: 🐛 type error in icestark

packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/plugin-icestark/src/index.ts, packages/plugin-icestark/src/runtime.tsx, packages/plugin-icestark/src/runtime/removeLayout.ts, yarn.lock
=> Release: plugin-icestark 2.4.1

packages/vite-service/CHANGELOG.md, packages/vite-service/package.json, packages/vite-service/src/wp2vite/config.ts
=> fix: transform postcssOptions for vite

packages/build-babel-config/CHANGELOG.md, packages/build-babel-config/package.json, packages/build-babel-config/src/index.ts, packages/build-user-config/CHANGELOG.md, packages/build-user-config/package.json, packages/build-user-config/src/userConfig/polyfill.ts
=> feat: 🎸 support latetst polyfills untill ECMAScript 2021

packages/build-babel-config/CHANGELOG.md, packages/build-babel-config/package.json, packages/build-babel-config/src/index.ts, packages/build-user-config/CHANGELOG.md, packages/build-user-config/package.json, packages/build-user-config/src/config/user.config.js, packages/build-user-config/src/userConfig/devServer.js, packages/build-user-config/src/userConfig/polyfill.ts
=> Release:builder-user-config-1.1.4

examples/basic-ssr/src/pages/About/index.tsx, examples/basic-ssr/src/pages/Home/index.tsx, examples/basic-ssr/src/routes.ts, packages/icejs/package.json, packages/plugin-ice-ssr/CHANGELOG.md, packages/plugin-ice-ssr/package.json, packages/plugin-ice-ssr/src/index.ts, yarn.lock
fix: https://github.com/alibaba/ice/issues/4861
=> fix: ssr not works in file-system routes

packages/vite-service/CHANGELOG.md, packages/vite-service/src/wp2vite/config.ts, yarn.lock
Fix: https://github.com/alibaba/ice/issues/4902
=> fix: config postcssOptions

packages/plugin-dev-inspector/CHANGELOG.md, packages/plugin-dev-inspector/package.json, packages/plugin-dev-inspector/src/index.ts
=> fix: error devServer config when use webpack-dev-server v4

packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/plugin-icestark/src/runtime.tsx
=> fix: 🐛 provide initial `pathname` with `location`

packages/icejs/bin/copy-dts-to-ice-temp.js
related PR: https://github.com/alibaba/ice/pull/4809
=> fix: process.env.INIT_CWD is undefined in low version npm

packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/plugin-icestark/src/runtime.tsx
=> feat: 🎸 release plugin-icestark 2.4.2

packages/icejs/package.json, packages/plugin-router/CHANGELOG.md, packages/plugin-router/package.json, packages/plugin-router/src/runtime/formatRoutes.tsx
=> hotfix: nested router config

examples/with-prerender-spa/src/routes.ts, packages/icejs/package.json, packages/plugin-ice-ssr/CHANGELOG.md, packages/plugin-ice-ssr/package.json, packages/plugin-ice-ssr/src/renderPages.ts.ejs, packages/plugin-ice-ssr/src/server.ts.ejs, packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/runtime/src/index.ts, yarn.lock
- feat: lock the dependency `path-to-regexp` version to 1.x (follow the react-router-dom@5.x)
- fix: router path may be undefined in ssg
=> fix: ssg render error

packages/miniapp-renderer/CHANGELOG.md, packages/miniapp-renderer/package.json, packages/miniapp-renderer/src/miniappRenderer.tsx
https://github.com/raxjs/rax-app/pull/878
=> fix: miniapp render

packages/plugin-router/CHANGELOG.md, packages/plugin-router/package.json, packages/plugin-router/src/index.ts
=> fix: support config devServer.historyApiFallback

packages/plugin-ice-ssr/CHANGELOG.md, packages/plugin-ice-ssr/package.json, packages/plugin-ice-ssr/src/index.ts, packages/plugin-ice-ssr/src/renderPages.ts.ejs, packages/plugin-ice-ssr/src/server.ts.ejs
server.ts 构建后 string template 语法将会被编译成  `"`
=> fix: compatible with special chars in html

packages/icejs/package.json, packages/plugin-config/CHANGELOG.md, packages/plugin-config/package.json, packages/plugin-config/src/template/index.ts.ejs, packages/vite-service/CHANGELOG.md, packages/vite-service/package.json, packages/vite-service/src/wp2vite/index.ts
=> fix: compatible with globalThis in vite mode

examples/basic-spa/src/pages/Dashboard/index.tsx, examples/basic-spa/src/routes.ts, packages/plugin-react-app/src/runtime.tsx, test/basic-spa.test.ts
=> feat: support props.pageConfig

packages/vite-service/CHANGELOG.md, packages/vite-service/package.json, packages/vite-service/src/plugins/html.ts
之前处理记录 https://github.com/alibaba/ice/pull/4627
vite 近期版本对于路径的 format 策略有调整，对所有 html 路径统一进行 format 修复
Resolves #5034
=> fix: build error in win32 system

examples/basic-spa/build.json, packages/build-user-config/CHANGELOG.md, packages/build-user-config/src/userConfig/alias.js
=> fix: enhance alias for node_modules dependencies

packages/vite-plugin-index-html/CHANGELOG.md, packages/vite-plugin-index-html/package.json, packages/vite-plugin-index-html/src/index.ts, packages/vite-plugin-index-html/src/utils.ts, packages/vite-plugin-index-html/tests/utils.ts
=> fix: 🐛 unexpected entry with too long root dir

packages/vite-service/CHANGELOG.md, packages/vite-service/package.json, packages/vite-service/src/wp2vite/config.ts
=> fix: add proxy listeners if exists

.github/workflows/1.x-publisher.yml, .github/workflows/auto-publisher.yml, .github/workflows/beta-publisher.yml
=> fix: using vulnerable action actions/checkout

packages/vite-service/CHANGELOG.md, packages/vite-service/package.json, packages/vite-service/src/start.ts, packages/vite-service/src/wp2vite/index.ts
Fix
- https://github.com/alibaba/ice/issues/5085
- https://github.com/alibaba/ice/issues/5084 （在 plugin-react-app 有 openBrowser 的逻辑，viteServer 不需要打开浏览器，统一在 plugin-react-app 中操作）
- https://github.com/alibaba/ice/issues/5070 （上一个 issue 解了，这个也自然解决了）
=> fix: open blank page and after.start.devServer excute time is error

packages/plugin-app-core/CHANGELOG.md, packages/plugin-app-core/package.json, packages/plugin-app-core/src/generator/templates/index.ts.ejs
=> fix: circular dependence of lazy when run test

packages/vite-service/src/plugins/html.ts
=> fix: vite index.html content-type

packages/build-user-config/CHANGELOG.md, packages/build-user-config/package.json, packages/build-user-config/src/cliOption/force.js, packages/build-user-config/src/config/option.config.js
=> feat: support cli option force to clear cache

packages/build-app-helpers/CHANGELOG.md, packages/build-app-helpers/package.json, packages/build-app-helpers/src/injectTransformRuntime.ts, packages/build-app-templates/CHANGELOG.md, packages/build-app-templates/package.json, packages/build-app-templates/src/templates/rax/runApp.ts.ejs, packages/build-app-templates/src/templates/react/runApp.ts.ejs, packages/build-user-config/CHANGELOG.md, packages/build-user-config/package.json, packages/build-user-config/src/getEnhancedWebpackConfig.js
- [chore] not inline @babel/runtime/helpers code
- [fix] `appConfig` need a default value
- [fix] rax runApp template export `getSearchParams` method
=> release next

packages/vite-plugin-index-html/CHANGELOG.md, packages/vite-plugin-index-html/package.json, packages/vite-plugin-index-html/src/index.ts, packages/vite-plugin-index-html/src/utils.ts, packages/vite-plugin-index-html/tests/index.test.ts, packages/vite-plugin-index-html/tests/utils.ts
=> fix/be compatible for input like `src/main`

packages/plugin-react-app/CHANGELOG.md, packages/plugin-react-app/package.json, packages/plugin-react-app/src/index.js
=> fix: vitePlugins only take effect when vite is true

packages/vite-service/CHANGELOG.md, packages/vite-service/package.json, packages/vite-service/src/wp2vite/index.ts
=> fix: 🐛 escape MockPlugn when --disable-mock

packages/build-user-config/CHANGELOG.md, packages/build-user-config/package.json, packages/build-user-config/src/userConfig/mock.js
兼容 rax-app 在 webpack 4 模式下的 dev server 参数
=> fix: compatible with rax-app devServer

packages/build-webpack-config/CHANGELOG.md, packages/build-webpack-config/package.json, packages/build-webpack-config/src/setWebpackLoaders.ts
https://github.com/webpack-contrib/css-loader#features
=> fix: css modules global selector

packages/create-app-shared/CHANGELOG.md, packages/create-app-shared/package.json, packages/create-app-shared/src/web/history.ts, packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/plugin-icestark/src/runtime.tsx
=> fix: 🐛 custom history

packages/build-app-helpers/CHANGELOG.md, packages/build-app-helpers/package.json, packages/build-app-helpers/src/analyzeRuntime.ts
Fix: https://github.com/alibaba/ice/issues/5184
=> fix: filter js file when analyze

packages/build-webpack-config/CHANGELOG.md, packages/build-webpack-config/package.json, packages/build-webpack-config/src/setWebpackLoaders.ts
This reverts commit 2c5bc295639bf58168a483249d7b65034a9a286c.
=> Revert "fix: css modules global selector (#5233)"

examples/basic-i18n/src/app.tsx, packages/create-app-shared/CHANGELOG.md, packages/create-app-shared/package.json, packages/create-app-shared/src/createInitHistory.ts, packages/create-app-shared/src/types.ts, packages/create-app-shared/src/web/history.ts, packages/icejs/package.json, packages/plugin-i18n/CHANGELOG.md, packages/plugin-i18n/package.json, packages/plugin-i18n/src/index.ts, packages/plugin-i18n/src/templates/index.tsx.ejs, packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/plugin-icestark/src/runtime.tsx, packages/plugin-router/CHANGELOG.md, packages/plugin-router/package.json, packages/plugin-router/src/runtime.tsx, packages/plugin-router/src/types/index.ts
- [feat] be able to pass arguments to memory router, closes https://github.com/alibaba/ice/pull/5247
- [feat] support setLocale API outer components, closes https://github.com/alibaba/ice/pull/5253
=> Release: 2.6.2

packages/build-app-helpers/CHANGELOG.md, packages/build-app-helpers/package.json, packages/build-app-helpers/src/analyzeRuntime.ts
=> fix: compile jsx syntax before analyze

packages/vite-service/CHANGELOG.md, packages/vite-service/src/build.ts, packages/vite-service/src/start.ts, yarn.lock
=> chore: optimize compile error

packages/icejs/package.json, packages/plugin-app-core/CHANGELOG.md, packages/plugin-app-core/package.json, packages/plugin-app-core/src/utils/getRuntimeModules.ts
=> fix: compatible with folder which has parentheses and spaces

packages/plugin-ignore-style/CHANGELOG.md, packages/plugin-ignore-style/README.md, packages/plugin-ignore-style/package.json, packages/plugin-ignore-style/src/index.ts
plugin-ignore-style默认的正则规则不够灵活，增加自定义rule支持灵活的ignore
=> feat: support custom rule for plugin-ignore-style

packages/build-user-config/src/userConfig/proxy.js
fix: res is undefined when proxy for websocket
=> fix: res is undefined when proxy for websocket

packages/plugin-request/src/runtime.ts
Prevent repeated injection interceptor
=> bugfix: repeat interceptor

packages/plugin-react-app/src/setBase.js
Fix https://github.com/alibaba/ice/issues/5308
=> fix: skip public folder for minimization

packages/build-webpack-config/CHANGELOG.md, packages/build-webpack-config/package.json, packages/build-webpack-config/src/setWebpackLoaders.ts, yarn.lock
Resolve #5349
Relate to https://github.com/ice-lab/builder-deps/pull/28
=> fix: problems with parse paths specified in url of css files

packages/webpack-plugin-extract-css-assets/CHANGELOG.md, packages/webpack-plugin-extract-css-assets/package.json
add change log for extract-css-assets-webpack-plugin
=> chore: changelog

packages/plugin-fusion/CHANGELOG.md, packages/plugin-fusion/package.json, packages/plugin-fusion/src/webpackLoaders/unicodeLoader.js
unicodeLoader do not return sourceMap will break resolve-url-loader
=> fix: return sourceMap of custom loader

packages/plugin-i18n/src/constants.ts, packages/plugin-i18n/src/index.ts, packages/plugin-i18n/src/runtime.tsx, packages/plugin-i18n/src/templates/index.tsx.ejs, packages/plugin-i18n/src/types.ts
增加插件配置项 cookieOptions，以支持修改设置 ice_locale 的 cookie 选项。
默认值是：`{ maxAge: 60 * 60 * 24 * 365 }`
=> feat: i18n cookieOptions

examples/basic-i18n/build.json, examples/basic-i18n/src/locales/locales.ts, examples/basic-i18n/src/locales/messages.ts, examples/basic-i18n/src/pages/UserInfo/index.tsx, examples/basic-i18n/src/routes.ts, examples/basic-ssr/build.json, packages/icejs/package.json, packages/plugin-i18n/CHANGELOG.md, packages/plugin-i18n/package.json, packages/plugin-i18n/src/constants.ts, packages/plugin-i18n/src/index.ts, packages/plugin-i18n/src/runtime.tsx, packages/plugin-i18n/src/templates/index.tsx.ejs, packages/plugin-i18n/src/types.ts, packages/plugin-i18n/src/utils/getDetectedLocaleFromPathname.ts, packages/plugin-i18n/src/utils/getLocaleData.ts, packages/plugin-i18n/src/utils/getRedirectIndexRoute.tsx, packages/plugin-i18n/src/utils/normalizeLocalePath.ts, packages/plugin-ice-ssr/CHANGELOG.md, packages/plugin-ice-ssr/package.json, packages/plugin-ice-ssr/src/index.ts, packages/plugin-ice-ssr/src/server.ts.ejs, yarn.lock
=> release 2.6.6

packages/plugin-fusion/CHANGELOG.md, packages/plugin-fusion/package.json, packages/plugin-fusion/src/webpackLoaders/unicodeLoader.js, packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/plugin-icestark/src/index.ts
=> fix: compatible with router false of plugin-icestark

packages/plugin-keep-alive/package.json
修复https://github.com/alibaba/ice/issues/5512
=> feat：由于react-activation版本低导致antd国际化失败以及其它context被破坏的问题

.github/workflows/auto-publisher.yml, package.json
=> fix: ci for publish

.editorconfig
=> chore: editor config

examples/with-basename/ice.config.mts, examples/with-basename/package.json, examples/with-basename/src/app.tsx, examples/with-basename/src/document.tsx, examples/with-basename/src/pages/about.tsx, examples/with-basename/src/pages/index.tsx, examples/with-basename/src/pages/layout.tsx, examples/with-basename/tsconfig.json, packages/runtime/src/runServerApp.tsx, pnpm-lock.yaml
修改在设置 basename 后在生产环境下生成的 html 内容是空的问题
=> fix: render empty html content in prod

packages/ice/templates/core/entry.client.tsx.ejs
=> fix: compat with createElement in rax mode

packages/create-ice/CHANGELOG.md, packages/create-ice/README.md, packages/create-ice/package.json, packages/create-ice/src/create.ts, packages/create-ice/src/index.mts, packages/create-ice/tsconfig.json, pnpm-lock.yaml, website/docs/guide/start.md
=> feat: ice.js 3 create-ice

package.json, packages/miniapp-html-styles/package.json, scripts/publishPackage.ts, scripts/publishPackageWithDistTag.ts
=> fix: publish script

packages/create-ice/CHANGELOG.md, packages/create-ice/package.json, packages/create-ice/src/index.mts
https://github.com/alibaba/ice/pull/5571#issuecomment-1318217604
=> fix: fs module is not defined

packages/webpack-config/src/unPlugins/redirectImport.ts, packages/webpack-config/tests/fixtures/redirectImport/matched.js, packages/webpack-config/tests/fixtures/redirectImport/missmatch.js, packages/webpack-config/tests/redirectImport.test.ts
Support partial match of redirect import
=> feat: support partial match of redirect import

tests/integration/app-config.test.ts, tests/integration/basic-project.test.ts, tests/integration/disable-data-loader.test.ts, tests/integration/hash-router.test.ts, tests/integration/rax-inline-style.test.ts, tests/integration/rax-project.test.ts, tests/integration/routes-generate.test.ts, tests/integration/single-router.test.ts, tests/integration/with-auth.test.ts, tests/integration/with-store.test.ts, vitest.config.ts
Pass a timeout value for long-running test for unexpected test error.
=> fix: pass a timeout value for long-running test

packages/ice/src/service/config.ts
Generate cache file in `.cache` directory.
=> fix: add temp file to cache dir

packages/ice/src/createService.ts
Fix script of `ice start --config custom.config.mts`
=> fix: support custom config file

website/docs/guide/advanced/codeSplitting.md
=> docs: code splitting

website/docs/guide/basic/document.md
- 增加 Document 组件参数 pagePath 的说明
=> docs: add Document props pagePath

packages/runtime/CHANGELOG.md, packages/runtime/src/Document.tsx
Document 中同时存在 `Data` 和 `Script` 组件时，需要 merge 二者的数据。（搭建 SSR）
=> fix: merge app context

packages/runtime/package.json
=> chore: version

examples/basic-project/ice.config.mts, packages/bundles/src/index.ts, packages/ice/package.json, packages/webpack-config/CHANGELOG.md, packages/webpack-config/package.json, packages/webpack-config/src/utils/transformCoreJs.ts, pnpm-lock.yaml
=> fix: format core-js path

packages/plugin-pha/CHANGELOG.md, packages/plugin-pha/package.json, packages/plugin-pha/src/index.ts, packages/plugin-pha/src/manifestHelpers.ts
修复自定义 HOST 时，PHA 插件访问 DEV Path 的异常的问题。
=> fix: fix dev path for pha

packages/plugin-pha/CHANGELOG.md, packages/plugin-pha/package.json, packages/plugin-pha/src/index.ts
=> feat: add pha query

packages/ice/CHANGELOG.md, packages/ice/src/config.ts, packages/ice/src/createService.ts, packages/ice/src/types/userConfig.ts, packages/ice/src/utils/renderExportsTemplate.ts
```js
export default defineConfig(() => ({
dataLoader: {
fetcher: {
packageName: 'custom-fetcher-lib',
method: 'request',
},
},
}));
```
=> feat: support config for fetcher

packages/ice/src/utils/getServerCompilerPlugin.ts
revert platform config set by https://github.com/alibaba/ice/pull/5628
=> fix: platform config

packages/ice/CHANGELOG.md, packages/ice/templates/exports/data-loader.ts.ejs
import 自定义 fetcher 的时候会报错，这个设计已经去除了，现在是 fetcher 参数。
=> fix: remove dataloaderFetcher

website/docs/guide/basic/document.md
=> docs: add docs of cumstom render

packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/runtime/src/Document.tsx, packages/runtime/src/dataLoader.ts, packages/runtime/src/runServerApp.tsx, packages/runtime/src/types.ts
=> fix: ssg data loader error

packages/runtime/src/runClientApp.tsx
=> fix: the error of switching route in react 16 #5739

website/docs/guide/basic/appear.md
=> docs:  modify doc of appear

packages/ice/CHANGELOG.md, packages/ice/src/plugins/web/index.ts, packages/ice/src/tasks/web/index.ts
=> fix: several bug when use dataLoader

website/docs/guide/basic/config.md, website/docs/guide/basic/data-loader.md
=> docs: add custom fetcher for static dataloader

packages/plugin-mpa/CHANGELOG.md, packages/plugin-mpa/package.json, packages/plugin-mpa/src/index.ts, packages/plugin-react-app/CHANGELOG.md, packages/plugin-react-app/package.json, packages/plugin-react-app/src/config.js, packages/plugin-react-app/src/setBuild.js, yarn.lock
Support custom optimize runtime rule.
=> feat: support custom optimize runtime rule

packages/ice/CHANGELOG.md, packages/ice/src/service/serverCompiler.ts, packages/ice/src/types/plugin.ts, packages/ice/src/webpack/DataLoaderPlugin.ts, packages/webpack-config/CHANGELOG.md, packages/webpack-config/src/getCompilerPlugins.ts, packages/webpack-config/src/index.ts, packages/webpack-config/src/types.ts, packages/webpack-config/src/unPlugins/compilation.ts
=> fix: do not compile data-loader to lower es version

packages/ice/src/plugins/web/index.ts, packages/ice/src/utils/getServerCompilerPlugin.ts, packages/ice/src/webpack/ServerCompilerPlugin.ts
Disable incremental when build.
=> fix: disable incremental when build

packages/bundles/CHANGELOG.md, packages/bundles/package.json, packages/ice/package.json, packages/plugin-rax-compat/package.json, packages/plugin-store/package.json, packages/webpack-config/package.json, pnpm-lock.yaml
=> chore: tag version

packages/runtime/src/runServerApp.tsx
=> fix: fix distType

examples/with-pha/ice.config.mts, examples/with-pha/src/app.tsx, examples/with-pha/src/pages/Custom/index.tsx, packages/ice/CHANGELOG.md, packages/ice/package.json, packages/plugin-pha/src/manifestHelpers.ts, pnpm-lock.yaml
=> hotfix: Release/3.0.5

packages/plugin-pha/CHANGELOG.md, packages/plugin-pha/package.json, packages/plugin-pha/src/constants.ts, packages/plugin-pha/src/types.ts, packages/plugin-pha/tests/manifestHelper.test.ts
PHA manifest 支持 enableExpiredManifest
=> feat: support enable_expired_manifest

website/docs/guide/advanced/update-from-icejs2.md
Close https://github.com/alibaba/ice/issues/5676
=> docs: add-icejs2-update

.github/workflows/website.yml
- Remove that update website when push to release-next
=> chore: website flow

packages/ice/CHANGELOG.md, packages/ice/src/plugins/web/index.ts, packages/ice/src/webpack/ServerCompilerPlugin.ts
=> fix: rebuild server entry when document changed

packages/plugin-store/src/runtime.tsx
this code change has no side effects, just improve the robustness of StoreProviderWrapper
=> fix: improve the robustness of StoreProviderWrapper

packages/ice/CHANGELOG.md, packages/ice/src/service/serverCompiler.ts, packages/ice/src/utils/getServerCompilerPlugin.ts
Add the right platform for server bundle.
=> fix: server compiler options when bundle server entry

examples/basic-project/ice.config.mts, packages/ice/CHANGELOG.md, packages/ice/src/config.ts
=> fix: default value of ssr

packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/runtime/src/routesConfig.ts
Compatible with empty meta element
=> fix: compatible with empty meta element

examples/icestark-child/src/app.tsx, packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/plugin-icestark/src/index.ts, packages/plugin-icestark/src/types.ts
Support lifecycle of `bootstrap` for qiankun micro app.
=> feat: support lifecycle of bootstrap

packages/ice/CHANGELOG.md, packages/ice/package.json, packages/ice/src/utils/getSupportedBrowsers.ts, packages/ice/src/webpack/DataLoaderPlugin.ts, pnpm-lock.yaml
fix：https://github.com/alibaba/ice/issues/5830
=> fix: data loader target

examples/basic-project/src/app.tsx, examples/basic-project/src/standard-module.ts, packages/ice/package.json, packages/webpack-config/CHANGELOG.md, packages/webpack-config/package.json, packages/webpack-config/src/webpackPlugins/AssetsManifestPlugin.ts, pnpm-lock.yaml, tests/integration/basic-project.test.ts
=> fix: dynamic import works in app.tsx

packages/create-ice/CHANGELOG.md, packages/create-ice/package.json, packages/create-ice/src/create.ts
Closes https://github.com/alibaba/ice/issues/5834
=> feat: add fusion pro scaffold

pnpm-lock.yaml, website/package.json
- 修复 website 构建报错的问题, 使用 `pnpm update` 升级了依赖解决
=> fix: website build with errors

packages/plugin-store/CHANGELOG.md, packages/plugin-store/package.json
代码变更内容 https://github.com/alibaba/ice/pull/5770
=> chore: bump verison of plugin-store

packages/ice/CHANGELOG.md, packages/ice/src/createService.ts, packages/ice/templates/exports/data-loader.ts.ejs
close https://github.com/alibaba/ice/issues/5878
=> fix: The imported dataloaderFetcher name is error

packages/plugin-pha/CHANGELOG.md
=> chore: add changelog for plugin pha

.github/workflows/ci.yml, .github/workflows/coverage.yml, .gitignore, .puppeteerrc.cjs
Changes the Puppeteer cache location for ci cache.
=> chore: changes the cache location for Puppeteer

website/docs/guide/plugins/plugin-dev.md
Fix import path of runtime types.
=> docs: import path of runtime types

examples/basic-project/src/pages/blog.tsx, packages/ice/package.json, packages/webpack-config/CHANGELOG.md, packages/webpack-config/package.json, packages/webpack-config/src/index.ts, pnpm-lock.yaml
=> fix: optimize webpack config

packages/plugin-pha/CHANGELOG.md, packages/plugin-pha/src/index.ts, packages/plugin-pha/src/manifestHelpers.ts
=> feat: support configure for resource_prefetch

packages/ice/src/service/analyze.ts
=> fix: dev process exit when error occurs

packages/ice/src/createService.ts, packages/ice/src/plugins/web/index.ts, packages/ice/src/service/runtimeGenerator.ts, packages/ice/src/types/generator.ts, packages/ice/templates/core/index.ts.ejs, packages/webpack-config/src/types.ts
close https://github.com/alibaba/ice/issues/5902
How to use:
```js
generator.addExport({
specifier: [
'Meta',
'Title',
'Links',
'Scripts',
'Data',
'Main',
],
source: '@weex/xxx',
target: 'weex',
});
```
=> feat: suport documentImport

packages/plugin-pha/CHANGELOG.md, packages/plugin-pha/src/index.ts
=> chore: preload should be false default

.github/workflows/version.yml
https://github.com/alibaba/ice/actions/runs/4191962623/jobs/7266960592
=> chore: add changeset commit version

packages/ice/src/createService.ts, packages/ice/src/plugins/web/index.ts, packages/ice/src/service/runtimeGenerator.ts, packages/ice/src/types/generator.ts, packages/ice/src/types/plugin.ts, packages/ice/tests/generator.test.ts, packages/runtime/src/Document.tsx, packages/runtime/src/index.ts
=> feat: add type for runtime

.changeset/flat-poets-dream.md, packages/plugin-pha/src/phaMiddleware.ts
close https://github.com/alibaba/ice/issues/5938
=> fix: dev manifest should work when manifest has not tabbar

.changeset/gentle-teachers-cheer.md, packages/plugin-fusion/src/index.ts
=> fix: compile non-js file when use plugin fusion

.github/workflows/release.yml
Manually create release to the latest version.
=> chore: ci workflow

website/docs/guide/advanced/integrate-from-rax.md
修改 rax-migrate 文档，增加手动需要确认的点的提示。
=> docs: modify docs of rax-migrate

.github/workflows/release.yml, .github/workflows/version.yml
Run `version` script before publish.
=> fix: ci workflow

website/docs/guide/basic/config.md
=> docs: route limit

.github/workflows/release.yml, .github/workflows/version.yml, package.json, pnpm-lock.yaml, scripts/setupUser.ts
Setup GitUser for CLA assignment.
=> chore: setup git user

.changeset/proud-glasses-retire.md, packages/plugin-pha/src/manifestHelpers.ts, packages/plugin-pha/src/types.ts, packages/plugin-pha/tests/manifestHelper.test.ts
close https://github.com/alibaba/ice/issues/5955
=> fix: modify type of config and fix data of prefetch is decamelized

website/docs/guide/advanced/integrate-from-rax.md
=> docs: add appear doc

.changeset/quick-shoes-matter.md, packages/ice/bin/ice-cli.mjs, packages/ice/package.json, pnpm-lock.yaml
=> fix: support unknown cli options registered by plugins

packages/ice/bin/ice-cli.mjs
=> fix: remove dashed keys and using camelcase expansion

package.json, website/docs/guide/basic/config.md
Docs for `server.onDemand` and `routes.config`.
=> chore: docs for new feature

.changeset/new-lamps-argue.md, examples/routes-generate/ice.config.mts, packages/ice/src/routes.ts
=> fix: compatible with dynamic routes when disable lazy import

CONTRIBUTING.md
=> chore: run setup

.changeset/lemon-bats-arrive.md, examples/routes-generate/src/pages/$.tsx, packages/ice/src/utils/generateEntry.ts
=> fix: file name should compat with win32

website/docs/guide/plugins/plugin-dev.md
=> fix: set render doc

.changeset/wet-readers-worry.md, packages/ice/src/createService.ts
close https://github.com/alibaba/ice/issues/6034
```js
dataLoader: {
fetcher: {
packageName: '@ali/universal-mtop',
method: 'request',
},
},
```
=> fix: declarationType of dataLoaderImport should be normal

.changeset/polite-turtles-visit.md, packages/ice/src/service/config.ts, packages/ice/src/service/serverCompiler.ts, packages/ice/src/types/plugin.ts
Set platform node for compile project config
=> fix: set platform node for compile project config

.changeset/good-goats-cover.md, examples/with-data-loader/src/pages/blog1.tsx, examples/with-data-loader/src/pages/blog2.tsx, examples/with-data-loader/src/pages/home.tsx, examples/with-data-loader/src/pages/layout.tsx, packages/runtime/src/dataLoader.ts, packages/runtime/src/routes.tsx, packages/runtime/src/runClientApp.tsx, tests/integration/with-data-loader.test.ts
fix: https://github.com/alibaba/ice/issues/5707
=> fix: data loader error during navigate

.github/workflows/release.yml, .github/workflows/version.yml, .github/workflows/website.yml, package.json, pnpm-lock.yaml
https://github.com/pnpm/pnpm/issues/6213
=> fix: pnpm install deps error

.changeset/tasty-pianos-help.md, packages/plugin-icestark/src/index.ts
=> fix: avoid remount when app mount in other micro app framework

.changeset/moody-otters-cover.md, packages/ice/src/esbuild/removeTopLevelCode.ts, packages/ice/src/service/ServerRunner.ts, packages/ice/src/service/analyze.ts, packages/plugin-rax-compat/src/index.ts
Improve performance by using async function, such as esbuild onLoad https://esbuild.github.io/plugins/#on-load
=> fix: improve performance by using async function

.changeset/nine-rockets-relate.md, packages/ice/src/commands/start.ts, packages/ice/src/middlewares/renderMiddleware.ts, packages/ice/src/middlewares/renderOnDemand.ts
=> fix: static resources should not render

website/docs/guide/advanced/fusion.md
=> docs: plugin fusion

website/docs/guide/basic/appear.md
增加曝光埋点首次 useOnce 的使用示例  
Close #5997  
Close #5996
=> docs: update appear

package.json
=> fix: not build before release beta version

.changeset/young-chairs-dream.md, packages/plugin-icestark/src/index.ts
Props of container passed by is conflict with the render node of ice.js.
=> fix: micro app render in qiankun

website/docs/guide/basic/mock.md
fix demo code error about mockjs
=> fix demo code error

.changeset/metal-tips-drop.md, packages/plugin-pha/src/constants.ts, packages/plugin-pha/src/types.ts, packages/plugin-pha/tests/manifestHelper.test.ts
close https://github.com/alibaba/ice/issues/6060
=> feat: support downgradeUrl

.changeset/weak-cats-rest.md, packages/plugin-pha/src/manifestHelpers.ts, packages/plugin-pha/tests/manifestHelper.test.ts
close https://github.com/alibaba/ice/issues/6153
=> fix: fix frames error with multiple

.changeset/good-baboons-care.md, packages/ice/src/webpack/DataLoaderPlugin.ts
fix https://github.com/alibaba/ice/issues/5877
=> fix: data loader format

website/docs/guide/plugins/plugin-dev.md
Close https://github.com/alibaba/ice/issues/6169
=> docs: fix addWrapper usage

website/docs/guide/plugins/plugin-dev.md
=> docs: optimize plugin dev

.changeset/big-spoons-travel.md
=> fix: minor version of @ice/runtime

.changeset/stale-oranges-hear.md
Add changelog for plugin-store, plugin-icestark and miniapp-runtime
=> chore: add changelog for plugins

packages/ice/scripts/postinstall.mjs, packages/runtime/scripts/postinstall.mjs
Detect beta version if it is satisfied.
=> fix: coerce beta version into semver

.changeset/new-mangos-train.md, packages/runtime/src/Document.tsx
Encode route path to escape xss
=> fix: encode route path to escape xss

packages/appear/CHANGELOG.md, packages/appear/package.json
天马组件版本有冲突，需要新发一个 0.1.5 版本与天马组件版本一致
=> chore: bump appear version

packages/ice/src/routes.ts
=> fix: route specifier is invalid

.changeset/lucky-pans-serve.md, packages/bundles/package.json, pnpm-lock.yaml
Fix #6199
Relate to https://github.com/ice-lab/swc-plugins/pull/13
=> fix: support case of import module with aliased name

.changeset/silly-ladybugs-begin.md, packages/jsx-runtime/src/index.ts
=> fix: style props convert error

packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/runtime/src/runServerApp.tsx
Parsing url path without using URL.
=> hotfix: parsing url path without using URL

packages/runtime/tests/runServerApp.test.tsx
Pass createRoutes for test case
=> fix: test case after merge

.changeset/README.md, .changeset/config.json, package.json
Close: https://github.com/alibaba/ice/issues/6174
目前发布的版本号是 `{version}-{tag}-{commit}-{datetime}`。可查看 https://www.npmjs.com/package/@ice/pkg/v/1.5.7-canary-f9b7572-20230512031148
=> feat: release snapshot version

.changeset/weak-zebras-turn.md, packages/rax-compat/src/possible-standard-names.ts, packages/rax-compat/src/props.ts
针对 rax-compat 的 possibleStandardNames 的改动
1. 增加了 playsInline 以支持 video inline 播放的场景
2. 重构了常量声明, 减少代码量
=> refactor: possible standard properties

package.json
https://github.com/alibaba/ice/actions/runs/4957606330/jobs/8869492830?pr=6148
=> fix: version script not found

packages/webpack-config/src/unPlugins/compilation.ts
Make a copy of keep exports list
=> fix: make a copy of keep exports list

.changeset/lazy-feet-vanish.md, packages/ice/CHANGELOG.md, packages/plugin-pha/CHANGELOG.md, packages/runtime/CHANGELOG.md
=> fix: changelog

website/docs/guide/basic/config.md
对 compileDependencies 增加说明，避免 dev 阶段配置对 build 生效
=> docs: compile deps

.changeset/sharp-pumas-poke.md, packages/runtime/src/runClientApp.tsx
=> fix: use api history to navigate

packages/ice/src/createService.ts, packages/ice/src/service/runtimeGenerator.ts, packages/ice/src/types/generator.ts, packages/ice/src/types/plugin.ts, packages/ice/templates/core/entry.client.tsx.ejs, packages/webpack-config/src/types.ts, packages/webpack-config/src/unPlugins/redirectImport.ts, pnpm-lock.yaml
Support api of addEntryImportAhead
=> feat: support api of addEntryImportAhead

website/docs/guide/basic/config.md
=> docs: add proxy config description

.changeset/long-tomatoes-drum.md, examples/routes-generate/ice.config.mts, examples/routes-generate/src/pages/about.tsx, packages/ice/src/routes.ts
=> fix: import identifier is invalid in route config

.changeset/thin-coins-learn.md, packages/ice/src/createService.ts, packages/runtime/package.json, packages/runtime/src/polyfills/signal.ts
Add default polyfill for signal for unexpected breakchange of react-router upgrade.
=> fix: add default polyfill for signal

packages/runtime/package.json
Add sideEffects config for polyfills otherwise it will be removed.
=> fix: add sideEffects config for polyfills

.changeset/four-roses-confess.md, packages/rax-compat/src/style.ts
=> Hotfix: rax compat style

.changeset/dirty-dogs-clap.md, packages/ice/package.json, packages/runtime/package.json, pnpm-lock.yaml
ref: https://github.com/remix-run/react-router/issues/10469
=> fix: route paths are not match with hash

.changeset/spicy-mice-provide.md, examples/basic-project/ice.config.mts, packages/bundles/src/index.ts, packages/ice/package.json, packages/ice/src/config.ts, packages/ice/src/createService.ts, packages/ice/src/service/runtimeGenerator.ts, packages/ice/src/types/userConfig.ts, packages/ice/src/utils/runtimePolyfill.ts, packages/runtime/package.json, packages/runtime/src/polyfills/abortcontroller.js, packages/runtime/src/polyfills/signal.ts, packages/webpack-config/src/index.ts, packages/webpack-config/src/unPlugins/compilation.ts, pnpm-lock.yaml
Auto polyfill for AbortController (it's not polyfilled by core-js).
=> hotfix: auto polyfill for abortcontroller

.changeset/plenty-horses-develop.md, packages/runtime/src/ClientRouter.tsx, packages/runtime/src/runClientApp.tsx, packages/runtime/src/utils/deprecatedHistory.ts
=> fix: replace history methods by router navigate for backwards compatibility

.changeset/empty-dodos-laugh.md, examples/basic-project/src/pages/index.tsx, packages/runtime/src/ClientOnly.tsx, packages/runtime/src/routes.tsx
- fix：当 serverDataLoader 请求出错时，降级为 CSR
- fix：将 ClientOnly 组件的 fallback 参数调整为 可选的
=> fix: server dataLoader error

.changeset/unlucky-apes-lick.md, packages/ice/package.json, packages/ice/src/commands/build.ts, packages/ice/src/utils/generateEntry.ts, pnpm-lock.yaml
=> fix: support source map for stack traces in node

.changeset/gorgeous-sheep-visit.md, .changeset/poor-tools-develop.md, examples/app-config/package.json, examples/basic-project/package.json, examples/csr-project/package.json, examples/disable-data-loader/package.json, examples/miniapp-project/package.json, examples/rax-inline-style/package.json, examples/rax-project/package.json, examples/with-entry-type/package.json, examples/with-nested-routes/package.json, examples/with-pha/package.json, packages/bundles/package.json, packages/ice/package.json, packages/miniapp-loader/package.json, packages/plugin-miniapp/package.json, packages/plugin-pha/package.json, packages/plugin-rax-compat/package.json, packages/webpack-config/package.json, packages/webpack-config/src/config/splitChunks.ts, packages/webpack-modify/package.json, pnpm-lock.yaml, website/package.json
=> fix: optimize deprecation warning of webpack

.changeset/forty-cheetahs-design.md, packages/ice/templates/core/env.ts.ejs, packages/plugin-pha/src/constants.ts
close https://github.com/alibaba/ice/issues/6295
=> feat: support isPHAAppWorker

.changeset/smart-walls-divide.md, packages/runtime/src/sourcemap.ts
支持 start 阶段未压缩的 js 计算 sourcemap 正确性
=> feat: support weex start sourcemap

.changeset/healthy-lies-approve.md
Add changeset for miniapp packages
=> chore: add changeset

packages/ice/src/constant.ts, packages/ice/src/service/runtimeGenerator.ts, packages/ice/tests/generator.test.ts, packages/runtime/src/index.ts
For backwards compatibility. Relate to #6238
=> fix: deprecated warning for use app context form @ice/runtime

.changeset/dirty-cougars-applaud.md, packages/ice/src/service/runtimeGenerator.ts, packages/ice/templates/core/types.ts.ejs, packages/ice/tests/generator.test.ts
Support the case of type alias used in plugin pha.
=> fix: alias for type declaration

.changeset/curvy-spies-grab.md, packages/ice/src/types/userConfig.ts
=> chore: add user config comments

.changeset/bright-poets-bathe.md, packages/ice/src/esbuild/transformPipe.ts
=> fix: relative id in pipe transform

.changeset/four-gifts-remain.md, .changeset/red-llamas-trade.md, packages/ice/src/commands/build.ts, packages/ice/src/config.ts, packages/ice/src/types/userConfig.ts, packages/plugin-pha/src/manifestHelpers.ts, website/docs/guide/basic/config.md
=> feat: support user config htmlGenerating

packages/ice/src/config.ts, packages/ice/src/types/userConfig.ts, website/docs/guide/basic/config.md
resolve https://github.com/alibaba/ice/issues/6353
=> feat: enhance dropLogLevel build config

.changeset/funny-dolphins-hope.md, packages/plugin-pha/src/manifestHelpers.ts, packages/plugin-pha/tests/manifestHelper.test.ts
问题的原因是之前 @chenjun1011  加异步 dataLoader 的时候修改了数据结构，增加了 loader 以及 options 的一层结构。
close https://github.com/alibaba/ice/issues/6364
=> fix: format of dataLoaderConfig loader changed

.changeset/rotten-hats-mate.md, examples/memory-router/ice.config.mts, packages/ice/src/createService.ts, packages/ice/src/types/userConfig.ts, packages/webpack-config/src/config/splitChunks.ts, packages/webpack-config/src/types.ts, website/docs/guide/basic/config.md
Support code splitting strategy of page-vendors.
=> feat: support code splitting strategy of page-vendors

.changeset/sharp-frogs-live.md, packages/plugin-rax-compat/src/index.ts
=> Support inline style filter

.changeset/green-cats-fold.md, packages/runtime/src/reportRecoverableError.ts, packages/runtime/src/runClientApp.tsx, packages/runtime/src/types.ts
=> feat: report detail recoverable error

.changeset/afraid-forks-cheer.md, packages/plugin-pha/src/constants.ts, packages/plugin-pha/src/types.ts
close https://github.com/alibaba/ice/issues/6419
=> fix(plugin-pha): add bounces attr

.changeset/tender-feet-yell.md, examples/rax-inline-style/src/components/InlineLess/index.tsx, examples/rax-inline-style/src/components/InlineLess/x.less, examples/rax-inline-style/src/components/InlineLess/x.module.less, examples/rax-inline-style/src/pages/index.jsx, packages/plugin-rax-compat/src/index.ts
=> hotfix: inline style with less

.changeset/long-lamps-bow.md, packages/cache-canvas/package.json, packages/cache-canvas/src/index.tsx
=> fix: fix native back

.changeset/empty-penguins-give.md, examples/with-antd/ice.config.mts, packages/ice/src/service/Runner.ts
=> fix: compatible with Win32 when enable onDemand compile

.changeset/healthy-cameras-lick.md, packages/plugin-cavans/package.json, pnpm-lock.yaml
=> chore: remove runtime

.changeset/quick-turtles-pretend.md, packages/ice/src/middlewares/renderMiddleware.ts
Fix bug of ignore static rule.
=> fix: ignore static resource when render server entry

.changeset/rich-pets-warn.md, packages/rspack-config/src/splitChunks.ts, tests/integration/app-config.test.ts, tests/utils/build.ts
Compatible with win32 in speedup mode.
Fix #6491
=> fix: compatible with win32 in speedup mode

.changeset/large-bobcats-count.md, packages/bundles/package.json, pnpm-lock.yaml
Bump @swc/core version for minify bugs.
=> chore: bump @swc/core version

.changeset/hot-pants-type.md, examples/with-store/src/store.ts, packages/ice/templates/core/entry.server.ts.ejs, packages/runtime/src/Document.tsx, packages/runtime/src/runServerApp.tsx
A solution for #6485
Fix: #6422
Relate task: document will be compile separate form server bundle.
=> fix: unnecessary to import runtime module and routes when csr

.changeset/honest-dancers-move.md, packages/ice/src/bundler/rspack/build.ts, packages/ice/src/bundler/webpack/build.ts
Throw error when server compile failed
=> fix: throw error when server compile failed

examples/with-rsc/ice.config.mts, examples/with-rsc/package.json, packages/bundles/package.json, packages/bundles/scripts/tasks.ts, packages/ice/package.json, packages/ice/src/bundler/webpack/getWebpackConfig.ts, packages/ice/src/config.ts, packages/ice/src/createService.ts, packages/ice/src/plugins/web/config.ts, packages/ice/src/plugins/web/task.ts, packages/ice/src/service/serverCompiler.ts, packages/ice/src/types/userConfig.ts, packages/ice/src/webpack/ServerCompilerPlugin.ts, packages/ice/templates/core/entry.server.ts.ejs, packages/runtime/package.json, packages/runtime/src/routes.tsx, packages/runtime/src/runRSCApp.tsx, packages/runtime/src/runServerApp.tsx, packages/shared-config/src/types.ts, packages/webpack-config/src/index.ts, pnpm-lock.yaml
- react
- react-dom
- react-server-dom-webpack
=> feat: bundle canary version of react

.changeset/five-garlics-live.md, packages/ice/src/bundler/rspack/build.ts, packages/ice/src/bundler/rspack/index.ts, packages/ice/src/bundler/rspack/start.ts, packages/ice/src/bundler/webpack/build.ts, packages/ice/src/bundler/webpack/index.ts, packages/ice/src/bundler/webpack/start.ts
=> fix: params urls for hook before.start.run

.changeset/empty-ads-sleep.md, packages/ice/src/createService.ts, packages/ice/templates/core/entry.client.tsx.ejs, packages/ice/templates/core/entry.server.ts.ejs, packages/ice/templates/exports/data-loader.ts.ejs, packages/runtime/src/runServerApp.tsx
兼容没有 document.tsx 的情况
weex 下使用加上 htmlGenerating: false,
=> feat: compat no document

.changeset/twenty-pens-remain.md, packages/plugin-stream-error/README.md, packages/plugin-stream-error/package.json, packages/plugin-stream-error/src/index.ts, packages/plugin-stream-error/tsconfig.json, pnpm-lock.yaml
New plugin deal with stream error.
If stream error occured, app will fallback to CSR mode.
=> feat: new plugin deal with stream error

.changeset/wet-cameras-swim.md, packages/ice/src/createService.ts
close https://github.com/alibaba/ice/issues/6543
=> fix: hasDocument should check jsx

.changeset/long-mayflies-smoke.md, examples/csr-project/ice.config.mts, packages/ice/src/service/ServerRunner.ts
Deal with json file when use on-demand compile.
=> fix: deal with json file when use on-demand compile

.changeset/sharp-trees-hammer.md, examples/basic-project/src/app.tsx, packages/ice/templates/core/index.ts.ejs, packages/ice/templates/core/type-defines.ts.ejs
Add type definition of runApp.
=> feat: add type definition of runApp

.changeset/slimy-oranges-peel.md, packages/ice/templates/core/entry.client.tsx.ejs
=> fix: return render root in case of plugin may depend on it

.changeset/cool-comics-confess.md, .changeset/fresh-rings-help.md, packages/plugin-fusion/src/index.ts
=> fix: compatible with win32 when config themePackage

packages/create-app-shared/package.json, packages/create-app-shared/src/router.ts, packages/create-app-shared/src/web/initAppLifeCycles.ts
1. 初始值从 document.visibilityState 获取
2. 每次 visibilitychange, 都从 document.visibilityState 获取新值
=> Fix visibility change 

package.json, packages/create-app-shared/CHANGELOG.md, packages/create-app-shared/package.json, packages/create-app-shared/src/router.ts, packages/create-app-shared/src/runtimeModule.ts
1. 修复在 SSR 环境下执行的时候, document  is not defined 的问题, 这种情况下恢复至 1.3.0 版本的状态
=> fix: support SSR for document.visibilityState

.changeset/clever-rules-try.md, packages/ice/src/bundler/rspack/getConfig.ts, packages/ice/src/bundler/rspack/index.ts, packages/rspack-config/src/index.ts, packages/shared-config/src/types.ts, packages/webpack-config/src/index.ts
=> fix: compatible with plugin API configureWebpack in speedup mode

.changeset/early-rings-develop.md, packages/ice/src/service/onDemandPreBundle.ts, packages/ice/src/service/preBundleDeps.ts, packages/ice/src/service/serverCompiler.ts
=> fix: do not prebundle node built-in module

.changeset/empty-islands-unite.md
Update release type to `patch` in #6590
=> Use patch for plugin rax compat

packages/plugin-store/CHANGELOG.md, packages/plugin-store/src/generator.ts
For example:
`import hello-worldLayout from "xxx/hello-world/Layout";`, now it is `import HelloWorldLayout from "xxx/hello-world/Layout"`
=> fix(plugin-store): convert kebab-case to PascalCase

packages/plugin-store/CHANGELOG.md, packages/plugin-store/package.json
Ref: https://github.com/alibaba/ice/pull/6188
=> chore: update plugin-store version and changelog

.changeset/nice-vans-float.md, packages/runtime/src/Document.tsx, packages/runtime/src/runServerApp.tsx, packages/runtime/src/server/streamRender.tsx
=> feat: support pre render ssr

packages/ice/src/middlewares/renderMiddleware.ts, packages/runtime/src/runServerApp.tsx, packages/runtime/src/server/streamRender.tsx
服务端预渲染场景下，allReady 以后再去 pipe 流
=> feat: support preRender

.changeset/cold-timers-hug.md, .changeset/fluffy-onions-travel.md, packages/bundles/package.json, packages/bundles/src/plugin-refresh.ts, packages/ice/src/bundler/rspack/getConfig.ts, packages/ice/src/esbuild/assets.ts, packages/rspack-config/src/index.ts, packages/shared-config/src/getAlias.ts, packages/shared-config/src/index.ts, packages/webpack-config/src/index.ts, pnpm-lock.yaml
=> fix: several bug when bump pack dependencies 

.changeset/perfect-cows-pretend.md, packages/ice/src/service/ServerRunner.ts, packages/ice/src/service/serverCompiler.ts
Add assets plugin for pre bundle thrid-party dependencies
Fix: #6683
=> fix: add assets plugin for pre bundle thrid-party dependencies

packages/ice/bin/ice-cli.mjs
Fixes errors reported by eslint
=> fix: fix eslint problem

.changeset/tender-lamps-marry.md, examples/with-keep-alive/README.md, examples/with-keep-alive/package.json, packages/runtime/src/KeepAliveOutlet.tsx, website/docs/guide/advanced/keep-alive.md
https://github.com/facebook/react/pull/27640
=> fix: unstable_Offscreen to unstable_Activity

packages/bundles/override/rspack/adapter.js, packages/bundles/override/rspack/defaults.js, packages/bundles/override/rspack/normalization.js, packages/bundles/override/rspack/zod.js, packages/bundles/package.json, packages/ice/package.json, packages/rspack-config/package.json, pnpm-lock.yaml
Bump the @rspack/core version to 0.4.3
=> fix: bump the version of rspack

packages/react-app-renderer/CHANGELOG.md, packages/react-app-renderer/package.json
Lock the depencencies version of `@loadable/component` to 5.15.3
=> fix: lock @loadable/component version

packages/ice/src/createService.ts
=> fix: register with new defaultTaskConfig evey time

.changeset/two-ducks-rush.md, packages/ice/src/createService.ts, packages/ice/src/service/Runner.ts
=> Fix: on demand server cache

.changeset/violet-rabbits-cheer.md, packages/ice/src/plugins/task.ts, packages/ice/tests/defineJestConfig.test.ts, packages/ice/tests/defineVitestConfig.test.ts
=> Fix: resolve path of regenerator-runtime

.changeset/chatty-students-fix.md, packages/shared-config/src/unPlugins/compilation.ts
=> Fix: disable swcrc by default

.changeset/tidy-falcons-tickle.md, packages/plugin-unocss/src/index.ts
Always add preset uno for plugin.
=> Fix: always add preset uno for plugin

.changeset/old-toes-itch.md, packages/runtime/src/dataLoader.ts, packages/runtime/src/requestContext.ts, packages/runtime/src/routes.tsx
=> Fix: pass the correct request context to data loader

.changeset/shaggy-flies-scream.md, packages/rspack-config/src/index.ts
Set enforce post for compilation loader.
=> Fix: set enforce post for compilation loader

.changeset/funny-apes-clap.md, examples/single-route/src/pages/layout.tsx, packages/runtime/src/ClientRouter.tsx, packages/runtime/src/routes.tsx, packages/runtime/src/runClientApp.tsx, packages/runtime/src/runServerApp.tsx, packages/runtime/src/singleRouter.tsx, packages/runtime/tests/singleRoute.test.tsx
Enhance single router mode without react-router.
=> Feat: enhance single router mode without react-router

.changeset/light-beds-vanish.md, packages/bundles/scripts/tasks.ts
Fix HMR boundary in speedup mode.
=> Fix: HMR boundary in speedup mode

.changeset/selfish-suns-design.md, packages/runtime/src/index.ts
=> Fix: export losing ts type

.changeset/warm-wombats-taste.md, packages/ice/package.json, packages/ice/src/constant.ts, packages/plugin-i18n/package.json, packages/plugin-pha/package.json, packages/runtime/package.json, packages/runtime/src/index.ts, packages/runtime/src/router.ts, packages/runtime/src/singleRouter.tsx, pnpm-lock.yaml
=> Feat: update react-router for new feature

.changeset/serious-cows-explain.md, packages/bundles/package.json, pnpm-lock.yaml
Fix css module hash is not match.
=> Fix: css module hash is not match

packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/runtime/src/singleRouter.tsx
Compatible when undefined basename.
=> fix: compatible when undefined basename

package.json, packages/bundles/package.json, packages/ice/package.json, packages/rspack-config/package.json, packages/rspack-config/src/index.ts, patches/@rspack__core@0.5.4.patch, pnpm-lock.yaml
=> Fix: update rspack version

.changeset/lovely-pans-arrive.md
=> chore: add changelog

packages/cache-canvas/src/storage.tsx
=> fix: bug fixed

packages/bundles/scripts/tasks.ts
Replace pre-bundle package path.
=> fix: replace pre-bundle package path

packages/bundles/scripts/tasks.ts
Fix compile script for dev-server.
=> Fix: compile script for dev-server

website/config/sidebars.js
Remove sidebar config of miniapp.
=> docs: remove sidebar config of miniapp

packages/icejs/package.json, packages/plugin-store/CHANGELOG.md, packages/plugin-store/package.json, packages/plugin-store/src/babelPluginReplacePath.ts
closed https://github.com/alibaba/ice/issues/6686
=> feat: match page paths

packages/icejs/package.json, packages/plugin-store/CHANGELOG.md, packages/plugin-store/package.json, packages/plugin-store/src/vitePluginPageRedirect.ts
Closed: https://github.com/alibaba/ice/issues/6812
=> fix: store-error-in-vite-mode

.changeset/shy-monkeys-scream.md, packages/ice/src/service/config.ts
=> Fix: app config compile error of env exports

.changeset/olive-wolves-dress.md, packages/ice/bin/ice-cli.mjs, packages/ice/src/config.ts, packages/ice/src/createService.ts
Support add plugin by cli option.
```bash
ice start --plugin custom-plugin
```
=> Feat: support add plugin by cli option

README.md
=> chore: add open with opensumi badge

packages/runtime/src/routes.tsx
Optimize loader code of route.
=> Fix: optimize loader function of route

.changeset/tricky-cheetahs-mate.md, packages/webpack-config/src/index.ts
SWC minify will cause runtime error if set mangle.safari10
=> Fix: minify config of swc

.changeset/red-ducks-look.md, packages/runtime/src/singleRouter.tsx
Add mismatch warning for single route mode.
=> Fix: mismatch warning for single route mode

.changeset/chatty-masks-join.md, .changeset/real-knives-nail.md, packages/plugin-rax-compat/src/services/jsx.ts, packages/shared-config/src/types.ts, packages/shared-config/src/unPlugins/compilation.ts
Pass options for function type of `compilationConfig`.
=> Feat: support options for compilationConfig

.changeset/big-taxis-brush.md
=> chore: add changset for plugin-request

.changeset/odd-avocados-decide.md, packages/ice/bin/ice-cli.mjs, packages/ice/src/bundler/config/getUrls.ts, packages/ice/src/bundler/rspack/start.ts, packages/ice/src/bundler/webpack/start.ts, packages/ice/src/config.ts, packages/ice/src/plugins/web/index.ts, packages/ice/src/types/plugin.ts
Close #6865 and support open specified route.
=> feat: support open specified route and list all avaiable routes

.changeset/shaggy-cherries-fail.md, examples/app-config/ice.config.mts, examples/app-config/package.json, packages/plugin-externals/CHANGELOG.md, packages/plugin-externals/README.md, packages/plugin-externals/package.json, packages/plugin-externals/src/index.ts, packages/plugin-externals/src/webpack-plugin.ts, packages/plugin-externals/tsconfig.json, packages/runtime/src/Document.tsx, pnpm-lock.yaml
New plugin for external dependencies mush easier in CSR.
=> feat: externals plugin for external dependencies mush easier

website/docs/guide/basic/document.md
Update the demo code of customize script
=> docs: update the demo code of customize script

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/version.yml, .github/workflows/website.yml
Update ci action version of pnpm.
=> Chore: update ci action of pnpm

.changeset/unlucky-boats-type.md, packages/runtime/src/routes.tsx, packages/runtime/tests/routes.test.tsx
Throw error for better debugging.
=> Fix: throw error for better debugging

website/docs/guide/about.md
=> docs: update the links which has expired

packages/plugin-request/src/hooks.ts
修复useRequest导出的request类型错误，类型和ahooks useRequest run保持一致
=> fix: fix use request type error, adjust type definition for consistency.

.changeset/curvy-ways-sleep.md, packages/rspack-config/src/index.ts
Align copy plugin with webpack mode.
=> Fix: align copy plugin with webpack mode

.changeset/pink-panthers-call.md, packages/ice/src/service/ServerRunner.ts
=> Fix: modify meta.renderer in server runner

packages/icejs/package.json, packages/plugin-ice-ssr/CHANGELOG.md, packages/plugin-ice-ssr/package.json, packages/plugin-icestark/CHANGELOG.md, packages/plugin-icestark/package.json, packages/vite-service/CHANGELOG.md, packages/vite-service/package.json, scripts/getPackageInfos.ts, yarn.lock
=> Chore: lock the version of cheerio

packages/plugin-stream-error/CHANGELOG.md, packages/plugin-stream-error/package.json, packages/plugin-stream-error/src/components/headStreamErrorRecoverScript.tsx, packages/plugin-stream-error/src/components/index.tsx, packages/plugin-stream-error/src/index.tsx
support head stream error recover script component
=> feat: export head stream err recover script component

packages/plugin-stream-error/src/components/headStreamErrorRecoverScript.tsx
=> Chore: lint fix

.changeset/calm-cobras-smoke.md, packages/runtime/src/runServerApp.tsx, packages/runtime/src/server/streamRender.tsx, packages/runtime/src/types.ts
close https://github.com/alibaba/ice/issues/6977
=> feat: support getAssets for onShellReady

.changeset/curvy-jars-watch.md, packages/runtime/src/Suspense.tsx
=> revert: revert suspence event

.changeset/sharp-lemons-dress.md, packages/bundles/package.json, pnpm-lock.yaml
Add support for linux-arm64. Fix #6872
=> Feat: support more platforms

packages/bundles/package.json, pnpm-lock.yaml, tests/utils/browser.ts
https://github.com/alibaba/ice/issues/7049
=> fix: update es-module-lexer

.changeset/gorgeous-dogs-look.md, .changeset/little-tigers-doubt.md, examples/with-suspense-ssr/src/pages/index.tsx, packages/runtime/src/Suspense.tsx
* make suspense event id more robust.
* add missing change set.
=> feat: change suspense event id

packages/ice/src/service/config.ts, packages/ice/src/service/serverCompiler.ts, packages/ice/src/types/plugin.ts
=> fix: config use esbuild

.changeset/tame-planets-rush.md, packages/ice/src/service/serverCompiler.ts
=> fix: jsxplugs transform

.changeset/fast-falcons-serve.md, packages/appear/src/weex/index.tsx
=> fix: fix appear event handler callback refs in WeexAppear component

packages/plugin-stream-error/CHANGELOG.md, packages/plugin-stream-error/package.json, packages/plugin-stream-error/src/index.tsx
Support option rootId to empty root
=> feat: support option rootId to empty root

.changeset/silver-foxes-run.md, packages/ice/templates/core/env.ts.ejs
1. 249e2cf3 (chore: add changeset)
- 新增了changeset文件 .changeset/silver-foxes-run.md
- 用于记录版本变更信息
2. 3b507d3c (refactor: add env for themis, delete PHA/Kraken, simplize WindVane)
- 修改了 packages/ice/templates/core/env.ts.ejs
- 为themis添加了环境配置
- 删除了PHA/Kraken相关代码
- 简化了WindVane的实现
- 净减少3行代码（4行增加，7行删除）
=> 重构内置 env.ts 实现

packages/ice/CHANGELOG.md, packages/ice/package.json, packages/ice/templates/core/env.ts.ejs
This pull request introduces a hotfix to the `@ice/app` package, adding backward compatibility for specific runtime environments and updating the package version. The key changes include updates to environment variables and metadata.
=> hotfix: add isPHA and isKraken env for backward compatibility
