alibaba/ice

- scaffords/ice-design-lite/.eslintrc
- scaffords/ice-design-pro/.eslintignore
- scaffords/ice-design-pro/.eslintrc
fix #74 
env 增加 "mocha": true 是因为后边我们会增加单测
.eslintignore 不应该忽略任何 src 的文件
> fix: eslint config for scaffords

- scaffolds/ice-design-cms/.gitignore
发现就 cms 这个模板里面没有 .gitignore， 自己创建了项目一般会直接 git init 和 git add . （发现多加了好多多余内容），然后看其他模板都有这个 .gitignore ,遂感觉可以直接复制过来就可以用
> 添加.gitignore

- blocks/MonacoEditor/demo/index.js
- blocks/MonacoEditor/src/MonacoEditor.jsx
因为 require loader 被加载了多次, 后边我想是不是得把这个做成 iframe, 完全隔离环境, 但是这样复杂度又会提升   
我实际使用是放在iframe里面的
> fix: monaco editor failed then load second time

- tools/ice-scripts/lib/config/getEntry.js
- tools/ice-scripts/lib/config/getEntryByPages.js
- tools/ice-scripts/lib/config/getPlugins.js
- tools/ice-scripts/lib/config/getProxyConfig.js
- tools/ice-scripts/lib/config/getRules.js
- tools/ice-scripts/lib/config/getUserConfig.js
- tools/ice-scripts/lib/config/paths.js
- tools/ice-scripts/lib/utils/validationSassAvailable.js
- tools/ice-scripts/package.json
Close https://github.com/alibaba/ice/issues/738  
webpack 构建设置 `publicPath: './'` 将资源离线化，css 中的相对资源由 loader 处理。
```js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
module.exports = {
plugins: [
new MiniCssExtractPlugin({
// Options similar to the same options in webpackOptions.output
// both options are optional
filename: "[name].css",
chunkFilename: "[id].css"
})
],
module: {
rules: [
{
test: /\.css$/,
use: [
{
loader: MiniCssExtractPlugin.loader,
options: {
// you can specify a publicPath here
// by default it use publicPath in webpackOptions.output
publicPath: '../'
}
},
"css-loader"
]
}
]
}
}
```
https://github.com/webpack-contrib/mini-css-extract-plugin#minimal-example
> fix: css images relative path

- vue-materials/scaffolds/d2-admin-ice/vue.config.js
设置 `baseUrl = '/'` 解决使用客户端启动项目时点击 GUI 上的预览地址无效（必须访问终端里生成的地址）问题
> default baseUrl

- react-materials/scaffolds/ice-coreui-admin/config-overrides.js
- react-materials/scaffolds/ice-coreui-admin/package.json
- react-materials/scaffolds/ice-creative-dashboard/config-overrides.js
- react-materials/scaffolds/ice-creative-dashboard/package.json
- react-materials/scaffolds/ice-light-bootstrap-dashboard/config-overrides.js
- react-materials/scaffolds/ice-light-bootstrap-dashboard/package.json
- react-materials/scaffolds/ice-material-dashboard/config-overrides.js
- react-materials/scaffolds/ice-material-dashboard/package.json
**修复 react-scripts 构建器不支持 ES7 decorator 的问题**
1. 通过 react-app-rewired 的 injectBabelPlugin 接口配置 `transform-decorators-legacy`
2. 对模板描述进行补充，说明是使用 react-scripts 作为构建器
3. 对模板进行分类区分，四个社区引入的模板都归类于 Dashboard 类
不建议将该类模板改为使用 ice-scripts 作为构建器，理由是，对 Iceworks 来说，是一个通用的接入方式，只需要满足 package.json 的 scripts 里有 `npm run start` 和 `npm run build` 即可，另外用户也可以自定义接入模板，也不一定使用 ice-scripts 作为构建器。
> fix: support es7 decorators

- tools/ice-scripts/lib/config/getUserConfig.js
- 解决问题：用户在 .webpack.rc.js 里使用 webpack 时（webpack.DefinePlugin）需要在项目里依赖一个 webpack，这个 webpack 跟 ice-scripts 的 webpack 版本可能会冲突导致构建出错，因此通过 function 的方式将内置的 webpack 透传给用户，保证只有一个 webpack 版本
- 文档下周在统一的工程文档上一起加
- 使用：
```js
// .wepackrc.js
module.exports = (context) => {
const { webpack } = context;
return {
plugins: [
new webpack.DefinePlugin({
ASSETS_VERSION: '0.0.1',
    })
  ]
}
};
```
> feat: webpackrc 支持导出 function 并透传给用户一些上下文

- tools/ice-scripts/CHANGELOG.md
- tools/ice-scripts/lib/config/getPlugins.js
- tools/ice-scripts/lib/config/getRules.js
- tools/ice-scripts/lib/config/webpack.config.basic.js
- tools/ice-scripts/lib/dev.js
- tools/ice-scripts/package.json
- tools/ice-skin-loader/README.md
- tools/ice-skin-loader/lib/createSkinExtraContent.js
- tools/ice-skin-loader/lib/generateVarsByThemeConfig.js
- tools/ice-skin-loader/lib/index.js
- tools/ice-skin-loader/package.json
- 不删除 `import variables.scss` 语句，不确定之前为什么这么做，事实上是有副作用的，比如主题包里的变量不全
- 取代 css-prefix-plugin 的功能，发布后删除 css-prefix 这个包
- 将配置从 buildConfig 移到 themeConfig 打脸x1
- 考虑到需要结合 configProvider，用户还是得自定义 prefix，所以讲原先的 bool 改回 string，打脸x2
- themeConfig 由 ice-scripts 传入，loader 自己读文件不合理
- 修复没有 theme 就不进 skin-loader 的 bug
- 代码重构&补充文档
- ice-scripts 1.7.9 -> 1.8.0
- ice-skin-loader 0.1.0 -> 0.2.0
> fix: 修复删除 variables.scss 后变量不存在问题

- tools/ice-scripts/bin/ice-build.js
- tools/ice-scripts/lib/config/webpack.config.prod.js
前端监控系统在线上js报错后往往需要sourcemap文件用来精确定位错误。
但是发现ice build中的devtool被写死成none
现希望能放开该配置项
> feat: ice-scripts build support sourcemap

- react-materials/scaffolds/ice-creator-admin/package.json
- react-materials/scaffolds/ice-creator-admin/src/components/NotFound/NotFound.scss
- react-materials/scaffolds/ice-creator-admin/src/index.js
- react-materials/scaffolds/ice-creator-admin/src/layouts/BasicLayout/components/Aside/index.jsx
- react-materials/scaffolds/ice-creator-admin/src/layouts/BasicLayout/components/Aside/index.module.scss
- react-materials/scaffolds/ice-creator-admin/src/layouts/BasicLayout/components/Header/index.jsx
- react-materials/scaffolds/ice-creator-admin/src/layouts/BasicLayout/components/Header/index.scss
- react-materials/scaffolds/ice-creator-admin/src/layouts/BasicLayout/components/Logo/index.js
- react-materials/scaffolds/ice-creator-admin/src/layouts/BasicLayout/components/Logo/index.module.scss
- react-materials/scaffolds/ice-creator-admin/src/layouts/BasicLayout/index.js
- react-materials/scaffolds/ice-creator-admin/src/layouts/BasicLayout/index.module.scss
- react-materials/scaffolds/ice-creator-admin/src/layouts/UserLayout/index.scss
- react-materials/scaffolds/ice-creator-admin/src/pages/Dashboard/components/NoticeList/NoticeList.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/Dashboard/components/UserLanding/UserLanding.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/Dashboard/components/UserLanding/index.module.scss
- react-materials/scaffolds/ice-creator-admin/src/pages/HotPost/components/HotPostRank/HotPostRank.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/HotPost/components/HotRank/HotItem.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/HotPost/components/HotRank/HotRank.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/HotPost/components/OverviewChart/OverviewChart.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/NewPost/components/NewPostForm/index.js
- react-materials/scaffolds/ice-creator-admin/src/pages/PostList/components/PostCategory/PostCategory.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/PostList/components/PostCategory/index.module.scss
- react-materials/scaffolds/ice-creator-admin/src/pages/Settings/components/AccountPanel/AccountPanel.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/Status/components/AccountBadge/BadgeItem.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/Status/components/AccountFeatures/FeatureItem.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/Status/components/AccountStatus/StateItem.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/UserLogin/UserLogin.jsx
- react-materials/scaffolds/ice-creator-admin/src/pages/UserRegister/UserRegister.jsx
upgrade ice-creator-admin to @alifd/next
> upgrade ice-creator-admin to @alifd/next

- react-materials/scaffolds/ice-library-management-admin/package.json
- react-materials/scaffolds/ice-library-management-admin/src/components/ContainerTitle/ContainerTitle.jsx
- react-materials/scaffolds/ice-library-management-admin/src/index.js
- react-materials/scaffolds/ice-library-management-admin/src/layouts/BasicLayout/components/Aside/Aside.jsx
- react-materials/scaffolds/ice-library-management-admin/src/layouts/BasicLayout/components/Aside/Aside.scss
- react-materials/scaffolds/ice-library-management-admin/src/layouts/BasicLayout/components/Footer/Footer.jsx
- react-materials/scaffolds/ice-library-management-admin/src/layouts/BasicLayout/components/Header/Header.jsx
- react-materials/scaffolds/ice-library-management-admin/src/layouts/BasicLayout/components/Header/Header.scss
- react-materials/scaffolds/ice-library-management-admin/src/layouts/UserLayout/UserLayout.scss
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibBorrow/components/BorrowForm/index.js
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibDonation/components/DonationForm/index.js
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibManagement/components/LibTable/BorrowTable.jsx
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibManagement/components/LibTable/BorrowTableFilter.jsx
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibManagement/components/LibTable/CustomTable.jsx
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibManagement/components/LibTable/LibTable.jsx
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibManagement/components/LibTable/LibTable.module.scss
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibManagement/components/LibTable/TableFilter.jsx
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibManagement/components/LibTable/index.js
- react-materials/scaffolds/ice-library-management-admin/src/pages/LibRecommend/components/RecommendForm/index.js
- react-materials/scaffolds/ice-library-management-admin/src/pages/UserLogin/UserLogin.jsx
- react-materials/scaffolds/ice-library-management-admin/src/pages/UserRegister/UserRegister.jsx
upgrade ice-library-management-admin to fusion design
> upgrade ice-library-management-admin to fusion design

- docs/about.md
> docs: update qrcode

- tools/ice-scripts/CHANGELOG.md
- tools/ice-scripts/lib/config/getRules.js
- tools/ice-scripts/lib/config/webpack.config.prod.js
- tools/ice-scripts/package.json
修复默认开启 UglifyJsPlugin sourceMap 引起的内存溢出问题，更新为默认关闭 sourceMap
> fix: turn off source maps by default

- tools/ice-devtools/CHANGELOG.md
- tools/ice-devtools/lib/screenshot.js
- tools/ice-devtools/package.json
fix https://github.com/imagemin/imagemin-pngquant/issues/46
> fix: imagemin-pngquant install error

- react-materials/scaffolds/ice-design-pro/src/pages/GeneralTable/components/CustomForm/CustomForm.jsx
input 为了支持ie9 使用的是table布局，所以配合的FormItem 也没有用 flex 布局。如果自己写布局要注意这个点。
> fix: safari 下 input 不能直接被flex布局包裹

- react-materials/components/balloon-confirm/package.json
- react-materials/components/container/package.json
- react-materials/components/data-binder/package.json
- react-materials/components/dynamic-icon/package.json
- react-materials/components/ellipsis/package.json
- react-materials/components/form-binder/package.json
- react-materials/components/foundation-symbol/package.json
- react-materials/components/img/package.json
- react-materials/components/img/src/index.js
- react-materials/components/label/package.json
- react-materials/components/label/src/index.js
- react-materials/components/layout/package.json
- react-materials/components/notification/package.json
- react-materials/components/notification/src/index.js
- react-materials/components/panel/package.json
- react-materials/components/panel/src/index.js
- react-materials/components/qrcode/package.json
- react-materials/components/styled-menu/package.json
- react-materials/components/title/package.json
- react-materials/components/title/src/index.js
- 修复 `@alifd/next` 依赖构建错误问题（感觉是因为 ice-devtools@1.x 没支持 `@alifd/next`?），此部分需要重新发版本
- 所有组件增加 react+react-dom 的 dev 依赖，不需要发版本
- 改变 `export default from` 语法，ice-devtools@2.x 为什么不支持这个语法正在排查，这部分不需要法版本
> fix: 依赖 next 的组件重新构建发版&增加react&react-dom的dev依赖&修复部分组件 export 语法

- tools/ice-scripts/lib/config/getPlugins.js
- tools/ice-scripts/lib/plugins/append-style-webpack-plugin.js
- 修复未编译&追加主题包 icons.scss 问题 https://github.com/alibaba/ice/issues/1478 https://github.com/alibaba/ice/issues/1546
- 兼容 1.x 主题包 icons.scss 使用了 css-prefix 变量但未定义问题
- 编译 icons.scss 支持 `themeConfig.css-prefix`
> fix: 主题包 icons.scss 引入失败问题

- tools/ice-scripts/lib/config/getBabelConfig.js
- tools/ice-scripts/lib/config/getRules.js
- 支持 buildConfig.babelExclude
- 某个依赖包需要 babel 编译（不同 npm 路径可能不同）：babelExclude: "node_modules\\/(?!_@ali_lib-ucc)"
- node_modules 都需要编译：babelExclude: "bower_components"，随便配置一个奇怪的地址覆盖默认值即可
- 支持 babelPluginImportConfig，比如：
```
// 支持数组
"babelPluginImportConfig": {
"libraryName": "antd",
"libraryDirectory": "es",
"style": true
}
```
> Feat support babel config

- docs/advanced/webpackrc.md
- tools/ice-scripts/CHANGELOG.md
- tools/ice-scripts/lib/config/getPlugins.js
- tools/ice-scripts/package.json
1. 没有使用时间组件的不应该打包 momentjs
2. 使用了时间组件也不应该全量打包 momentjs 的所有 locale
1. 没有使用时间组件的模板去掉 moment 依赖，只有在使用时用户按需添加，这个体验能接受，用户可以 CDN 或者本地构建的方式，比较自由，另外组件层面也给出了提示
2. 通过配置 `new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)` 插件可支持按需加载
**之前：**
**现在：**
> feat: optimize monentjs with webpack

- tools/ice-scripts/CHANGELOG.md
- tools/ice-scripts/lib/config/getResolveAlias.js
- tools/ice-scripts/package.json
- npm 扁平化之后 @babel/runtime 跟 ice-scripts 同级，于是去 ice-scripts 的 node_modules 下找不到 @babel/runtime，我测试的时候用的 tnpm，扁平规则不一样所以没出现问题
- require.resolve 会递归找可以解决这个问题
Close #1689
> fix: alias babel runtime

- .gitignore
- tools/iceworks/gulpfile.js
- tools/iceworks/package.json
- tools/iceworks/renderer/src/stores/materials.js
目前官方物料源都托管在 `ice.alicdn.com` 下，很多用户特定网络会屏蔽这个域名导致物料源加载失败，因此整个 Iceworks 对用户不可用
对官方物料源加了一个 backup 的 url，backup url 来自于：通过 npm 包将物料源数据同步发包，然后访问 `https://cdn.jsdelivr.net/npm/@icedesign/materails-db@latest/lib/react-materials.json"`，结合日志发现部分用户这个地址还是无法访问
将所有官方维护的数据源（oss 上）添加到 Iceworks 代码里作为终极兜底方案。缺点是数据可能不是最新的，但一定能保证 Iceworks 的可用性。通过构建命令触发同步所有 oss 上的数据到指定代码文件夹，保证每次发版时会更新一次数据，获取数据的逻辑：`ice.alicdn.com`  -> `iceworks builtin data`
> [iceworks]builtin-materials-data

- tools/iceworks/app/main/env.js
- tools/iceworks/app/main/paths.js
- tools/iceworks/app/main/shared.js
- tools/iceworks/renderer/src/lib/project-scripts.js
1. 因 iceworks 内置 node/npm/node-sass 环境，导致用户在命令行和 iceworks 两者间不能友好的切换出现各种问题，因 node-sass 强依赖 node 的版本
2. 因 iceworks 内置 node/npm/node-sass 环境，用户使用时强依赖 iceworks 对基础环境的升级，不能自由切换 node 等环境的版本
3. 目前下载依赖的方式是通过 `npm install --registry=xxx` 的方式进行安装，虽然支持了动态源的切换，但是只能通过 npm client  进行安装，而不能指定诸如 cnpm  和 tnpm 等 npm client，而 npm 和 cnpm 在依赖安装的策略不同，导致出现安装差异
1. 默认优先读取系统的 node/npm/cnpm/tnpm 环境变量，如果系统不存在，则降级兜底使用 iceworks 提供的
2. 支持切换不同的 npm client（npm、cnpm、tnpm）
* 完全去掉内置的 node/npm/node-sass，目前维护成本太大收益太小，提供检测 node 环境安装的提示和一键安装功能
* 在设置面板提供当前 iceworks 使用的 node/npm  client 等版本辅助信息（electron 版本和 electron 依赖的 node 版本理论上都可以暴露出来）
移除 iceworks 最初版本内置 sass binary ？
* iceworks 内置了 sass binary 二进制文件 [sass binary](https://github.com/alibaba/ice/tree/master/tools/iceworks/binary)
* ice-scripts 依赖 node-sass  4.9.0 版本 …
> [iceworks] default use of system environment

- tools/ice-scripts/CHANGELOG.md
- tools/ice-scripts/lib/config/getResolveAlias.js
- tools/ice-scripts/package.json
- 去除 babel-runtime 的 alias
- 依赖的组件里有可能使用不同 br 版本的 babel-runtime，都 alias 到 ice-scripts 里面会导致构建出错
- 不 alias 最大的问题，是我们的业务组件构建后依赖了 babel-runtime，但是 dep 里面没声明，但实际上我们大多数业务组件都依赖了 next，next 依赖了 babel-runtime，一般不会有问题，对于有问题的少数用户，让开发自己添加下 babel-runtime 即可
- webpack 版本不固定：这里的版本固定理论上没什么作用，即便写死了直接依赖，间接依赖还是没锁死，后续考虑全部放开，这个版本先放开 webpack，因为这里写死会间接导致一些项目要安装两个版本的 webpack，然后构建报错 tap balabala
> fix: 去除 babel-runtime 的 alias & 不锁死 webpack 依赖

- tools/iceworks/app/main/alilog.js
- tools/iceworks/app/main/index.js
- tools/iceworks/app/main/scaffolder/lib/extractor.js
- tools/iceworks/app/main/scaffolder/lib/utils.js
- tools/iceworks/app/main/template/utils/extractTarball.js
- tools/iceworks/app/main/utils/autoRetry.js
- tools/iceworks/app/main/utils/npmRequest.js
Iceworks 在主进程上监听了 `uncaughtException` 事件（[源码](https://github.com/alibaba/ice/blob/iceworks/2.17.1/tools/iceworks/app/main/index.js#L58)），并将错误上传到了 SLS 。当前 SLS 上收到了大量该错误。
Iceworks 版本信息：
- electron: 2.0.1
- Node.js: 8.x
- 错误的核心信息：
- msg: "ETIMEDOUT" ([Node.js@8.x - Error](https://nodejs.org/docs/latest-v8.x/api/errors.html))
- stack: "...request.js:849:19)"
- 现象：在一次收到该错误后同一客户端短时间内大量产生该错误。
基本定位：
- 由于 request 请求造成的超时错误未被捕获；
- 该请求有重试机制，导致短时间内大量产生该错误。
1. 错误采集的接口必须容错，否则该接口的抛错将被抛到主进程，造成死循环；
2. 错误采集的接口上传完整的 error 对象，以便获取更多的信息；
3. 重试逻辑存在隐患，需要重新梳理。因此优化重试的实现逻辑：入参优化，异步处理优化，重试判断逻辑优化；
4. extractTarball 打点（所有 request 的错误都先打点，以便统计 request 错误）。
> [iceworks] request 的容错

- react-materials/scaffolds/ice-design-pro/src/components/LocaleProvider/LocaleProvider.jsx
当前的 localeInfo 是根据 `navigator.language` 来的。
但是如果用户浏览器的语言未在程序中指定，就会抛出错误，页面甚至无法打开。#1716
所以如果监测到用户语言是别的国家的，应该默认回落到更通用的 `en-US` 作为默认值。
> fix: pro LocaleProvider fallback to en-US (#1716)

- tools/iceworks/renderer/src/lib/project-scripts.js
https://github.com/alibaba/ice/issues/1718
由于目前支持使用系统的 cnpm/npm 以及其他 npm client，因不同系统之间的环境变量配置会有所不一样，iceworks 目前未能读取相关的路径，导致用户安装错误率失败大幅提高
降级原因方案使用 npm 结合动态源的方式，保证线上版本正常使用
支持多 npm client 安装需要研究 windows 设置环境变量的规则以及 Mac 自定义配置的情况，或者提供设置环境变量的入口， 且需要经过充分的 beta 测试
> fix: use built-in npm client

- tools/ice-scripts/lib/config/getBabelConfig.js
babel 7 里面配置不支持数组参数，只能通过多个同名的 plugin 来实现
> [ice-scripts]Fix babel plugin import

- tools/ice-scripts/lib/scaffold/download.js
`Promise.resolve` can not be called as a function, because there is no context object with 
`Promise.resolve`.
> fix: download scaffold error.

- docs/advanced/how-to-dynamic-load.md
更新动态加载组件文档，之前使用 react-loadable 三方库，改为使用官方提供的 `React.lazy`。
fix #1828
> doc: update react-loadable -> React.lazy

- packages/iceworks-client/.webpackrc.js
- packages/iceworks-client/src/index.js
- packages/iceworks-client/src/models/material.js
- packages/iceworks-client/src/pages/Material/index.js
- packages/iceworks-client/src/store/StoreProvider.js
- packages/iceworks-client/src/store/index.js
- packages/iceworks-client/src/store/storeContext.js
- packages/iceworks-client/src/store/useStore.js
> 使用 react hooks 实现 useStore 功能进行全局的状态管理
`StoreContext`
`StoreProvider`
`useStore()`
使用 hooks 之前，需要先使用 `StoreContext.Provider` 在跟路组件上
```
// src/index.js
import React, { useState }  from 'react';
import { StoreContext } from '@store';
const App = () => {
const [store, setStore] = useState()
return (
<StoreContext.Provider value={{ store, setStore }}>
...
</StoreContext.Provider>
)
}
ReactDOM.render(<App/>, document.getElementById('root'));
```
除了使用 `StoreContext.Provider` 还可以使用 `StoreProvider`，本质上对 `StoreContext.Provider`  的一层封装
```
// src/index.js
import React  from 'react';
import { StoreContext } from '@store';
const App = () => {
return (
<StoreProvider initialState={xxx}>
...
</StoreProvider>
)
}
```
然后就可以使用 `useStore`  hooks 更新和设置全局的 `store` 数据
```
// models/material.js
import { …
```
> [Iceworks]feat: implementation useStore

- templates/ice-angular-material-template/template/block/demo/index.html
- templates/ice-angular-material-template/template/scaffold/src/index.html
html 中有 <base href="/"> 标签导致所有资源从跟路径请求。
> fix: 修复 angular 模版资源 404 的问题

- tools/ice-scripts/lib/core/Plugin.js
const { processEntry } = api;
processEntry({ entry }) 
// <- Uncaught TypeError: Cannot read property 'service' of undefined
> fix: bind this to prevent context change

- tools/ice-scripts/package.json
url-loader will specifies an alternative loader to use when a target file's size exceeds the limi, default is file-loader
https://github.com/webpack-contrib/url-loader/#fallback
https://github.com/webpack-contrib/url-loader/blob/a6705ccf419c6a1240c4ae13c4e19cc0d1360c07/src/utils/normalizeFallback.js#L3
> fix: add file-loader dep

- docs/materials/init-dev.md
- docs/materials/schema.md
1. `init-dev.md`:
The link of `material data protocol` is broken when viewed from the [website](https://ice.work/docs/materials/init-dev).
2. `schema.md`:
The file `iceworks/marterial-scaffold.md` is not present in the current directory anymore. Replaced it with a general link to reflect the correct meaning.
> fix: broken links in website

- packages/iceworks-client/src/components/ErrorBoundary/FallbackComponent.js
- packages/iceworks-client/src/components/ErrorBoundary/index.js
- packages/iceworks-client/src/locales/en-US/index.js
- packages/iceworks-client/src/locales/zh-CN/index.js
- packages/iceworks-client/src/pages/Project/components/FallbackPanel/index.js
- packages/iceworks-client/src/pages/Project/components/LayoutPanel/index.js
- packages/iceworks-client/src/pages/Project/index.js
- packages/iceworks-client/src/pages/Task/index.js
> 问题：部分 UI 的 JavaScript 错误不应该导致整个应用崩溃
* 详见 https://github.com/alibaba/ice/pull/2036 由于未补获的错误导致整个应用 crash，对用户体验及其不好
* 在当前 iceworks 架构下是按照功能模块进行设计的，由此引申模块之间的功能是相互独立的，即使某个模块出错，也只会对当前功能模块有影响
> 解决：使用 React 提供的 `Error Boundaries` 进行错误处理和兜底的 UI 展示
封装 `<ErrorBoundary>` 组件处理错误边界，提供两种使用方式：
```jsx
import ErrorBoundary from '@components/ErrorBoundary';
<ErrorBoundary>
<WrappedComponent />
</ErrorBoundary>
```
```jsx
import {  withErrorBoundary } from '@components/ErrorBoundary';
const WrappedComponent = () => {
// some code
}
export default withErrorBoundary(WrappedComponent)
```
自定义 `Fallback Component` 组件和 `onError` 错误处理
```jsx
// Component
<ErrorBoundary FallbackComponent={  } onError={  }>
<WrappedComponent />
<ErrorBoundary />
or
// HOC
withErrorBoundary(
WrappedComponent,
FallbackComponent,  // …
```
> [iceworks] feat error boundary support

- tools/iceworks/gulpfile.js
https://github.com/alibaba/ice/issues/2074
原因：
- 在老版本中使用的 electron-builder 版本是 [20.20.x](https://github.com/alibaba/ice/blob/iceworks/2.18.2/tools/iceworks/package.json#L71)，打包产出 latest-mac.json/latest-mac.yml ，检查更新时会获取 latest-mac.yml 的内容；
- 在新版本中使用的 electron-builder 版本是 20.39.0，打包产出 latest-mac.yml，检查更新时会获取 latest-mac.yml 的内容。
在发布过程中，由于 json 文件不存在，所以上传 `latest-mac.json` 将失败，下面流程不再执行，`latest-mac.yml` 没有上传。导致获取更新时没有更新。
> fix: 版本自动更新问题

- tools/iceworks/renderer/src/stores/extensions.js
issue: https://github.com/alibaba/ice/issues/2117
用户创建项目，iceworks 会将对应的项目路径缓存到系统的某个文件中，当用户在命令行或者文件夹中把项目删除，在重新打开 iceworks 时会从缓存路径读取对应的项目信息，但是项目已经不存在了，读取失败导致引用到了 pkgData 的代码挂掉了
> fix: compatible when the project is deleted

- packages/ice-template-builder/src/components/Form/BasicForm/BasicForm.jsx
- packages/ice-template-builder/templates/redux/_package.json
- packages/ice-template-builder/templates/redux/ice.config.js
- tools/iceworks/renderer/src/components/CustomScaffold/ColorCard.jsx
- ice-scripts 2.x 已不支持 secondaryColor
- 自定义模板中 ice.config.js 使用 themeConfig ；
- 自定义模板功能中不透出辅色选择。
> refactor: custom template 

- packages/iceworks-client/src/pages/Task/index.js
- packages/iceworks-client/src/pages/Task/stores/task.js
- packages/iceworks-server/src/lib/adapter/modules/task/index.ts
fix: 不同的task任务的状态错误地保存在一个变量中导致相互影响
> [iceworks ] fix: task status save in global

- packages/iceworks-client/src/components/GlobalBar/index.module.scss
fix: xterm样式使用display：none隐藏导致初始化宽度未撑开，改用visibility: hidden隐藏
> [iceworks] fix: xterm style

- packages/iceworks-server/package.json
- packages/iceworks-server/src/lib/adapter/modules/task/index.ts
* 直接调用子进程的 kill() 可以关闭子进程，但是无法关闭子进程打开的其它子进程。需要通过进程 ID 结束进程和子进程。
> [iceworks] kill process pid

- packages/iceworks-client/ice.config.js
- packages/iceworks-client/package.json
- packages/iceworks-server/package.json
- packages/iceworks-server/src/app/middleware/client.ts
* 动态端口获取，端口逻辑 iceworks CLI => Server Middleware => Client Socket
* 由于 socket.io 的设计，在多进程中服务器必须在 sticky 模式下工作，故需要给 startCluster 传递 sticky 参数。
* 前端资源按需加载需要指定 publicPath 路径
> [iceworks] publish flow

- packages/ice-npm-utils/CHANGELOG.md
- packages/ice-npm-utils/lib/index.js
- packages/ice-npm-utils/package.json
修复getAndExtractTarball写空文件时卡死的问题
原因： nodev8.14.0环境下，writeStream写空文件时，不会触发finish事件,  node10下没有问题
> fix: fix write null file in node 8

- packages/iceworks-client/src/components/Progress/index.js
- packages/iceworks-client/src/components/Progress/index.module.scss
- packages/iceworks-client/src/hooks/useDependency.js
- packages/iceworks-client/src/index.js
- packages/iceworks-client/src/pages/Project/components/DependencyPanel/index.js
- packages/iceworks-client/src/pages/Project/index.js
- 创建项目时没有 Adapter 不应该有下载依赖的提醒
- 创建页面时，表单的样式问题
- 安装依赖时，日志重复打印
onBeforeunload 的弹窗在开发阶段弹出十分阻碍，因此在此 PR 中顺便加入了生产环境的判断。
> Project panel bug fix

- packages/iceworks-client/src/pages/Engineering/index.js
问题：现有是通过adpater取ice.config.js配置，进而进行设置菜单的显示隐藏。但是对于adpater-react-v1，由于ice-script v1不支持ice.config.js，adapter中不加载Configuration模块，导致client请求config报错。
fix: 通过Project store中的panels属性来判断Configuration模块是否存在，避免了发请求，不存在的话隐藏设置面板
> [iceworks] fix: adpater-react-v1 getConfCLI error

- packages/iceworks-client/src/components/GlobalBar/index.js
- packages/iceworks-server/package.json
- packages/iceworks-server/src/app/io/controller/home/system.ts
修复打开编辑器的问题，现在能够打开在进程中的编辑器，依赖包[launch-editor](https://github.com/Orange-C/launch-code-editor)
> Fix: fix open editor bug

- packages/iceworks-server/package.json
- packages/iceworks-server/src/app/controller/goldlog.ts
- packages/iceworks-server/src/app/controller/home.ts
- packages/iceworks-server/src/app/router.ts
```js
"scripts" : {
"dev": "NODE_ENV=local midway-bin dev --ts --framework=midway-mirror"
}
```
> [iceworks] use midway mirror package

- packages/iceworks-server/src/interface/base.ts
- packages/iceworks-server/src/interface/git.ts
- packages/iceworks-server/src/interface/router.ts
- packages/iceworks-server/src/lib/adapter/modules/dependency/index.ts
- packages/iceworks-server/src/lib/adapter/modules/git/index.ts
- packages/iceworks-server/src/lib/adapter/modules/page/index.ts
- packages/iceworks-server/src/lib/adapter/modules/router/index.ts
midway logger stores logs to local files and send logs to remote.
> refactor: replace console with midway logger

- packages/iceworks-client/src/hooks/useTask.js
- packages/iceworks-server/src/interface/base.ts
- packages/iceworks-server/src/lib/adapter/modules/task/index.ts
停止 task 进程是 windows 会抛 ENOENT 异常，导致整个进程错误
execa 的 shell 参数设置为true 导致 windows 下的进程不指定 file （可执行文件）
erorr 监听中的异常无法被上层捕获，通过提示输出
> fix: show message when task process error occur

- packages/iceworks-client/src/socket.js
socket 在不同的 Node 版本上出现以下 Error 导致页面白屏
Refs: https://socket.io/docs/client-api/#With-websocket-transport-only
```js
const socket = io({  transports: ['websocket']});
```
> fix: socket compatible with different system platforms

- packages/iceworks-server/src/lib/adapter/modules/task/index.ts
- packages/iceworks-server/src/lib/plugin/project-manager/app.ts
@chenbin92 
Should we add a method call `execa` for project, then adapter using `project.execa`  to execute command?
Following benefits:
- Developer don't need to declare env explicitly;
- We can do some special processing in this way, such as printing global logs.
> feat: set env for server

- packages/ice-npm-utils/lib/index.js
- packages/ice-npm-utils/test/index.test.js
Fix #2438.
Some packages have directories in the tarball.
The package `split` can be processed by original version of function `getAndExtractTarball`.
```
tar xvzf split-1.0.1.tgz 
x package/package.json
x package/.npmignore
x package/LICENCE
x package/index.js
x package/examples/pretty.js
x package/.travis.yml
x package/readme.markdown
x package/test/options.asynct.js
x package/test/partitioned_unicode.js
x package/test/split.asynct.js
x package/test/try_catch.asynct.js
```
However, the package `@babel/helper-function-name` cannot be processed. The directory `lib` makes it fail.
```
tar xvzf helper-function-name-7.1.0.tgz
x package
x package/LICENSE
x package/README.md
x package/lib
x package/package.json
x package/lib/index.js
```
> Fix npm utils extract tarball error

- packages/iceworks-client/src/pages/Material/components/MaterialPanel/index.js
- packages/iceworks-client/src/pages/Material/components/MaterialPanel/index.module.scss
打开物料面板->其他 样式错乱
是之前添加的Loading组件导致的样式错乱 修改错误后，样式正常。如下图
> [iceworks] fix material-panel-styles

- tools/iceworks/renderer/src/Layout/Layout.jsx
- tools/iceworks/renderer/src/Layout/Layout.scss
The reminder will always exist. The closing button is only temporarily hidden. The reminder will still be displayed on the next boot.
> feature: A reminder to upgrade to 3

- tools/iceworks-app/README.zh-CN.md
- tools/iceworks-app/gulpfile.js
- tools/iceworks-app/package.json
No longer need to generate and upload `changelog.json` and `updates.json`,  new sites no longer reveal electronic information.
> refactor: delete unnecessary file generation and upload logic 

- packages/iceworks-server/src/lib/adapter/modules/router/index.ts
问题: 新建页面时路由加到notFound路由后面，导致访问不到
fix: router adapter中原有的路由排序逻辑有两个问题，一个是路由不存在时未排序，另一个是对于有children的路由只会遍历第一个
> fix: router sort logic

- packages/iceworks-client/src/pages/Project/components/PagePanel/BuildPageModal.js
- packages/iceworks-client/src/pages/Project/components/PagePanel/SavePageModal.js
新建页面出现堆栈溢出问题
1. 新建页面时调用 `progress.show` 传递了一个组件到 icestore：
2. 而这个组件本质解析后是一个递归的对象：
3. icestore 中使用 `Object.isFrozen(value)` 进行判断是否要 addProxy：
4. 由于在开发环境中 react 组件是 Frozen 的而生产环境不是 Frozen 的，因而导致 icestore 判断递归执行了
传递一个简单对象到 icestore 中
> fix: use intl formatMessage api

- packages/iceworks-server/src/lib/adapter/modules/dependency/index.ts
- packages/iceworks-server/src/lib/remoteLogger/index.ts
info log will send to remote in the production environment, installation operations generate a large number of logs which is unnecessary.
> fix:  unnecessary logs

- packages/iceworks-server/src/lib/plugin/project-manager/app.ts
新用户首次使用 iceworks 无项目时，控制台抛出错误提示 `notfound project` 不友好
> fix:  not throw an exception

- packages/iceworks-server/package.json
The template.vue.ejs file is not in the dist.
copy template.vue.ejs file to the dist
> [iceworks]fix: copy vue ejs file to dist

- tools/iceworks-cli/CHANGELOG.md
- tools/iceworks-cli/lib/downloadServer.js
- tools/iceworks-cli/package.json
*  https://github.com/alibaba/ice/issues/2604
* `execa.shell` API 已删除https://github.com/sindresorhus/execa/releases/tag/v2.0.0
*  不推荐使用
> fix: update iceworks failed

- tools/iceworks-cli/lib/downloadServer.js
* 安装 iceworks 时安装依赖失败就退出进程 https://github.com/alibaba/ice/issues/2626
> fix: exit process when installation dependencies fail

- tools/iceworks-cli/lib/downloadServer.js
* 在下载 iceworks-core 之后安装依赖可能非常慢，目前只打印了一个提示，给用户的感觉以为是卡死，因此输出安装的详细日志流
> Iceworks cli/log install info

- packages/iceworks-server/src/lib/adapter/locales/en-US.json
- packages/iceworks-server/src/lib/adapter/locales/zh-CN.json
- packages/iceworks-server/src/lib/adapter/modules/task/getTaskConfig.ts
- packages/iceworks-server/src/lib/adapter/modules/task/index.ts
* https://github.com/alibaba/ice/issues/2674
* https://github.com/alibaba/ice/issues/2627
修复工程管理的快捷参数不生效问题，主要原因在于透出到 ice-scripts 的 Boolean 值是以字符串的形式，而 ice-scripts 解析字符串用于是当做 true 的形式进行处理，导致不生效
* 如果判断是 false 则不写入到 CLI 参数上
> [iceworks] fix cli args not working

- packages/iceworks-client/ice.config.js
- packages/iceworks-client/src/components/GlobalBar/index.js
- packages/iceworks-client/src/components/GlobalBar/index.module.scss
- packages/iceworks-client/src/hooks/useDependency.js
- packages/iceworks-client/src/pages/Project/components/DEFPanel/index.js
- packages/iceworks-client/src/stores/globalTerminal.js
使用fusion的Tab组件时，未被激活的TabItem的css元素为 `display: none`，文档渲染时，该元素如同不存在，开启Tab组件的lazyLoad后也不能实例化未被Tab激活的Term，导致未被实例化。
同时实例化两个全局日志（进程日志和操作日志）。不使用fusion的Tab组件。
> fix: can't instantiate two global terminals

- packages/iceworks-client/src/hooks/useProject.js
- packages/iceworks-client/src/pages/Project/index.js
1. The `project` variable is destructured from the `useProject` hooks as `projectStore.dataSource`. We can use this variable instead.
2. We can refactor the `reloadAdapter` method to be placed inside `useProject` hooks. That way we don't need to access `projectStore` in `packages/iceworks-client/src/pages/Project/index.js`.
> Project Page: Use destructured variable from hooks and refactor reloadAdapter

- docs/guide/resource/migrate.md
* 增加 icekit pro 模板升级指南文档，关联 issue  https://github.com/alibaba/ice/issues/2582
* 文档放在 `资源` 目录下
> doc: add icekit pro migrate spec

- docs/guide/dev/router.md
在实际的开发过程中，可能需要在React组件外使用history进行跳转。我认为需要在路由文档中添加上更详细的说明，以便其他人参考。
> docs: add router example

- packages/iceworks-server/src/lib/adapter/modules/page/index.ts
fixed #2747
不使用 `mv`这个npm包，因为它依赖的是原生fs。
若使用原生的fs，在windows的环境下，会可能出现EPERM等错误。
可使用[graceful-fs](https://www.npmjs.com/package/graceful-fs)代替原生的fs。
而fsExtra则是内置了graceful-fs。详见fs-extra的讨论[#684](https://github.com/jprichardson/node-fs-extra/issues/684)
使用 `fsExtra.mv()` 移动组件的/src目录下的文件
> [Iceworks]fix couldn't create page on windows

- packages/iceworks-server/package.json
- packages/iceworks-server/src/lib/adapter/modules/task/index.ts
- 在windows环境下，启动调试时，如果输出的log是中文的话，会出现乱码。（我身边没有mac，mac我没有测试）
- 如果你的windows系统默认的编码方式是gbk的话，那么输出的字符串的编码类型是gbk。当然如果你曾经改过系统的默认的编码方式，则按照你后面改过后的编码方式。
- 如果你是用gbk编码的，就用gbk解码，utf-8也是一样道理。如果你是用utf-8编码的，用gbk解码是会乱码的。
- `buffer.toString()`默认的转换方式为 `utf-8`。
引入`iconv-jschardet`和`iconv-lite`: 对`buffer`的编码类型做一个判断，如果是 `GB2312`，则以`GBK`解码。
```
const encodingType = iconvJschardet.detect(buffer);
const chunk: string = encodingType.encoding === 'GB2312' ? iconv.decode(buffer, 'gbk') : buffer.toString();
```
> [Iceworks]fix: fix decode for log

- docs/guide/advance/proxy.md
> docs: fix typo

- packages/icejs/bin/start.js
- packages/plugin-react-app/package.json
- packages/plugin-react-app/src/config/default.config.js
- packages/plugin-react-app/src/config/setWebpackbar.js
- packages/plugin-react-app/src/index.js
- packages/plugin-ssr/package.json
- packages/plugin-ssr/src/index.ts
- yarn.lock
> feat: optimize webpackbar

- .eslintrc.js
- docs/guide/basic/app.md
- docs/guide/basic/store.md
- examples/basic-request/src/pages/Home/index.tsx
- examples/basic-request/src/pages/Home/service.ts
- examples/basic-spa/src/components/WrapperPage/index.tsx
- packages/plugin-react-app/src/index.js
- packages/plugin-request/request/useRequest.ts
- packages/plugin-request/src/_createAxiosInstance.ts
- packages/plugin-request/src/module.ts
- packages/plugin-store/src/module.tsx
* 废弃 `store.getInitialStates` API，统一到 `getInitialData`
> refactor: store getInitialStates deprecated

- packages/plugin-react-app/src/index.js
relate to: #3237 
`html-webpack-plugin` 的输出在将在 build-scripts 中处理
> chore: optimize output log

- packages/plugin-react-app/src/userConfig/compileDependencies.js
修复在 win32 系统 下配置 compileDependencies 字段后，找不到对应的依赖的路径
> fix: fix compile dependencies path in windows

- packages/plugin-auth/template/index.tsx
- packages/plugin-auth/template/model.ts
直接在 `function` 中返回 `[A, B]` 时, TS 会推导为 `[A | B]`
close #3294
> fix: auth template types

- docs/guide/basic/build.md
- packages/plugin-react-app/src/config/default.config.js
- packages/plugin-react-app/src/userConfig/compileDependencies.js
- 默认增加编译相关的模块以支持运行在 IE11 中。
- 禁止 core-js 模块走 babel 编译（会有部分用户会开启全量编译，会把 core-js 也一块编译，会在 IE11 中报错）
Close: #3268
> Feat: compile deps to support IE11 

- packages/plugin-core/src/index.ts
兼容使用 js 配置时快捷定义 webpack 配置的场景
```js
module.exports = {
plugins: [
(api) => {},
],
};
```
> fix: compatible with functional plugin

- docs/guide/develop/plugin-list.md
- packages/plugin-esbuild/README.md
- packages/plugin-esbuild/package.json
- packages/plugin-esbuild/src/index.ts
- packages/plugin-esbuild/tsconfig.json
- tsconfig.json
- yarn.lock
Issue: [构建产物大小&编译速度优化](https://github.com/alibaba/ice/issues/3354)
> feat: add plugin-esbuild

- docs/guide/basic/build.md
- packages/create-ice/package.json
- packages/plugin-app-core/package.json
- packages/plugin-app-core/src/index.ts
- packages/plugin-react-app/src/userConfig/injectBabel.js
- packages/plugin-ssr/package.json
- 检测 targets 配置项并提示使用 browserlist 替代，
> feat: check the targets and compatible browserslist

- packages/rax-app-renderer/package.json
- packages/rax-app-renderer/tsconfig.json
`rax-app-renderer/renderer.tsx` 编译后为 `rax-app-renderer-renderer.jsx` 导致引用失败，实际应该编译成 `rax-app-renderer/renderer.js`
在 tsconfig 中设置了 jsx 为  preserve 导致编译后文件后缀为 `jsx`，关于 jsx 解释如下：
```json
{
jsx: "preserve"
}
```
-  在 preserve 模式下生成代码中会保留 JSX 以供后续的转换操作使用（比如：Babel）。 另外，输出文件会带有 `.jsx` 扩展名
- 在 react 模式会生成 React.createElement，在使用前不需要再进行转换操作了，输出文件的扩展名为 `.js`
```json
{
jsxFactory: "createElement"
}
```
当 jsx 设置为 react 时，默认会使用 `React.createElement("div")` 创建元素， 所以在 rax 中编译时需要将 jsxFactory 配置为 createElement，这样创建元素时会使用  `createElement("div")` 来生成，而不是 `React.createElement("div")`
> fix: ts compile config

- packages/plugin-request/template/request.ts
- packages/rax-app-renderer/package.json
- packages/rax-app-renderer/tsconfig.json
Signed-off-by: 二凢 <dingyu.wdy@alibaba-inc.com>
1. `request.get`, `request.post` 等方法返回的数据类型为 `Promise<any>`, 不应该是 `Promise<AxiosResponse<any>>`
2. `request` 返回数据类型为 `Promise<any>`, 不应该是 `any`
3. 增加泛型支持，默认为 `any`
1. 使用 ice ts 模板
2. `request('/')`， `request<boolean>('/')`
3. `request.get('/')`， `request.get<boolean>('/')`
> feat: request 增加泛型支持，修复request.get等方法返回数据类型错误

- packages/create-use-router/package.json
- packages/create-use-router/src/index.ts
In `path-to-regexp` v3.x, it can be used like: `const pathToRegexp  = require('path-to-regexp')`.
But in v6.x, it only can be used like: `const { pathToRegexp } = require('path-to-regexp')`
> fix: path-to-regexp usage

- docs/guide/advance/backend.md
- docs/guide/advance/publish.md
- docs/guide/advance/quality.md
- docs/guide/advance/statistical.md
- docs/guide/advance/test.md
- 补充「编写测试」文档 https://github.com/alibaba/ice/issues/3521
> docs: test guide

- examples/basic-store/src/pages/About/index.tsx
- examples/basic-store/src/pages/Detail/index.tsx
- examples/basic-store/src/pages/Detail/model.ts
- examples/basic-store/src/routes.ts
- packages/icejs/package.json
- packages/plugin-store/package.json
- packages/plugin-store/src/generator.ts
- packages/plugin-store/src/template/pageComponent.tsx.ejs
- packages/plugin-store/src/template/pageIndex.ts.ejs
- packages/rax-app/package.json
> Hotifx: store is undefined in class component

- packages/plugin-miniapp/src/index.ts
- 小程序下重新设置 entry 无需配置 `react-dev-utils/webpackHotDevClient`
> fix: reset miniapp entry

- packages/icejs/package.json
- packages/plugin-app-base/package.json
- packages/plugin-app-base/src/setDev.js
- packages/plugin-app-base/src/utils/polyfillLoader.js
- packages/plugin-react-app/package.json
- packages/plugin-react-app/src/utils/polyfillLoader.js
- packages/rax-app/package.json
- `app.json` 会经过 polyfill-loader，导致被加入了 js 代码，从而导致后续 JSON 解析报错
- 修复多页模式的 log 信息
> fix: js project error

- packages/build-mpa-config/src/mpa-loader.ts
暂时使用可以被 polyfill 覆盖的语法绕过高级语法导致的 ios10 等系统的白屏问题，具体 issue 见 https://github.com/raxjs/rax-scripts/issues/457
> fix: mpa-loader ios10

- packages/plugin-app-base/src/userConfig/externals.js
> fix: override externals

- packages/plugin-app-base/src/config/default.config.js
- packages/plugin-app-base/src/setBuild.js
- packages/plugin-app-base/src/setDev.js
- packages/plugin-app-base/src/setTest.js
- 修复 `web`/`kraken` 同时启动服务的时候，`kraken` 资源找不到的问题
- 支持 browser history
- 统一 debug 输出内容
> feat: support browser history

- packages/plugin-ice-ssr/package.json
- packages/plugin-ice-ssr/src/server.ts.ejs
问题描述：
项目中使用 SSR 时，遇到请求不存在路由，进入下面的逻辑时候，matchedRoute 会是 undefined，会报错。如下图：
> fix: ssr matchedRoute undefined

- examples/with-rax/src/components/BuggyCounter/index.tsx
- examples/with-rax/src/pages/Home/index.tsx
- packages/create-app-shared/src/appLifeCycles.ts
- packages/plugin-rax-app/package.json
- packages/plugin-rax-app/src/base.js
- packages/plugin-rax-web/package.json
- packages/plugin-rax-web/src/DocumentPlugin/index.js
- packages/plugin-rax-web/src/setEntry.js
- packages/plugin-rax-weex/package.json
- packages/plugin-rax-weex/src/setEntry.js
- packages/plugin-ssr/package.json
- packages/plugin-ssr/src/web/setDev.js
- yarn.lock
> chore: remove rax-compile-config

- packages/eslint-reporting-webpack-plugin/package.json
- packages/eslint-reporting-webpack-plugin/src/index.js
ESlint config `rax-config-ali` 's typescript  plugin parser error will occurred when use isPathIgnored and executeOnFiles.
Run used method in advance, can avoid block webpack
> fix rax-config-ali error block webpack

- .github/workflows/ci.yml
- packages/build-user-config/src/config/constants.js
- packages/build-user-config/src/utils/modifyUserConfig.js
当 `motifyUserConfig` 在 A 插件中执行的时候，A 插件中任意生命周期里拿到的 `context.userConfig` 都是被删减过后的值，无法获取到最新值。原因是 `motifyUserConfig` 修改的 `context` 和当前插件的 `context` 不是同一个对象，所以需要在 motify 之后更新 `userConfig`
> fix: update userconfig

- packages/plugin-store/src/generator.ts
问题：
当组件名是连字符（带 - ）的时候，组件命名会有问题，比如：
```jsx
// `PageAbout-a` will occur error 
import PageAbout-a from '/Users/luhc228/workspace/github.com/alibaba/ice/examples/basic-store/src/pages/About-a';
const PageComponentName = PageAbout-a;
```
> Fix: compatible with page name with - in store 

- packages/build-user-config/src/userConfig/eslint.js
当配置 `eslint: true` 的时候，阻塞构建的同时需要把 eslint 的报错抛出来
> fix: eslint emit error

- packages/create-app-shared/src/collectAppLifeCycle.ts
- packages/create-app-shared/src/pageLifeCycles.ts
- Fix: miniapp `onShareAppMessage` doesn't  emit
- Fix: `withPageLifeCycle` makes `componentWillUnmount` invaild
> fix: lifycycle problem

- examples/basic-spa/build.json
- packages/build-scripts-config/src/config/webpack/defaultPostcssPlugins.js
- packages/build-scripts-config/src/config/webpack/postcss.config.js
- packages/build-user-config/src/userConfig/postcssOptions.js
postcss-loader 为 3.x 版本，目前 rax 和 react 基础配置中均以 require 形式进行使用
> fix: compatible with functional postcss options

- packages/plugin-app-core/src/generator/templates/common/runApp.ts.ejs
- packages/plugin-app-core/src/generator/templates/common/types.ts.ejs
> fix: runApp params type

- packages/plugin-router/src/index.ts
Fix: mpa 应用下的 spa，导入 routes 后 ts 类型错误，详细见下图：
原因：在 build.json 中配置了 `routes: false` 后，不会生成类型文件
> Fix: router types not export when router is false

- packages/build-user-config/package.json
- packages/build-user-config/src/getEnhancedWebpackConfig.js
- yarn.lock
use @nuxtjs/friendly-errors-webpack-plugin instead while friendly-errors-webpack-plugin is not longer ship new versions
> fix: error message of friendly-errors-webpack-plugin

- package.json
- packages/build-app-helpers/src/getSassImplementation.ts
- packages/build-scripts-config/package.json
- packages/build-user-config/src/userConfig/sassLoaderOptions.js
- yarn.lock
默认移除 node-sass 将导致大量工程启动失败，造成比较大的 breakchange，因此策略调整如下：
- 内置 sass（dart-sass），区别详见 https://github.com/sass/dart-sass#behavioral-differences-from-ruby-sass （整体影响可控）
- 如果项目中依赖 node-sass / sass，则以项目中的依赖为准
> fix: add default sass implementation

- packages/build-user-config/src/userConfig/compileDependencies.js
> chore: exclude core-js in miniapp

- packages/build-user-config/src/config/user.config.js
- packages/build-user-config/src/userConfig/sourceMap.js
resolves https://github.com/alibaba/ice/issues/3960
支持 sourceMap 设置字符串，设置 `hidden-*` 类型的 sourceMap 即可在构建产物中移除 sourceMappingURL
```json
{
"souceMap": "hidden-source-map"
}
```
> feat: support custom sourceMap in build

- packages/plugin-dev-inspector/README.md
- packages/plugin-dev-inspector/package.json
- packages/plugin-dev-inspector/src/index.ts
- packages/plugin-dev-inspector/src/loader.ts
- packages/plugin-dev-inspector/src/runtime.tsx
- packages/plugin-dev-inspector/tsconfig.json
- tsconfig.json
增加插件 build-plugin-dev-inspector
同时支持 rax 及 ice.
在本地调试的环境下，把鼠标 hover 到想要调试的元素，就会显示出遮罩框；再点击一下，会自动在编辑器中跳转到对应的文件中，并且跳转到对应的行和列。
实现原理：使用 inspector-dom 选择节点，使用 loader 将组件信息放入节点中，最后开启 devserver 通过 vs code goto 命令唤醒对应文件
效果：
> feat: add plugin-dev-inspector

- packages/plugin-app-core/src/generator/templates/common/loadRuntimeModules.ts.ejs
- packages/plugin-app-core/src/generator/templates/common/loadStaticModules.ts.ejs
采用 import 方式加载 runtime，会因 import 顺序问题，让 runtime 中引入的源码无法从 ice 中导入部的 API
比如 plugin-router 的 runtime 中依赖了 src/routes.ts，routes 文件中依赖的所有组件将无法使用从 ice 中导入的 withRouter 等 API（在 runApp 中导出）
> fix: load runtime modules

- packages/icejs/package.json
- packages/plugin-app-core/CHANGELOG.md
- packages/plugin-app-core/package.json
- packages/plugin-app-core/src/constant.ts
未编译 runtime 代码使用 require 加载方式与 build-plugin-fast-refresh 共用是会导致无法模块无法加载的问题，暂时关闭
> fix: modify default value of generateRuntime

- packages/plugin-router/src/runtime/formatRoutes.tsx
多层嵌套路由 path 拼接规则有问题
三层以下正常的原因：默认做了 parent path 为空的兜底逻辑
> fix: join route path

- packages/plugin-icestark/CHANGELOG.md
- packages/plugin-icestark/package.json
- packages/plugin-icestark/src/babelPluginMicroapp.ts
- packages/plugin-icestark/src/types/base.ts
> release: plugin icestark 2.0.7

- packages/build-user-config/package.json
- packages/build-user-config/src/userConfig/esbuild.js
- yarn.lock
ESBuildPlugin is now deprecated and can be removed [Release 2.10.0](https://github.com/privatenumber/esbuild-loader/releases/tag/v2.10.0)
> chore: remove ESBuildPlugin while it is deprecated

- packages/plugin-store/CHANGELOG.md
- packages/plugin-store/src/generator.ts
- packages/plugin-store/src/utils/checkPageIndexFileExists.ts
- packages/plugin-store/src/utils/checkStoreAndModelExist.ts
- packages/plugin-store/src/utils/checkStoreAndModelFileExist.ts
- packages/plugin-store/src/utils/getPath.ts
问题：在 Windows 中调试项目，src/pages/Home/store.ts 已存在，但还是在终端显示 Warning 找不到对应的 store.ts
原因：
原来在匹配目标文件时，是使用以下的用法：
```ts
import * as globby from 'globby';
// globby.sync(pattern, options)
// srcPath 是绝对路径
globby.sync(path.join(srcPath, 'store.*'))
```
这里的 `path.join` 方法会将所有给定的 `path` 片段连接到一起（使用平台特定的分隔符作为定界符），然后规范化生成的路径。这会导致在 windows 和 mac 上生成的路径有不同的差异：
```js
path.join('src', 'store.*')
// windows
// \\xxx\\src\\store.*
// linux or macos
// /xxx/src/store.*
```
在 [How to write patterns on Windows? ](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows) 中提到，pattern 中应使用`/` 作为要匹配的字符，而使用 `\` 用于转义字符。
在匹配路径的时候，因为在 fast-glob 内部会把 cwd 路径统一 normalize 掉（详见[代码](https://github.com/mrmlnc/fast-glob/blob/ffff3ecc11d5d752b14386c55affaaaa4a8a2879/src/utils/path.ts#L11)），使得在所有平台上得到统一的路径。当在 Windows …
> Fix: fail to check store file in Windows

- packages/plugin-router/CHANGELOG.md
- packages/plugin-router/package.json
IRouterConfig 类型依赖到 `@types/react-router-dom` 包中的类型，但当前 plugin-router 中 `@types/react-router-dom` 是在 devDeps，安装 ice.js 依赖时没有安装该依赖到项目中，导致下面的报错：
> Fix: react-router-dom types not found

- packages/build-mpa-config/CHANGELOG.md
- packages/build-mpa-config/src/index.ts
问题：在 MPA 应用中，当入口为 src/pages/Home/app.ts，并且入口包含 `export default`，页面没有正常渲染出来
解决：检查当入口没有 export default 时，判定是 runApp 或者自定义渲染逻辑，不再限定是 app.ts 文件
> fix: page not render when app.ts has export default declaration in mpa

- packages/build-mpa-config/CHANGELOG.md
- packages/build-mpa-config/package.json
- packages/build-mpa-config/src/index.ts
原因：原先有部分 ice.js mpa 应用以 src/pages/xxx/app.ts 作为入口时，使用 export default，会导致在临时目录下生成对应的 mpa entry，导致用户自定义的 render 逻辑失效
解决：rax-app 保持现在的逻辑，ice 针对以 app.ts 入口不生成 mpa entry
> fix: generate  mpa entry when use app.ts

- packages/create-app-shared/CHANGELOG.md
- packages/create-app-shared/package.json
- packages/create-app-shared/src/createBaseApp.ts
如果开发者通过 `runApp` 传入的配置对象上存在不可枚举的属性或者原型链上的属性，通过 `deepmerge` 中的 `deepClone` 会导致这些属性丢失
> fix: deep clone let custom config  lost

- packages/icejs/package.json
- packages/icejs/src/getBuiltInPlugins.ts
- packages/plugin-icestark/CHANGELOG.md
- packages/plugin-icestark/src/index.ts
- packages/plugin-icestark/src/runtime.tsx
plugin-icestark 2.0.8 版本除了依赖 wrapperRouterRender 之外，还依赖到了 plugin-router 中的 renderRouter 中支持 customProps 能力。如果锁了版本的情况下可能会存在有 wrapperRouterRender 但是没有 customProps 能力，导致业务上的 breakchange。
统一在环境变量中输出版本信息，后续可以作为一些版本依赖的判断依据，用于提示输出和 cache 版本的标识
> fix: compatible with case which icejs verison is locked

- packages/build-mpa-config/CHANGELOG.md
- packages/build-mpa-config/src/generateEntry.ts
- packages/build-mpa-config/src/index.ts
- packages/build-mpa-config/src/template/rax.ts.ejs
- packages/build-user-config/CHANGELOG.md
- packages/build-user-config/src/loaders/AppConfigLoader/index.js
The configure which developer config in `src/app.json` `route` field, will pass to page component as `props.pageConfig`
> feat: support pass page config to page

- packages/build-mpa-config/CHANGELOG.md
- packages/build-mpa-config/package.json
- packages/build-mpa-config/src/generateEntry.ts
- packages/build-mpa-config/src/index.ts
- packages/build-mpa-config/src/template/rax.ts.ejs
- packages/build-user-config/CHANGELOG.md
- packages/build-user-config/package.json
- packages/build-user-config/src/loaders/AppConfigLoader/index.js
- packages/icejs/package.json
- packages/plugin-fusion/CHANGELOG.md
- packages/plugin-fusion/package.json
- packages/plugin-fusion/src/index.js
- packages/plugin-fusion/src/utils/getCalcVars.js
- packages/plugin-fusion/src/utils/getThemeCode.js
- packages/plugin-ice-ssr/CHANGELOG.md
- packages/plugin-router/CHANGELOG.md
- packages/plugin-router/package.json
- packages/plugin-router/src/runtime/formatRoutes.tsx
- packages/plugin-router/src/utils/__tests__/joinPath.spec.ts
- packages/plugin-router/src/utils/joinPath.ts
- packages/plugin-router/tsconfig.json
- packages/plugin-webpack5/CHANGELOG.md
- packages/plugin-webpack5/package.json
- packages/plugin-webpack5/src/index.ts
- packages/plugin-webpack5/src/remoteConfig.ts
- packages/react-app-renderer/CHANGELOG.md
- packages/react-app-renderer/package.json
- packages/react-app-renderer/src/server.tsx
> Release 1.17.7

- packages/react-app-renderer/CHANGELOG.md
- packages/react-app-renderer/package.json
- packages/react-app-renderer/src/server.tsx
在开启 SSR 应用，dev 模式下是能正常的，prod 环境下会报错  '[SSR]: Only support BrowserRouter when using SSR. You should set the router type to "browser". For more detail, please visit https://ice.work/docs/guide/basic/router'
抛出上面的错误是 `react-app-renderer` 中的 `reactAppRendererWithSSR` 函数。
假设当前应用的 `appConfig` 配置如下的：
```js
import { runApp } from 'ice';
const appConfig = {
app: {
rootId: 'ice-container',
},
router: {
type: 'browser'
}
};
runApp(appConfig);
```
在生产环境下，尝试在本地复现问题以更好的排查，增加下面的 log 日志：
```diff
export default function reactAppRendererWithSSR(context, options) {
const { appConfig } = options || {};
+ console.log('appConfig:', appConfig);
appConfig.router = appConfig.router || {};
if (appConfig.router.type !== 'browser') {
throw new Error('[SSR]: Only support BrowserRouter when using SSR. You should set …
```
> fix: origin appConfig object was modified

- packages/build-scripts-config/CHANGELOG.md
- packages/build-scripts-config/package.json
sass 1.33/34 版本出现大量 warning 日志，目前仅支持 cli 方式调用的时候禁止输出，暂时锁定版本已优化调试信息
https://github.com/sass/dart-sass/issues/672#issuecomment-846311746
> fix: lock sass version

- packages/build-user-config/CHANGELOG.md
- packages/build-user-config/src/userConfig/postcssrc.js
SSR 场景，target 为 node 的 webpack config 中没有 postcss-loader
https://github.com/alibaba/ice/blob/d11ec74c50011e8e1647fec3ae9fab89a9e17a4b/packages/build-user-config/src/userConfig/postcssrc.js#L15
只 use( 'postcss-loader' )，而不配置 .loader()，会导致 webpack 报错 "No loader specified"
> fix: No loader specified

- packages/create-use-router/CHANGELOG.md
- packages/create-use-router/package.json
- packages/create-use-router/src/index.ts
- 从应用维度来看，cache `routerConfig` 带来的收益极小
- HMR 生效时，共享文件内存会导致代码执行报错
> refactor(create-use-router): remove routerConfig cache for HMR 

- packages/plugin-auth/template/index.tsx.ejs
修复 webpack 模式下 basic-plugin-auth 插件的类型导出问题
> Fix: basic-plugin-auth export type

- packages/build-mpa-config/package.json
- packages/create-cli-utils/package.json
- packages/icejs/package.json
- packages/plugin-config/package.json
- packages/plugin-dev-inspector/package.json
- packages/plugin-helmet/package.json
- packages/plugin-icestark/package.json
- packages/plugin-logger/package.json
- packages/plugin-mpa/package.json
- packages/plugin-react-app/package.json
- packages/plugin-router/package.json
- packages/plugin-stark-module/package.json
- packages/plugin-theme/package.json
- packages/vite-service/package.json
- packages/vite-service/src/build.ts
- packages/vite-service/src/start.ts
- yarn.lock
对于项目开发而言 start / build 属于高频操作，并且 icejs 内置并预编译了 webpack。而 jest 测试相对低频，如果默认依赖会带来大量三分依赖和 peer dependencies 的 waring，因此期望有测试需求的，可以在具体项目中依赖 jest。
关联 PR：https://github.com/ice-lab/build-scripts/pull/53
> chore: upgrade dependencies

- packages/build-user-config/src/userConfig/cssLoaderOptions.js
如果用户在 cssLoaderOptions 中传入了 `modules` 配置项，会导致全部的 css rules 都应用 css modules，这个 PR 对 `modules` 配置进行了处理，只传给 `*-module` 的规则
> fix: only pass `modules` to css module rule

- packages/icejs/package.json
- packages/plugin-app-core/CHANGELOG.md
- packages/plugin-app-core/package.json
- packages/plugin-app-core/src/utils/getRoutes.ts
win32 下 path.join 的路径 `src\\routes` 作为 globby 的匹配规则无法正确查找到路由文件。
Close #4611
> fix: globby pattern do not support path of win32

- packages/vite-service/src/plugins/html.ts
windows 下如果传入的 html 地址为相对路径，通过 path.posix.relative 获取值会有问题
> fix: windows build error in vite mode

- packages/plugin-react-app/package.json
通过 build-plugin-router 和 build-plugin-react-app 依赖相同版本的 react-router-dom 方式修复 yarn 安装无法找到依赖的问题
> fix: add dependency of react-router-dom to fix yarn install

- examples/basic-vite/src/pages/Home/index.tsx
- packages/icejs/package.json
- packages/plugin-store/CHANGELOG.md
- packages/plugin-store/package.json
- packages/plugin-store/src/index.ts
- packages/plugin-store/src/vitePluginImportRedirect.ts
vite 项目下使用 store 会出现循环依赖的情况，从而导致 HMR 过程中发生报错：
can't read property store of null
> fix: store error in vite HMR

- packages/plugin-router/CHANGELOG.md
- packages/plugin-router/package.json
- packages/plugin-router/src/index.ts
- packages/vite-service/CHANGELOG.md
- packages/vite-service/package.json
- packages/vite-service/src/wp2vite/config.ts
vite 模式下默认过滤了 node_modules 相关的 alias，导致与 webpack 模式差异较大。
对于内置设置的 alias，存在 esm 规范产物的应该优先使用，比如 react-router-dom 包
> fix: alias in mode vite

- packages/plugin-react-app/CHANGELOG.md
- packages/plugin-react-app/package.json
- packages/plugin-react-app/src/userConfig/remoteRuntime/configApp.ts
备选方案：使用 [html-webpack-tags-plugin](https://www.npmjs.com/package/html-webpack-tags-plugin) 替代 AddAssetHtmlPlugin，但由于其代码内部耦合 html-webpack-plugin 的依赖判断（框架内部预编译了 html-webpack-plugin，实际引入为 @builder/pack/deps/html-webpack-plugin），暂时无法直接替换。
考虑应用场景和 404 页面的使用，先通过移除 404 页面生成插件低成本修复
> fix: build error when active remoteRuntime

- packages/build-user-config/CHANGELOG.md
- packages/build-user-config/src/config/user.config.js
- packages/build-user-config/src/userConfig/eslint.js
- packages/vite-service/src/wp2vite/index.ts
> fix: disable default file lint for hmr performace

- packages/plugin-icestark/CHANGELOG.md
- packages/plugin-icestark/package.json
- packages/plugin-icestark/src/runtime.tsx
> fix: 🐛 more elegant way to use `registerAppEnter` & `registerAppLeave`

- packages/icejs/bin/copy-dts-to-ice-temp.js
当执行 postinstall 脚本时，process.cwd() 拿到的是该依赖的路径`/my-project/node_modules/ice.js`，而不是 `/my-project`，导致复制 ice.d.ts 类型声明文件到错误的目录 (`/my-project/node_modules/ice.js/.ice/ice.d.ts`)
参考：
- https://stackoverflow.com/questions/34781630/how-to-automatically-copy-files-from-package-to-local-directory-via-postinstall
- https://docs.npmjs.com/cli/v8/commands/npm-run-script#description
> fix: fail to copy dts file to correct dir

- packages/icejs/package.json
- packages/plugin-mpa/CHANGELOG.md
- packages/plugin-mpa/package.json
- packages/plugin-mpa/src/index.ts
- yarn.lock
disableRuntime 的情况下 `addImportDeclaration` 未注册，并且 `redirectEntries` 为空（没有在 .ice 目录下生成入口）
Fix #4907
> fix: compatible with disable runtime when config mpa

- packages/webpack-dev-mock/CHANGELOG.md
- packages/webpack-dev-mock/package.json
- packages/webpack-dev-mock/src/matchPath.ts
vite 模式下不存在 req.path，而 req.url 会带上 query 参数，统一通过 _parseUrl 上的内容进行获取
Fix #4894
> fix: match the correct pathname of mock server

- packages/build-user-config/CHANGELOG.md
- packages/build-user-config/package.json
- packages/build-user-config/src/webpack5.js
> fix: re-calculate webpack cache id when config disableRuntime

- packages/vite-service/src/wp2vite/config.ts
Vite would downgrade https server from http2 to tls-only if `server.proxy` is truthy (See [vite code](https://github.com/vitejs/vite/blob/61d076ae0ce724ffc5242358d067f7b1438d24bb/packages/vite/src/node/http.ts#L85)). 
As `{}` is a truthy value, even there is no proxy setting, https would be downgraded.
> fix(vite-service): fix transform for no proxy

- packages/plugin-icestark/CHANGELOG.md
- packages/plugin-icestark/package.json
- packages/plugin-icestark/src/entryHelper.ts
- packages/plugin-icestark/src/index.ts
- packages/plugin-icestark/src/lifecyclePlugin.ts
- packages/plugin-icestark/tests/entryHelper.spec.ts
- packages/vite-plugin-index-html/CHANGELOG.md
- packages/vite-plugin-index-html/package.json
- packages/vite-plugin-index-html/src/index.ts
- packages/vite-plugin-index-html/src/utils.ts
- packages/vite-plugin-index-html/tests/utils.ts
> Release: plugin-icestark 2.5.1

- packages/vite-plugin-index-html/src/index.ts
- packages/vite-plugin-index-html/src/utils.ts
- packages/vite-plugin-index-html/tests/index.test.ts
我在使用 icestark 的 vite demo 时，发现 react 子应用加载会报错，后来发现是 vite-plugin-index-html 在打包时，没有删除  <script type="module" src="/src/main.tsx"></script>；
我看了下，是 icestark-vite-react 的 vite.config.ts 文件中配置的是  src/main.tsx；而 “index.html” 中的是 /src/main.tsx，  导致 vite-plugin-index-html 中的字符串匹配失败（如下图）；
这里_entry 和 src 都可能填写绝对或相对地址，所以俩变量哪边的 length 更大就不好说了，这导致正则和 includes 都不好使了，我这里把这个 _entry 补了下，当它是前面不是 `./` 或者  `/` 的时候，在前面拼一下 `./`，这样至少 length 不会比 src 少，includes 可以成功；
另外我顺便抽离了 getRelativePath 方法到 utils.ts 里了，同时改了方法名，getRelativedPath 貌似是错别字；
> 我这个修改方法，没覆盖所有场景(绝对或相对地址)，后面我再抽时间写个方法优化下吧；
> fix: wrong matching logic in pluginIndexHtml

- packages/build-mpa-config/src/generate/BaseGenerator.ts
https://github.com/alibaba/ice/pull/5090#discussion_r783616867
期望初始化阶段完成 disableRuntimePlugin 的设置，如果在 base 中执行，时机上不好把握，因为在 constructor 阶段，注册的 API 还无法拿到
> chore: optimize api name

- packages/build-user-config/CHANGELOG.md
- packages/build-user-config/package.json
- packages/build-user-config/src/userConfig/mock.js
兼容 rax-app 在 webpack 5下使用低版本 4.x 的 webpack-dev-server
> fix: compatible with rax-app devServer when config webpack5

- examples/basic-i18n/src/app.tsx
- packages/plugin-i18n/CHANGELOG.md
- packages/plugin-i18n/package.json
- packages/plugin-i18n/src/index.ts
- packages/plugin-i18n/src/templates/index.tsx.ejs
Ref: https://github.com/alibaba/ice/issues/5243
支持在组件外设置国际化语言（本质是修改浏览器 cookie 的 ice_locale 的值）
> feat: support setLocale api

- packages/plugin-react-app/CHANGELOG.md
- packages/plugin-react-app/package.json
- packages/plugin-react-app/src/setBase.js
> fix: config of conditionNames

- packages/create-app-shared/package.json
- packages/create-app-shared/src/index.ts
- yarn.lock
Treat kraken as web, prevent injecting Weex modules.
> Fix: treat kraken as web

- packages/plugin-react-app/src/userConfig/remoteRuntime/configApp.ts
#5210 fix remoteRuntime while using preBuilt bundles 
解决 container missing 问题，
但似乎第一次构建的时候并非使用预构建产物，且第二次构建也会编译npm包。
shared的缘故？
> fix: remoteRuntime container missing

- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/axiosUtils.ts
toString() 方法在 IE 11 下会报错，需要增加兼容性处理
https://github.com/axios/axios/blob/v1.x/lib/utils.js
> feat: add compatible toString() function

- packages/plugin-i18n/src/index.ts
- packages/plugin-i18n/src/runtime.tsx
- packages/plugin-i18n/src/templates/index.tsx.ejs
- packages/plugin-i18n/src/types.ts
Add a setting option in appConfig which can block cookie setting when app loaded or execute setLocale method. This feature is to meet the needs of cookie privacy protection compliance in some countries and regions.
> feat: add setting for block cookie setting i18n locale

- packages/vite-service/CHANGELOG.md
- packages/vite-service/package.json
- packages/vite-service/src/wp2vite/index.ts
- yarn.lock
> fix: avoid top-level warnings of esbuild

- packages/build-user-config/src/userConfig/hash.js
Replace `hash` to `fullhash` to fix webpack5 hash waring.
Webpack doc:  https://webpack.js.org/configuration/output/#outputpath
> fix:webpack5 replace hash to fullhash.

- packages/plugin-css-assets-local/src/index.js
- packages/webpack-plugin-extract-css-assets/README.md
- packages/webpack-plugin-extract-css-assets/src/index.ts
- packages/webpack-plugin-extract-css-assets/src/process-assets.ts
修改了 plugin-css-assets-local 和 webpack-plugin-extract-css-assets 两个包。
加入了 forceLocal 选项，表示是否强制为本地，默认值为 false。
当 forceLocal 为 true 时，则无论 output.publicPath 是否为 http 网络路径，插件都会工作。
> feat: add forceLocal of extract-css-assets plugin

- examples/basic-i18n/build.json
- examples/basic-i18n/src/locales/locales.ts
- examples/basic-i18n/src/locales/messages.ts
- packages/plugin-i18n/src/runtime.tsx
- packages/plugin-i18n/src/templates/index.tsx.ejs
- packages/plugin-i18n/src/utils/getDetectedLocaleFromPathname.ts
- packages/plugin-i18n/src/utils/getLocaleData.ts
i18n 下路由跳转时候依赖 cookies 上 `ice_locale` 的值，因此需要初次访问页面的时候设置当前页面的 locale 到 cookie 中
> fix: redirect incorrect i18n page

- examples/basic-i18n/src/pages/UserInfo/index.tsx
- examples/basic-i18n/src/routes.ts
- packages/plugin-ice-ssr/CHANGELOG.md
- packages/plugin-ice-ssr/src/server.ts.ejs
对于带有 /${locale} 的地址，在 matchRoute 时无法拿到路由组件
> fix: not get the real component when enable i18n

- examples/basic-i18n/build.json
- examples/basic-i18n/src/locales/locales.ts
- examples/basic-i18n/src/locales/messages.ts
- packages/plugin-i18n/package.json
- packages/plugin-i18n/src/index.ts
- packages/plugin-i18n/src/runtime.tsx
- packages/plugin-i18n/src/templates/index.tsx.ejs
- packages/plugin-i18n/src/types.ts
- packages/plugin-i18n/src/utils/getDetectedLocaleFromPathname.ts
- packages/plugin-i18n/src/utils/getLocaleData.ts
- packages/plugin-i18n/src/utils/getRedirectIndexRoute.tsx
- packages/plugin-i18n/src/utils/normalizeLocalePath.ts
- IE11 下不存在 `window.navigator.languages`，需要做兼容处理
- 支持在禁用 cookie 的情况下不设置当前语言到 cookie 中 https://github.com/alibaba/ice/pull/5437
- 修复 cookie 禁用时，locale 值获取不正确的问题 https://github.com/alibaba/ice/pull/5441 https://github.com/alibaba/ice/pull/5442
- 调整 locale 获取的优先级 https://github.com/alibaba/ice/pull/5458
- 修复跳转到错误的国际化路由页面 https://github.com/alibaba/ice/pull/5461
暂未解决的问题：
https://github.com/alibaba/ice/issues/5384
> fix: some i18n bugs

- packages/plugin-ice-ssr/CHANGELOG.md
- packages/plugin-ice-ssr/src/server.ts.ejs
生成 Html 中没有加入异步 bundle url，导致没有等待异步的资源加载完，就进行页面渲染，出现样式闪动的情况
> fix: not await dynamic chunks load

- examples/basic-i18n/build.json
- examples/basic-ssr/build.json
- packages/plugin-ice-ssr/package.json
- packages/plugin-ice-ssr/src/index.ts
- yarn.lock
支持 nodeExternals 选项，ssr 打包的时候可以把 node_modules 的依赖 external 出去
> feat: support nodeExternals

- packages/build-user-config/CHANGELOG.md
- packages/build-user-config/package.json
- packages/build-user-config/src/userConfig/hash.js
rax-app 依赖 @builder/user-config，而部分 rax-app 的项目还是依赖 webpack4，导致无法正确计算出 hash 值
Close #5477
> fix: compatible with webpack4 hash type

- packages/plugin-fusion/CHANGELOG.md
- packages/plugin-fusion/package.json
- packages/plugin-fusion/src/webpackLoaders/unicodeLoader.js
- packages/vite-service/CHANGELOG.md
- packages/vite-service/package.json
- packages/vite-service/src/plugins/cssChunk.ts
入口的 css 在一些主动分包场景下会有对应依赖关系，不能直接删除
> fix: do not remove origin output css when config cssChunkNames

- packages/plugin-keep-alive/src/runtime.tsx
使用vite在生产环境下构建时，KeepAlive组件会被导出为{ default:  KeepAlive, KeepAlive： KeepAlive，....} react渲染该组件会报错，prod环境很难追踪bug，直接使用单独导出的KeepAlive就好,国庆快乐，溜了溜了。
> fix(plugin): 使用vite在生产环境下构建(webpack正常),build-plugin-keep-alive插件会异常导致所有的子路由无法渲染

- packages/plugin-ignore-style/src/index.ts
在使用antd和procomponents时，按照官方文档操作使用ignore-style-plugin处理procomponents中对antd组件样式的重复引用，windows环境下无法生效，最终定位到是由于windows文件分隔符为\，而插件中处理libraryName的正则默认是/，导致null-loader没有拦截到procomponents中对antd样式的引用。
> fix: 兼容由于文件分隔符的差异导致ignore-style-plugin在windows电脑环境下调试无法生效的问题

- examples/with-data-loader/src/app.tsx
- examples/with-data-loader/src/pages/home.tsx
- packages/runtime/src/AppData.tsx
- packages/runtime/src/dataLoader.ts
- packages/runtime/src/routes.tsx
- packages/runtime/tests/routes.test.tsx
- packages/runtime/tests/runClientApp.test.tsx
- 修复 app 的 dataLoader 没有被调用的问题（原因是，dataLoader 构建时移除了，需要通过 data-loader.js 发起请求）
> fix: app data loader

- packages/rax-compat/src/hooks.ts
- packages/rax-compat/tests/hooks.test.tsx
调用 `useState` 返回更新函数，需要支持函数入参的写法。
```js
const [state, setState] = useState(0);
setState(0);
setState(count => count + 1);
```
> fix: rax-compat usestate bug

- packages/miniapp-runtime/CHANGELOG.md
- packages/miniapp-runtime/package.json
- packages/miniapp-runtime/src/dom/element.ts
- packages/miniapp-runtime/src/dom/event-source.ts
背景介绍：dev 模式下 node_modules 代码不会被编译，在支付宝小程序环境中下面的代码将出现 `Constructor Map requires 'new'` 的报错（详见 https://stackoverflow.com/questions/66438435/error-typeerror-constructor-map-requires-new-in-es5 ）：
```js
class EventSource extends Map {
//...
}
const eventSource = new EventSource();
```
因此修改此处代码
> refactor(miniapp): use static create method to create instance of EventSource

- packages/ice/CHANGELOG.md
- packages/ice/package.json
- packages/ice/src/service/serverCompiler.ts
- packages/ice/src/types/plugin.ts
- packages/ice/src/webpack/DataLoaderPlugin.ts
- packages/webpack-config/CHANGELOG.md
- packages/webpack-config/src/getCompilerPlugins.ts
- packages/webpack-config/src/types.ts
- tests/integration/with-store.test.ts
fix: https://github.com/alibaba/ice/issues/5577
> feat: redirect imports

- README.md
- website/config/navbar.js
- website/docs/guide/advanced/auth.md
- website/docs/guide/advanced/integrate-from-rax.md
- website/docs/guide/advanced/keep-alive.md
- website/docs/guide/advanced/store.md
- website/docs/guide/advanced/unit-test.md
- website/docs/guide/basic/data-loader.md
- website/docs/guide/basic/router.md
文档里 GitHub 的链接从 ice-lab/ice-next 改到 alibaba/ice
> Docs: modify the url to the correct repo

- packages/ice/CHANGELOG.md
- packages/ice/bin/ice-cli.mjs
detect-port 对 80 端口判断有问题，即使 80 端口没占用，还是会用其他端口代替。因此这个 PR 是调整 commandArgs.port 的优先级，用户设定 port 优先级高，即使端口被占用则让他自己退出进程
> feat: force to use dev port which user set

- packages/ice/CHANGELOG.md
- packages/ice/src/commands/start.ts
- packages/ice/src/esbuild/removeTopLevelCode.ts
- packages/ice/src/plugins/web/index.ts
- packages/ice/src/service/webpackCompiler.ts
- packages/ice/src/types/plugin.ts
- packages/ice/src/utils/prepareURLs.ts
Close https://github.com/alibaba/ice/issues/5640
- 使用 `URL` 代替已经 deprecated 的 `url.format()`
> fix: dev url when enable hash router

- packages/plugin-fusion/CHANGELOG.md
- packages/plugin-fusion/package.json
- packages/plugin-fusion/src/index.ts
Fix error when use plugin without config `theme`
> fix: error when use plugin without config theme

- packages/ice/CHANGELOG.md
- packages/ice/package.json
- pnpm-lock.yaml
Bump @swc/helpers version (0.4.12-> 0.4.14) for module cannot resolve of `@swc/helpers/src/_object_destructuring_empty.mjs`
> fix: bump version of @swc/helpers

- packages/runtime/src/domRender.ts
textContent 替换 textNode 子节点实现，以兼容 weex 下 styleElement 无法通过插入 textNode 来 work 的行为。
> feat: modify textContent to support styleElement in weex

- packages/ice/CHANGELOG.md
- packages/ice/src/utils/babelPluginRemoveCode.ts
- packages/ice/tests/fixtures/removeCode/properties.ts
- packages/ice/tests/removeTopLevelCode.test.ts
Remove code when dead code is `ObjectProperties`
> fix: remove code of ObjectProperties

- examples/memory-router/ice.config.mts
- examples/memory-router/package.json
- examples/memory-router/src/app.tsx
- examples/memory-router/src/document.tsx
- examples/memory-router/src/pages/about.tsx
- examples/memory-router/src/pages/dashboard/blog.tsx
- examples/memory-router/src/pages/index.tsx
- examples/memory-router/tsconfig.json
- packages/ice/src/commands/start.ts
- packages/ice/src/middlewares/ssr/renderMiddleware.ts
- packages/ice/src/plugins/web/index.ts
- packages/ice/src/types/userConfig.ts
- packages/ice/src/utils/generateHTML.ts
- packages/ice/src/utils/getRouterManifest.ts
- packages/runtime/src/routes.tsx
- packages/runtime/src/runClientApp.tsx
- packages/runtime/tests/routes.test.tsx
- pnpm-lock.yaml
- tests/integration/memory-router.test.ts
> feat: enhance memory router

- packages/runtime/src/routes.tsx
如上图：error 对象在字符串中嵌套打印会丢失 stacktrace，导致报错信息有限，不利于排查问题~
> chore: optimize error display

- packages/ice/CHANGELOG.md
- packages/ice/src/createService.ts
- packages/ice/templates/core/entry.client.tsx.ejs
- packages/ice/templates/core/entry.server.ts.ejs
- packages/plugin-icestark/CHANGELOG.md
- packages/plugin-icestark/package.json
- packages/plugin-icestark/src/index.ts
Basename must be modified when render as a child app, framework app will pass basename by `window.ICESTARK.basename`
> fix: modify basename when render as a child app

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- codecov.yml
> fix: update ci workflow

- examples/with-data-loader/src/pages/home.tsx
- packages/ice/src/service/webpackCompiler.ts
- packages/ice/src/webpack/DataLoaderPlugin.ts
- tests/integration/with-data-loader.test.ts
- data-loader.js 产物使用 serverCompiler 进行编译，但是是运行在 client 端的文件
> fix: data-loader using serverCompiler with renderer client

- website/docs/guide/advanced/update-from-icejs2.md
十分抱歉，上个 PR 过于心急其实把正确的给改错了...
原因是我删掉了本地生成的临时 .ice 文件夹，导致报错告诉我找不到 ice...，便以为应该从 @ice/app 中引入 defineAppConfig
十分抱歉，十分抱歉
> docs: fix import defineAppConfigh from ice

- .changeset/famous-peas-visit.md
- .changeset/forty-zoos-talk.md
- .changeset/plenty-pans-flow.md
- .changeset/pre.json
- packages/bundles/package.json
- packages/bundles/scripts/tasks.ts
- packages/ice/CHANGELOG.md
- packages/ice/package.json
- packages/ice/src/esbuild/external.ts
- packages/ice/src/esbuild/transformImport.ts
- packages/ice/src/service/preBundleDeps.ts
- packages/ice/src/service/serverCompiler.ts
- packages/ice/src/utils/getServerCompilerPlugin.ts
- packages/ice/tests/preBundleCJSDeps.test.ts
- packages/ice/tests/transformImport.test.ts
- packages/miniapp-react-dom/CHANGELOG.md
- packages/miniapp-react-dom/package.json
- packages/miniapp-runtime/CHANGELOG.md
- packages/miniapp-runtime/package.json
- packages/plugin-auth/package.json
- packages/plugin-icestark/package.json
- packages/plugin-miniapp/CHANGELOG.md
- packages/plugin-miniapp/package.json
- packages/plugin-request/package.json
- packages/plugin-store/package.json
- packages/plugin-store/src/runtime.tsx
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- pnpm-lock.yaml
预打包依赖过程，由于预打包依赖的格式是 cjs，如果依赖中的依赖是被 external 的，那么预构建产物中将会是 require('xxx')。Server Bundle 如果是在 ESM 下运行的话，就会直接报错
https://github.com/evanw/esbuild/issues/1921#issuecomment-1152991694
> fix: prebundle esm module error

- .changeset/quick-mails-draw.md
- packages/plugin-jsx-plus/package.json
- packages/plugin-jsx-plus/src/index.ts
忽略 babel-plugin-transform-jsx-fragment 的 module check, 以避免在 rax-compat 场景下 mismatch 的问题
> feat: enable ignoreModuleCheck to support compat rax

- .changeset/strong-socks-invite.md
- examples/with-nested-routes/ice.config.mts
- packages/ice/src/config.ts
- packages/ice/src/createService.ts
- packages/ice/src/getWatchEvents.ts
- packages/ice/src/routes.ts
- packages/ice/src/types/userConfig.ts
- packages/ice/templates/core/routes.ts.ejs
- packages/webpack-config/src/config/splitChunks.ts
- packages/webpack-config/src/index.ts
- packages/webpack-config/src/types.ts
- website/docs/guide/basic/config.md
> feat: support code spiliting strategy

- .changeset/eleven-spiders-yell.md
- packages/plugin-pha/src/index.ts
插件调用参数无法仅添加preload：true，因为类型要求所有key必填
> Feat/pha: support plugin-pha interface optional

- .github/workflows/website.yml
Do not remove ice.png when deploy website
> fix: do not clean contributor png when deploy website

- .changeset/cuddly-rocks-warn.md
- packages/runtime/src/runServerApp.tsx
修复 distType 只包含 javascript 的时候不应该打出 html 文件的问题。
close https://github.com/alibaba/ice/issues/5972
> fix: should not build html file when distType has not html

- packages/ice/src/config.ts
Make sure config.splitChunks is not overwritten when codeSplitting is set
Relate to #5957
> fix: make sure config.splitChunks is not overwritten

- .changeset/brave-hotels-visit.md
- packages/ice/src/types/userConfig.ts
`server.onDemand` is optional.
> chore: optional ts type of onDemand

- .changeset/silly-jokes-mix.md
- packages/plugin-fusion/src/index.ts
> hotfix: add icon style when config themePackage

- .changeset/eighty-swans-arrive.md
- .changeset/new-lamps-argue.md
- .changeset/soft-sloths-join.md
- packages/ice/src/createService.ts
- packages/ice/src/types/plugin.ts
- packages/ice/src/utils/logger.ts
- packages/plugin-pha/src/constants.ts
- packages/plugin-pha/src/generateManifest.ts
- packages/plugin-pha/src/index.ts
- packages/plugin-pha/src/phaMiddleware.ts
如果 data loader 存在立即执行代码，增加保护措施，避免报错引起 Manifest 构建失败
> fix: pha with data loader

- .changeset/tame-cherries-invite.md
- packages/webpack-config/src/index.ts
Fix: #5966
Recommand to use `import.meta.rerender` for distinguish between csr, ssr and ssg.
> fix: make sure server env variable is always false

- .changeset/tasty-donkeys-reply.md
- .changeset/tricky-ways-tap.md
- packages/ice/src/utils/getRouterBasename.ts
- packages/runtime/src/runClientApp.tsx
- packages/runtime/src/runServerApp.tsx
- packages/runtime/src/utils/addLeadingSlash.ts
- packages/runtime/tests/runClientApp.test.tsx
Add leading slash for basename, otherwise it may cause error below:
> fix: add leading slash for basename

- .changeset/rich-carpets-drop.md
- packages/create-ice/package.json
- packages/create-ice/src/create.ts
- pnpm-lock.yaml
使用  `@iceworks/generate-project@2.x` 创建脚手架。
Close #5720
> feat: use latest @iceworks/generate-project to generate scaffold

- .changeset/hip-moles-cheat.md
- packages/ice/src/esbuild/externalNodeBuiltin.ts
- packages/ice/src/service/config.ts
Relate to #6041
如果直接设置 node 不去设置 banner 有可能会报 Dynamic require 错误，设置 banner 的情况下，由于 routes-config.bundle.mjs 会再次被引入打包，有记录命名冲突
> fix: external node builtin modules

- .changeset/sixty-walls-sin.md
- packages/webpack-config/src/index.ts
本地调试下，开启 compress 配置项后，流式渲染无法正常工作。考虑到对本地调试影响不大，故直接关掉
> feat: disable compress config in dev server for streaming render

- .changeset/tricky-fans-shave.md
- packages/ice/src/createService.ts
- packages/ice/src/service/ServerRunner.ts
SSR and SSG both are disabled, it may also cause server error such as `window is undefined` when using onDemand compiling.
> fix: remove all exports of routes when render mode is csr

- .changeset/wise-snails-sip.md
- packages/ice/src/createService.ts
- packages/ice/src/utils/getRuntimeModules.ts
Close: https://github.com/alibaba/ice/issues/6162
规定自定义插件写的 runtime 路径是绝对路径，如果在 windows 系统中，拿到的路径是不符合 ESM 模块引入规范的。因此在最终 runtimeModules 中引入 runtime 时候，需要使用相对路径引入
> fix: compatible with runtime absolute path on win32

- .changeset/stale-ants-notice.md
- packages/ice/src/service/serverCompiler.ts
Create esbuild context when dev
> fix: only create esbuild context when dev

- .changeset/lazy-dodos-compare.md
- packages/rax-compat/package.json
- packages/rax-compat/src/compat/element.ts
- packages/rax-compat/src/create-element.ts
- packages/rax-compat/src/hooks.ts
- packages/rax-compat/src/index.ts
- packages/rax-compat/src/props.ts
- packages/rax-compat/src/render.ts
- packages/rax-compat/src/runtime/jsx-dev-runtime.ts
- packages/rax-compat/src/runtime/jsx-runtime.ts
rax-compat 目前的构建产物是 .js 后缀，并且使用 ESM，在其他模块直接引入 rax-compat 会报错（因为当做 cjs 模块处理）
> feat: enable type=module to rax-compat

- .changeset/beige-colts-march.md
- packages/ice/src/commands/build.ts
- packages/ice/src/commands/start.ts
- packages/webpack-config/README.md
- packages/webpack-config/src/index.ts
在框架打包不同目标（target）产物时，希望编译打包组件对应 target 的产物，这样一定程度上可以减小 最终 bundle 的产物
假设有以下的组件 exports 导出：
```json
{
"name": "@ice/component",
"version": "1.0.0",
"exports": {
".": {
"web": "./web.js",
"miniapp": "./miniapp.js",
"weex": "./weex.js",
"default": "./index.js"
}
}
}
```
将会根据当前框架编译的 `target` 值，寻找组件导出的 conditionName 对应的入口文件，然后进行打包。
这样做的好处是，如果一个组件有不同平台的产物，框架在构建的时候找到对应平台的 entry 打包可进一步减少产物体积，避免把其他平台的产物内容也打包进来。
对比与原来的 universal-env，这种做法少了 Tree Shaking 和编译的时间。
> feat: support match target entry to bundle

- .changeset/olive-bobcats-trade.md
- packages/rax-compat/src/hooks.ts
- packages/rax-compat/src/ref.ts
- packages/rax-compat/tests/hooks.test.tsx
1. fix: state 被污染的情况
由于在 setState 的实现中，里面的 updateState方法会获取 eagerState 来判断是否需要更新，但是在使用了 useCallback 之后，这里面拿到的 eagerState 的值是定义是的，不会更新。
所以通过 useRef 在定义时创建一个共享的对象，使用这个共享对象来存储 eagerState
2. fix https://github.com/alibaba/ice/issues/6165
> fix: rax compat state

- .changeset/early-pets-shake.md
- .changeset/pretty-socks-attack.md
- packages/ice/package.json
- packages/webpack-config/src/utils/transformImport.ts
- packages/webpack-config/tests/transformImport.test.ts
- pnpm-lock.yaml
- @swc/helpers 版本升级到 0.5.1
- cjs 使用路径修改，使用标准 cjs 模块
> fix: bump @swc/helpers to 0.5.1

- .changeset/dry-crabs-deny.md
- .changeset/young-mice-joke.md
- packages/ice/src/commands/build.ts
- packages/ice/src/commands/start.ts
- packages/ice/src/plugins/web/task.ts
- packages/webpack-config/src/index.ts
- packages/webpack-config/src/types.ts
原来的写法是统一读取 commandArgs 上的 target 字段，如果有多个 task 的情况下，会导致每个 task 的 target 都是一样的，最后导致 conditionName 的设置有问题。
> fix: read the same task target

- website/docs/guide/basic/config.md
- react 和 react-dom 一般是同时 external 的，在文档里尽可能写正确
- 更新 cdn 的地址为 react 和 react-dom 18 版本
> docs: update externals config

- packages/plugin-icestark/src/runtime/framework.tsx
- packages/runtime/src/ClientRouter.tsx
- packages/runtime/src/ServerRouter.tsx
- packages/runtime/src/runClientApp.tsx
- packages/runtime/src/runServerApp.tsx
- packages/runtime/src/runtime.tsx
- packages/runtime/src/types.ts
升级 react-router-dom 到最新版本后，设置 basename 为 `/app` 后，如果 Link 组件是下面的写法：
```tsx
<Link to='/aaa'>aaa</Link>
```
这样路由地址直接跳转到 `/aaa`，而不是期望的 `/app/aaa`，导致无法正确匹配并渲染对应的组件。与之前的表现不一致
createBrowser 默认会开启 v7_prependBasename，这样就可以自动添加 basename 到路由地址：
https://github.com/remix-run/react-router/blob/853a9382b748466f9bf1af5c4c7e5571670f8b97/packages/react-router-dom/index.tsx#L223
> fix: basename not prepend

- .changeset/dull-hounds-hunt.md
- packages/plugin-store/src/index.ts
原先部分代码移除能力由 babel 封装的 esbuild 插件处理，目前代码移除统一收敛至 swc 编译，需要调整 store 插件注入代码的顺序，避免使用 store 场景下 store 源码未被移除的问题
> fix: import store source before swc compiler

- .changeset/plenty-rings-hammer.md
- examples/rax-inline-style/src/document.tsx
- packages/plugin-rax-compat/src/index.ts
所有文件中如果有 jsx 注释了，就应该使用 classic 模式，而不应该只判断是否有 import rax
> fix: jsx comment

- .changeset/giant-badgers-divide.md
- packages/runtime/src/RouteContext.ts
Compatible with hmr when data get undefined.
> fix: compatible with hmr when data get undefined

- .changeset/heavy-eggs-itch.md
- packages/ice/CHANGELOG.md
- packages/ice/src/createService.ts
- packages/ice/src/service/ServerRunner.ts
Pass `getRoutesFile` for onDemand server runner.
> fix: getRoutesFile is undefined when use onDemand server

- .changeset/ninety-mice-attack.md
- packages/runtime/src/runServerApp.tsx
reject error 后需要 return，避免进入后续逻辑
> fix: ssr error handle

- .changeset/perfect-bags-hug.md
- packages/webpack-config/src/unPlugins/compilation.ts
swc minify will hang on when '@remix-run/router' is not compiled
> fix: compile @remix-run/router when minify is swc

- .changeset/big-ravens-refuse.md
- packages/runtime/src/runClientApp.tsx
开启单路由和 SSG 的情况下，加载组件模块的时候直接报错 `lazy is not defined` 
已经前置通过 `lazy()` 加载过了组件并设置成 undefined，后续加载过程中不需要再加载，应该从缓存中拿组件实例
> fix: load route module error when only has one router

- packages/runtime/src/dataLoader.ts
detail: SSR compile time data field 'loaderData' not match runtime 'routesData'
Fix: https://github.com/alibaba/ice/issues/6306
> fix(runtime): when SSR client send extra useless requests (fix #6306)

- .changeset/hip-adults-trade.md
- packages/plugin-rax-compat/package.json
- packages/plugin-rax-compat/src/index.ts
- pnpm-lock.yaml
开启 [syntaxFeatures.exportDefaultFrom](https://ice3.alibaba-inc.com/v3/docs/guide/basic/config#syntaxfeatures) 选项并且开启 rax-compat 插件后，对于 `export default from xxx` 的语法不能正常解析编译
rax-compat 插件改写了 compilationConfig 从对象变为函数，导致原来的 `compilationConfig: { exportDefaultFrom: true }` 对象丢掉了。因此需要把原来的对象拷贝过去。
https://github.com/alibaba/ice/blob/45cb1c779dbe88805a3bcc7dcce538108b0cc328/packages/plugin-rax-compat/src/index.ts#L71
> fix: compilation config not extend

- .changeset/quick-oranges-fly.md
- packages/plugin-rax-compat/src/index.ts
- tests/integration/rax-inline-style.test.ts
移除了 plugin-rax-compat 中的 server.buildOptions 配置，这一配置导致了项目中存在使用 tsc 或 jsx: preserve 构建的依赖时，启用 rax-compat，会出现 createElement is not defined 错误。
> remove plugin-rax-compat server options

- packages/plugin-rax-compat/src/index.ts
- website/docs/guide/advanced/rax-compat.md
说明：inlineStyle 是具有传染性的，如果项目依赖了启用 inlineStyle 构建的模块，则此项目也必须启用 inlineStyle（即 stylesheet-loader），否则无法加载这些模块的样式。但 inlineStyle 应该被视为废弃的行为，同时可能导致其它非内联构建的模块出现问题（如依赖了 rax-swiper 的模块）。因此这个 PR 引入了文件粒度的配置，支持用户通过函数来延迟决定当前模块应该使用何种行为进行构建。
> Support inline style filter

- .changeset/flat-spies-attack.md
- packages/ice/src/service/config.ts
Always external dependencies when get config otherwise `.ice/routes-config.bundle.mjs` will pack @ice/runtime and dependencies when server.bundle is true.
> fix: always external dependencies when get config

- .changeset/tricky-panthers-applaud.md
- packages/webpack-config/src/compileExcludes.ts
Do not compile runtime library such as @babel/runtime, tslib, @swc/helpers
> fix: do not compile runtime library of tslib

- .changeset/flat-dodos-sniff.md
- packages/plugin-rax-compat/src/index.ts
TL;DR: 确保仅在 inlineStyle 为函数，且返回了 false 的情况下才更改原逻辑。
预期的正常逻辑：
- `inlineStyle: true`
- ExternalStyleLoader → 处理 global.css / *.module.css
- InlineStyleLoader → 处理所有其它 *.css 逻辑，将其处理为 JS 对象
- `inlineStyle: false`
- ExternalStyleLoader → 处理所有 CSS 逻辑
问题逻辑：
- `inlineStyle: true`
- ExternalStyleLoader → 处理 global.css / *.module.css **且被 inlineStyleFilter 显式返回 false 的文件**，也就是此时 `inlineStyle: true` （原逻辑中，等价于 `filter: () => true`）会导致且条件始终不满足，导致所有样式文件被 InlineStyleLoader 处理。
修正：
- 仅在 inlineStyle 显式传入一个函数，并且对当前的文件返回了 false 时，才使用 ExternalStyleLoader，否则对于 `inlineStyle: true` 或返回 filter 返回 true 的情况，都保持原有的正常逻辑。
> fix: fix inlineStyle filter function check

- packages/runtime/src/runServerApp.tsx
Fix the following warning.  不需要发布版本
> fix: unnecessary escape character

- .changeset/breezy-falcons-smell.md
- packages/ice/package.json
- packages/runtime/package.json
- packages/runtime/src/runClientApp.tsx
- pnpm-lock.yaml
> v5Compat is actived for the backforward  to use history API such as `history.push`,
> currently it will be replace by navigate api after router is created https://github.com/alibaba/ice/blob/ae705c03e8b6aa5ab4c7678c58788094f9e3d66d/packages/runtime/src/ClientRouter.tsx#L43
Fix #6390
> fix: render twice when navigate

- .changeset/kind-singers-jump.md
- packages/runtime/src/Suspense.tsx
Do not mutate data return by useSuspenseData  when csr, otherwise it may cause mulit time render in nested `withSuspense`.
> fix: do not mutate data return by useSuspenseData  when csr

- .changeset/violet-coats-rescue.md
- examples/basic-project/src/app.tsx
- packages/ice/src/createService.ts
- packages/ice/templates/core/entry.client.tsx.ejs
- packages/ice/templates/core/routes.tsx.ejs
- packages/runtime/src/index.ts
- packages/runtime/src/runClientApp.tsx
```ts
// Custom app render by export runApp function in `src/app.ts`
export const runApp = (render, options) => {
// render 为框架默认的渲染方法，options 为框架默认的 render options
render();
};
```
> feat: support app config of runApp

- packages/ice/src/createService.ts
- packages/ice/src/service/webpackCompiler.ts
- packages/ice/templates/core/entry.client.tsx.ejs
Default imported will cause build warning when attempt to access props which is not exported in IIFE.
> fix: build warning of runApp is not exported

- .changeset/neat-apples-divide.md
- packages/rax-compat/src/container-root-map.ts
- packages/rax-compat/src/render.ts
- packages/rax-compat/src/unmount-component-at-node.ts
- packages/rax-compat/tsconfig.json
- Fixs: Rax-Compat 下， `unmountComponentAtNode` 方法没有正确触发 Container 内部的 useEffect cleanup 流程。
- 由于 `render` 方法内部已经替换为 `createRoot`，而 React DOM 的 `unmountComponentAtNode` 方法不允许使用与 `createRoot` 相同的入参（即，`createRoot(container)` 后 `unmountComponentAtNode(container)`），同时 React 18 将废弃此方法，故不考虑用此方式实现。
- 为了直接抹平与 Rax 下的差异，无需模块代码变更，考虑使用 WeakMap 保存 container-root 关联，在 `render` 时保存此 container 对应的 root，并在 `unmountComponentAtNode` 时查找到对应的 root，调用 `root.unmount()`。
> Fix unmountComponentAtNode compat rax

- .changeset/healthy-crabs-decide.md
- packages/bundles/override/RefreshUtils.js
- packages/bundles/scripts/tasks.ts
路由组件到出 pageConfig、dataLoader 等路由能力时，会导致 HMR 时效，导致应用级别的重新渲染，特别在开启 SSR 后会显示如下错误
ReactRrefresh 插件内部会通过 isReactRefreshBoundary 判断这个文件的更新是不是适用 react fast refresh，对于 ice.js 框架设计上，路由组件可能会导出 `pageConfig`，`dataLoader`，`serverDataLoader`，`staticDataLoader` 这些都是允许的，因此增加  isSafeExport 定制判断，原始代码参考 https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/lib/runtime/RefreshUtils.js
Fix #5535
> fix: hmr failed when export pageConfg or dataLoader in page routes

- .changeset/soft-flies-happen.md
- packages/ice/package.json
Support Node API for other build tools:
```js
import createService from '@ice/app/service';
const service = createService({ rootDir: '', command: 'start', commadArgs: {} });
service.run();
```
Close #6441
> Chore: add exports of service for node api

- .changeset/famous-bottles-lick.md
- packages/ice/src/routes.ts
- packages/ice/src/service/analyze.ts
- packages/route-manifest/src/index.ts
- packages/route-manifest/src/routes.ts
- packages/route-manifest/tests/__snapshots__/generateRouteManifest.spec.ts.snap
- packages/route-manifest/tests/generateRouteManifest.spec.ts
Support the usage of define absolute route path:
```js
defineRoutes('/hi', '/...path.jsx');
```
Close #6441
> feat: support define route with absolute path

- .changeset/twenty-rules-attend.md
- packages/runtime/src/Document.tsx
- packages/runtime/src/Suspense.tsx
Compat runtime code with old browsers which depend on `Object.assgin` and `Map`.
> fix: runtime should compat with old browsers

- .changeset/violet-beds-wave.md
- packages/bundles/package.json
- packages/ice/package.json
- packages/ice/src/bundler/rspack/build.ts
- packages/ice/src/bundler/rspack/formatStats.ts
- packages/ice/src/bundler/types.ts
- packages/rspack-config/package.json
- pnpm-lock.yaml
Bump rspack version(0.3.0) for more hook and plugin support,  visit [announcing](https://www.rspack.dev/blog/announcing-0.3.html#breaking-changes) for more details.
> chore: bump rspack version for more hook and plugin support

- .changeset/green-kangaroos-cry.md
- packages/runtime/src/polyfills/signal.ts
在 webpack 打包时，如果该包为 `type: module` 的包，将不会对 require 进行处理，如果一旦 signal 文件在 `polyfill: usage` 场景下引入polyfill 将出现运行时错误
框架改写 core-js 的 import 语句，依赖其导入导出逻辑，因此需要增加 default 导出 https://github.com/alibaba/ice/blob/d8f238a5af3cf56f20b026826088aeb841c2250d/packages/shared-config/src/utils/transformImport.ts#L9-L49
> fix: mark polyfill signal as es module

- .changeset/olive-bikes-carry.md
- examples/basic-project/src/app.tsx
- examples/basic-project/src/document.tsx
- packages/ice/src/constant.ts
- packages/ice/templates/core/entry.server.ts.ejs
- packages/runtime/package.json
- packages/runtime/src/index.ts
- packages/runtime/src/runServerApp.tsx
- packages/runtime/src/types.ts
- pnpm-lock.yaml
Step 1: export `dataLoader` in `src/document.tsx`
```ts
// 这里参考 data-loader 的定义
export const dataLoader = defineDataLoader(() => {/* ... */});
```
Step2: use API `unstable_useDocumentData` imported from `ice`
```ts
import { unstable_useDocumentData } from 'ice';
```
临时解决方案，需要 document 计划改造成 RSC 方式执行
> feat: support API useDocumentData

- .changeset/spicy-planets-push.md
- packages/rspack-config/src/index.ts
Support custom middleware on dev server when use `speedup` mode.
> fix: support custom middleware on dev server

- .changeset/orange-carrots-stare.md
- packages/ice/src/types/plugin.ts
- packages/ice/src/webpack/DataLoaderPlugin.ts
Do not wrap arrow function when format as IIFE for browsers compatibility.
> fix: browsers compatibility of dataLoader

- examples/with-rsc/src/components/RefreshButton.client.tsx
- examples/with-rsc/src/pages/about.tsx
- packages/runtime/src/index.ts
- packages/runtime/src/runRSCClientApp.tsx
更新当前页面的 Server Component，同时保留 Client Component 的状态
> feat: rsc refresh

- .changeset/fuzzy-dolls-tell.md
- packages/ice/package.json
With `typesVersions` TypeScript can find the type definition for exports field correctly:
or it works like:
> fix(@ice/app): add typesVersions for export fields support

- .changeset/tiny-hounds-hope.md
- examples/hash-router/src/pages/layout.tsx
- packages/runtime/src/routes.tsx
Update route config when dataLoader is not defined.
> fix: update route config when dataLoader is not defined

- .changeset/famous-pigs-pretend.md
- packages/runtime/src/requestContext.ts
FC 环境下 ctx.req.url 的参数会被错误处理，而 query 对象又是正确的
这里优先使用 ctx.req.query 信息，一方面规避上面的问题，另外一方面也可以减少不必要的解析
> fix: query info in fc

- .changeset/hungry-lions-build.md
- .changeset/wise-donkeys-relate.md
- packages/ice/src/service/ServerRunner.ts
- packages/runtime/package.json
- packages/runtime/src/index.ts
- packages/runtime/src/react.ts
- packages/shared-config/src/unPlugins/compilation.ts
swc will inject createElement import even in the case of jsx. [Case](https://github.com/swc-project/swc/blob/main/crates/swc_ecma_transforms_react/src/jsx/static_check.rs)
swc support script within automatic runtime in version 1.3.44 and bring a break change for the behavior of import source:
Previously:
```jsx
// <div {...props} key={key} /> transform result in ice.js:
iimport { jsx as _jsx , jsxs as _jsxs , Fragment as _Fragment  } from "@ice/runtime/jsx-runtime";
import { createElement as _createElement  } from "react";
...
```
After @swc/core [1.3.44](https://github.com/swc-project/swc/blob/main/CHANGELOG.md#1344---2023-03-30):
```jsx
// <div {...props} key={key} /> transform result in ice.js:
import { jsx as _jsx , jsxs as _jsxs , Fragment as _Fragment  }  from …
```
> fix: export createElement for react in @ice/runtime

- .changeset/thick-monkeys-call.md
- packages/plugin-rax-compat/src/index.ts
问题：通过 userConfig 设置的 swc 编译配置（比如 syntaxFeatures.exportDefaultFrom），经过 `plugin-rax-compat` 插件处理后会丢失
> fix: user compilation config lose

- .changeset/friendly-olives-relax.md
- packages/runtime/src/routesConfig.ts
In some parcel case oldTags may be removed by other route.
> fix: compatible with tag.parentNode is null when update routes config

- .changeset/empty-islands-unite.md
- packages/plugin-rax-compat/package.json
- packages/plugin-rax-compat/src/index.ts
- packages/plugin-rax-compat/src/rax-compat-legacy-exports.ts.template
Add `legacy` option for `plugin-rax-compat`, which enables compatibility for legacy version rax version like `v0.6.x`.
When `legacy` option enbaled:
- Create `.ice/rax-compat-legacy-exports.ts` file, which patches the exports from `rax-compat`, add missing(removed) exports like `PropTypes`.
- Update `config.alias`, use the created file above as the alias for imports target `rax`, so they can import `PropTypes` from `rax` now.
> Support legacy mode for plugin-rax-compat

- .changeset/cyan-maps-do.md
- packages/runtime/src/runServerApp.tsx
- packages/runtime/src/types.ts
Support options when call document dataLoader.
Beta version: @ice/runtime@1.3.2-canary-cc7e3443c-20231019031627
> feat: support options when call document dataLoader

- .changeset/silent-monkeys-check.md
- packages/bundles/package.json
- packages/bundles/scripts/tasks.ts
- packages/ice/package.json
- packages/ice/src/bundler/config/defaultServerConfig.ts
- packages/ice/src/bundler/config/getUrls.ts
- packages/rspack-config/src/index.ts
- packages/shared-config/src/getCompilerPlugins.ts
- pnpm-lock.yaml
> fix: support transform plugin in speedup mode

- .changeset/orange-onions-relate.md
- packages/ice/src/webpack/DataLoaderPlugin.ts
esbuild 在构建 dataLoader 时会额外引入 let 变量，导致部分浏览器下报错，需要加入黑名单
> fix: data loader output

- .changeset/soft-coats-cover.md
- packages/ice/bin/ice-cli.mjs
- packages/ice/src/createService.ts
Move `requireHook` registry to `createService` file, this should **fixes the HMR** when creating ICE server programtically:
```typescript
import createService from '@ice/app/service';
await createService(/* ... */).run();
```
> fix(@ice/app): requireHook in createService

- .changeset/empty-pillows-bathe.md
- packages/rspack-config/src/assetsRule.ts
It is unnecessary to configure `mimetype` in speedup mode, and it will cause `type: 'asset'` works improperly.
Fix #6628
> fix: assets rule in speedup mode

- .changeset/gorgeous-coins-scream.md
- packages/webpack-config/src/index.ts
`ice.js` should not deal with the assets in public by default, it may cause unexpected error when minify JS while it had been already done.
> fix: do not minify assets in public by default

- .changeset/healthy-icons-scream.md
- packages/shared-config/src/getCompilerPlugins.ts
Unplugin (1.5.0) had been fix the excute order of webpack plugins, it unnecceray to reverse before tranform to webpack plugins.
> Fix: re-order tranform plugins

- packages/bundles/package.json
- packages/shared-config/package.json
- pnpm-lock.yaml
console always print below message when start or build. caniuse-lite is outdated, fix it by upgrading caniuse-lite and browserslist
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
> fix: bump latest version of caniuse-lite

- packages/ice/templates/core/document.tsx.ejs
```diff
- import { Meta, Title, Links, Main, Scripts } from 'ice';
+ import { Meta, Title, Links, Main, Scripts } from '@ice/runtime';
```
Import from `'@ice/runtime'` instead of `'ice'` as default document was located in the alias resolution path.
> fix: fix default document import

- .changeset/slimy-rats-dance.md
- packages/ice/bin/ice-cli.mjs
Set exit code to 1 to exit process with failure code, otherwise CI may regard build as success.
> fix: better error handling of build script

- .changeset/sharp-carrots-protect.md
- packages/ice/package.json
remove `./types` export in `typesVersions` field to be compatible with `/// <reference types="@ice/app/types" />` in scaffolds
> chore: remove types export

- website/docs/guide/advanced/request.md
运行时的配置需要加上 `ICE_` 前缀 https://v3.ice.work/docs/guide/basic/env#%E8%BF%90%E8%A1%8C%E6%97%B6
> docs: fix request base url env

- packages/bundles/override/rspack/normalization.js
- packages/bundles/package.json
- packages/bundles/scripts/tasks.ts
- packages/bundles/src/plugin-refresh.ts
- packages/rspack-config/src/index.ts
- packages/rspack-config/src/splitChunks.ts
- pnpm-lock.yaml
> fix: use built-in split chunks strategy by default

- package.json
- packages/bundles/package.json
- packages/ice/package.json
- patches/unplugin@1.5.1.patch
- pnpm-lock.yaml
code: https://github.com/unjs/unplugin/blob/main/src/rspack/index.ts#L43
It will break binary file when use default load
Fix #6692
> fix: should not include everything when generate rspack plugin by unplugin

- packages/ice/src/config.ts
- packages/rspack-config/src/index.ts
Use regex rule instead of function, it will reduce build time.
> feat: optimize compile rule

- .changeset/twenty-cycles-marry.md
- package.json
- packages/bundles/package.json
- packages/ice/package.json
- packages/rspack-config/package.json
- packages/rspack-config/src/index.ts
- packages/rspack-config/src/splitChunks.ts
- patches/@rspack__core@0.4.5.patch
- pnpm-lock.yaml
Relate to https://github.com/ice-lab/icepack/pull/28
> Fix: pack error when use speedup mode

- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/singleRouter.tsx
Compatible with API matchRoutes when basename is not provided in single route mode.
> fix: compatible with API matchRoutes when basename is not provided

- .changeset/five-kids-sit.md
- .changeset/thin-ligers-taste.md
- examples/with-antd5/ice.config.mts
- packages/bundles/package.json
- packages/ice/src/config.ts
- packages/ice/src/types/userConfig.ts
- packages/rspack-config/src/index.ts
- packages/shared-config/src/types.ts
- pnpm-lock.yaml
Relate to https://github.com/ice-lab/icepack/pull/30
在简单使用 antd 的项目，解析模块数量从 `2738` 下降到 `309`，启动时间优化从 `358ms` 到 `166ms`
由于减小的压缩阶段的 treeshaking 处理，让整体 build 提升更加明显，从 `1300ms+` 提升值 `300ms+`
> Feat: support optimize package import

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- .changeset/red-walls-vanish.md
- packages/runtime/src/routes.tsx
Avoid unexpected slash in route path in recursive.
> Fix: avoid unexpected slash in route path

- .changeset/orange-sheep-appear.md
- packages/runtime/src/ClientRouter.tsx
- packages/runtime/src/utils/deprecatedHistory.ts
Do not log warning message when use router api after router has been initialized.
> fix: do not log warning message when use router api

- .changeset/twelve-radios-travel.md
- packages/plugin-unocss/src/index.ts
Disable persistent cache for unocss generation.
> Fix: disable persistent cache for unocss generation

- .changeset/yellow-donkeys-fetch.md
- packages/plugin-unocss/package.json
- packages/plugin-unocss/src/index.ts
- packages/plugin-unocss/uno.css
- pnpm-lock.yaml
Use postcss plugin to transform unocss, so plugin can be used in both webpack mode and speedup mode.
> Feat: use postcss plugin to transform unocss

- packages/runtime/CHANGELOG.md
- packages/runtime/src/runClientApp.tsx
- packages/runtime/src/singleRouter.tsx
Pass customized location for match route when use single router mode.
> Fix: single router is not work when route path is customized

- .changeset/serious-birds-hang.md
- packages/rspack-config/src/index.ts
- packages/shared-config/src/index.ts
- packages/shared-config/src/utils/getDevtool.ts
- packages/webpack-config/src/index.ts
Remove enforce post of compilation loader, otherwise the fast-refresh injection code will appear in source map.
The order of rules will make sure that the compilation loader will be executed after custom transform plugin.
> Fix: improve dev sourcemap

- .changeset/giant-socks-marry.md
- packages/plugin-fusion/src/index.ts
- packages/style-import/package.json
- packages/style-import/src/index.ts
- packages/style-import/tests/importStyle.test.ts
- pnpm-lock.yaml
> Feat: optimize theme package injection

- .changeset/gentle-trainers-check.md
- package.json
- packages/shared-config/src/getCompilerPlugins.ts
- patches/unplugin@1.6.0.patch
- pnpm-lock.yaml
Ensure that custom transformers, when running in rspack mode, are defined after the built-in loaders. This order is crucial because if a custom transformer precedes the built-in loaders, the code passed to the unplugin may differ from what would be passed in webpack mod.
> Fix: align the order and content of custom transformer with webpack

- .changeset/famous-roses-hide.md
- packages/rax-compat/package.json
- packages/rax-compat/src/runtime/index.ts
修正了在特定情况下，swc 的转换代码会进行如下的代码转换：
```tsx
import Rax from 'rax-compat';
import { createElement } from 'rax-compat/runtime';
```
这个PR 为 rax-compat 提供了 `/runtime` 的 subpath。
> fix(rax-compat): fix createElement runtime import

- .changeset/brave-items-cover.md
- examples/with-keep-alive/src/pages/layout.tsx
- packages/runtime/src/KeepAliveOutlet.tsx
Support props `limit` and `paths` for KeepAliveOutlet.
> Feat: support props for KeepAliveOutlet

- .changeset/metal-turtles-design.md
- packages/runtime/src/singleRouter.tsx
Try to ignore `basename` in single route mode when route do not match.
> Fix: ignore basename in single route mode when route do not match

- .changeset/good-pans-joke.md
- package.json
- packages/bundles/package.json
- packages/ice/package.json
- packages/ice/src/bundler/rspack/formatStats.ts
- packages/ice/tsconfig.json
- packages/rspack-config/package.json
- patches/@rspack__core@0.5.7.patch
- pnpm-lock.yaml
Relate to https://github.com/ice-lab/icepack/pull/40
> Feat: upgrade pack-binding for new features

- packages/runtime/CHANGELOG.md
- packages/runtime/data-loader.d.ts
- packages/runtime/package.json
Add export type for `@ice/runtime/data-loader`.
> chore: add export type of @ice/runtime

- .changeset/wicked-points-fetch.md
- packages/ice/src/createService.ts
- packages/ice/src/utils/runtimeEnv.ts
- packages/ice/templates/core/entry.client.tsx.ejs
- packages/runtime/src/appData.ts
- packages/runtime/src/routes.tsx
- packages/runtime/src/runClientApp.tsx
The dataLoader runtime is unnecessary when dataLoader is not exported.
> Fix: optimize runtime code when dataLoader is not defined

- packages/ice/src/createService.ts
- packages/ice/src/types/plugin.ts
The build process completing successfully even if the deprecated API addTargetExport is called. However this usage will lead to an unexpected runtime error.
To ensure reliability and prevent such issues, the deprecated api should be removed.
> Fix: remove deprecated api of addTargetExport

- .changeset/odd-crews-sing.md
- examples/with-request/src/app.tsx
- packages/ice/src/bundler/rspack/getConfig.ts
Do not remove request config of dataLoader compilation in speedup mode.
Fix #6868
> Fix: request config is not work in dataLoader compilation

- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/routes.tsx
`serverDataLoader` will been remove if dataLoader is not defined. 
Route loader should always been called in server side because of the serverDataLoader.
> Fix: serverDataLoader is not work when dataLoader is not defined

- .changeset/little-cheetahs-raise.md
- packages/ice/src/constant.ts
- packages/runtime/src/index.ts
- packages/runtime/src/router.ts
- packages/runtime/src/routes.tsx
- export useAsyncData for component `Await`
- Add props type of component `Await`
> Feat: export useAsyncData for component Await

- .changeset/thirty-islands-shop.md
- packages/plugin-intl/src/index.ts
- packages/plugin-intl/src/runtime.tsx
- packages/plugin-intl/templates/locales.ts.ejs
Support get locale messages from global.
> feat: support get locale messages from global

- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/singleRouter.tsx
Add export of `useAsyncValue` in single route mode.
> Fix: add export of useAsyncValue in single route mode

- packages/plugin-intl/CHANGELOG.md
- packages/plugin-intl/package.json
- packages/plugin-intl/src/runtime.tsx
Compat with the navigator language return with underslash.
> Fix: compat with the navigator language return with underslash

- website/docs/guide/advanced/icestark.md
ice2主应用，ice3子应用的话，加载子应用提示找不到生命周期。原因是ice2的主应用会去读window.ICESTARK.library，获取当前子应用在window下的模块对象，但是ice3子应用不会往window.ICESTARK.library设置子应用的模块名称，而是直接挂到window下，如window.['ice3AppName'] = {mount: xx, unmount: xx}，ice2读不到。
因此在@ice/plugin-stark插件增加了了一个参数，并在插件注入entryCode的部分，增加对这个参数的判断，如果有传入，就往window.ICESTARK.library设置子应用的模块名称。
> feat: support ice2 main app and ice3 micro app

- .changeset/early-tomatoes-beg.md
- packages/plugin-jsx-plus/src/index.ts
Allow decorators-legacy syntax in js file.
> fix: allow decorators-legacy syntax in js file

- .changeset/sweet-fishes-draw.md
- packages/plugin-intl/README.md
- packages/plugin-intl/package.json
- packages/plugin-intl/runtime-simple.d.ts
- packages/plugin-intl/src/index.ts
- packages/plugin-intl/src/intl-until.ts
- packages/plugin-intl/src/runtime-simple.ts
- packages/plugin-intl/src/runtime.tsx
Support new options `intlSolution` to support remove `react-intl` in the scenario of using `intl` for simple case.
> Feat: support the simple solution of intl

- .changeset/popular-buttons-behave.md
- packages/rspack-config/src/index.ts
> fix: support compileDependencies in speedup mode

- .changeset/seven-mails-tickle.md
- examples/with-suspense-ssr/src/document.tsx
- packages/runtime/src/Suspense.tsx
close https://github.com/alibaba/ice/issues/6973
> feat: support suspence event

- .changeset/happy-cars-punch.md
- packages/runtime/src/KeepAliveOutlet.tsx
Avoid infinite setOutlets loop when config keepAlivePaths.
> fix: avoid infinite setOutlets loop when config keepAlivePaths

- .changeset/gorgeous-lemons-drop.md
- packages/shared-config/src/index.ts
- packages/shared-config/src/unPlugins/compilation.ts
- packages/webpack-config/src/index.ts
> Fix: add browsers list config to cache key

- packages/runtime/src/runClientApp.tsx
- packages/runtime/src/types.ts
线上hydrate由于报错栈没有参考价值，不能快速修复，在 appConfig 添加 `onBeforeHydrate` hook 来让开发者获取 hydrate 前后的 DOM 然后上报，用于快速定位问题
```diff
// src/app.ts
import { defineAppConfig } from 'ice';
// App config, see https://ice3.alibaba-inc.com/v3/docs/guide/basic/app
export default defineAppConfig(() => {
let beforeHydrateHtml = '';
return {
// Set your configs here.
app: {
onRecoverableError(error: any, errorInfo) {
+        // 上报 监控平台
+        if(reportLog){ 
+ 				const currentHtml = document.documentElement.innerHTML
+         reportLog({
+            code: `hydrate 错误 DOM Diff`,
+            message: {
+              beforeHydrateHtml,
+              currentHtml
+            },
+            level: 'Debug',
+          });
+        }
+      },
+      onBeforeHydrate() {
+        beforeHydrateHtml = …
```
> feat: onbeforehydrate

- .changeset/breezy-ants-clap.md
- packages/rspack-config/src/splitChunks.ts
Fix  the issue which `splitChunk: false` do not work properly in speedup mode.
> Fix: splitChunk config in speedup mode

- packages/jsx-runtime/package.json
- packages/jsx-runtime/src/createElement.ts
- packages/jsx-runtime/src/index.ts
- pnpm-lock.yaml
> https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#manual-babel-setup
根据 React 文档说明，自定义的 `jsx runtime` 需要兼容一个异常 case，这个 case 需要使用 `createElement` 来进行 jsx 的转换，如果指定了 `importSource`，则会使用 importSource 导出的 createElement
> 详细阅读 https://github.com/facebook/react/issues/20031#issuecomment-710346866
`<div {...obj} key="foo" />`： 即在 key 前有 spread object 的行为，会编译成使用 importSource(默认 react) 的 createElement 
```tsx
export default function Mod(props) {
return (
<>
<div {...{ key: 123 }} style={props.style} key='sss'>
hello mod
</div>
</>
);
}
```
编译结果：
```js
import { createElement as _createElement } from "@ice/jsx-runtime";
import { Fragment as _Fragment, jsx as _jsx } from "@ice/jsx-runtime/jsx-runtime";
export default function Mod(props) {
return _jsx(_Fragment, { …
```
> fix: should re-export createElement for backwards compatibility

- packages/plugin-request/src/hooks.ts
去掉默认空数组的赋值，避免 ts 报错
`useRequest(
id => {
return api.publishMicModuleDelete({ ids: [id] });
}
)`
对这种写法，做友好兼容
> useRequest 接口入参类型报错

- examples/with-suspense-ssr/src/document.tsx
- packages/runtime/src/Suspense.tsx
https://github.com/alibaba/ice/pull/6994
改为使用 `performance.mark` 以避免事件监听时可能存在的时序问题
> feat: support suspense event

- packages/ice/package.json
- packages/jsx-runtime/package.json
- packages/plugin-i18n/package.json
- packages/rax-compat/package.json
- patches/@rspack__core@1.2.2.patch
- pnpm-lock.yaml
This pull request includes several updates and patches across multiple packages, primarily focusing on updating the `@swc/helpers` dependency and modifying the version check in `@rspack/core`.
> fix: remove version check in compiled rspack

- .changeset/metal-poems-dance.md
- packages/ice/src/utils/hasDocument.ts
This pull request includes a fix to the glob pattern for document files in the `@ice/app` package. The most important changes are:
Fixes:
* [`.changeset/metal-poems-dance.md`](diffhunk://#diff-1576c0734f81ee7dc1657c0d1d9b75a6807b9e9bcc1ab5dff3ada207aece80c8R1-R5): Added a changeset entry to document the patch fix for the glob pattern.
* [`packages/ice/src/utils/hasDocument.ts`](diffhunk://#diff-41f2637c3932d33b7526cfc223948f7e2bb455fdb5206872d133d0184ffaf102L5-R5): Corrected the glob pattern to properly include `.js` files by changing `document.{tsx,ts,jsx.js}` to `document.{tsx,ts,jsx,js}`.
> Fix: glob pattern for document file

- packages/plugin-icestark/CHANGELOG.md
- packages/plugin-icestark/package.json
- packages/plugin-icestark/src/index.ts
This pull request includes changes to the `@ice/plugin-icestark` package to fix a type definition and update the version. The most important changes include fixing the plugin type definition for `library` and updating the version in the `package.json` file.
> chore: update plugin option type of plugin-icestark

- website/docs/guide/basic/development.md
Atom is no longer maintained, the team recommends to use other code editors like VSCode.
https://github.blog/news-insights/product-news/sunsetting-atom/
> Removed atom in the IDE section

- .changeset/ten-paws-sort.md
- packages/plugin-i18n/package.json
- packages/plugin-miniapp/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/Suspense.tsx
- packages/runtime/src/runtime.tsx
- packages/runtime/src/types.ts
- pnpm-lock.yaml
This pull request introduces a new feature that allows for custom Suspense wrappers to be registered and used within the runtime. This enables developers to wrap Suspense boundaries with additional components for cross-cutting concerns (e.g., logging, error boundaries, analytics). The implementation involves changes to the runtime's API, context, and the Suspense component itself.
> feat: add SuspenseWrappers to Runtime (#7131)
